@php
    $isArabic = in_array(app()->getLocale(), config('app.arabic_locales', ['ar']), true);
    $setupPercent = ($setup['required_count'] ?? 0) > 0 ? (int) round((($setup['completed_count'] ?? 0) / $setup['required_count']) * 100) : 100;
    $trendMax = max(1, (float) $dashboard['trend']->max(fn (array $day): float => max((float) $day['sales'], (float) $day['purchases'])));
    $trendSalesTotal = (float) $dashboard['trend']->sum(fn (array $day): float => (float) $day['sales']);
    $trendPurchasesTotal = (float) $dashboard['trend']->sum(fn (array $day): float => (float) $day['purchases']);
    $trendHasData = $trendSalesTotal > 0 || $trendPurchasesTotal > 0;
@endphp
<x-layouts::app :title="$isArabic ? 'لوحة القيادة' : 'Operational dashboard'">
<x-app.page max-width="full" class="space-y-4" data-guide="dashboard-header">
    <header class="dashboard-toolbar">
        <div class="min-w-0"><p class="text-xs font-semibold text-primary">{{ $isArabic ? 'مركز العمليات' : 'Operations center' }}</p><h1 class="mt-1 text-2xl font-bold text-text-primary">{{ app()->isLocale('ar-EG') ? 'يا '.(auth()->user()?->name ?? 'فندم').'، عامل إيه النهارده؟' : ($isArabic ? 'لوحة القيادة' : 'Operational dashboard') }}</h1><p class="mt-1 max-w-2xl text-sm text-text-muted">{{ $isArabic ? 'المؤشرات والمهام والاستثناءات المتاحة ضمن نطاق صلاحياتك.' : 'Indicators, tasks, and exceptions available within your authorized scope.' }}</p><div class="dashboard-toolbar__meta"><span class="dashboard-toolbar__chip"><flux:icon.calendar-days class="size-4" /><span dir="ltr">{{ now()->format('Y-m-d') }}</span></span><span class="dashboard-toolbar__chip"><flux:icon.clock class="size-4" />{{ $isArabic ? 'اليوم · آخر 7 أيام للاتجاه' : 'Today · 7-day trend' }}</span></div></div>
        <div class="flex flex-wrap gap-2">@can('pos_sales.create')<flux:button :href="route('pos')" variant="primary" icon="shopping-cart" wire:navigate>{{ $isArabic ? 'فتح نقطة البيع' : 'Open POS' }}</flux:button>@endcan @can('purchase_invoices_supplier_returns.create')<flux:button :href="route('purchasing.invoices')" variant="subtle" icon="receipt-percent" wire:navigate>{{ $isArabic ? 'فاتورة مشتريات' : 'Purchase invoice' }}</flux:button>@endcan @can('inventory_stock_card.create')<flux:button :href="route('inventory.opening.index')" variant="subtle" icon="adjustments-horizontal" wire:navigate>{{ app()->isLocale('ar-EG') ? 'ضيف رصيد افتتاحي' : ($isArabic ? 'إضافة رصيد افتتاحي' : 'Add Opening Inventory') }}</flux:button>@endcan</div>
    </header>

    <section class="dashboard-kpi-grid" aria-label="{{ $isArabic ? 'مؤشرات اليوم والاستثناءات' : 'Today indicators and exceptions' }}">
        @if($dashboard['sales'])<a href="{{ route('sales.invoices') }}" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'مبيعات اليوم' : 'Today sales' }}</p><p class="dashboard-kpi__value" dir="ltr">{{ number_format((float)$dashboard['sales']['total'], 2) }}</p><p class="dashboard-kpi__state">{{ $dashboard['sales']['count'] }} {{ $isArabic ? 'فاتورة معتمدة' : 'approved invoices' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.shopping-cart class="size-5" /></span></a>@endif
        @if($dashboard['purchases'])<a href="{{ route('purchasing.invoices') }}" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'مشتريات اليوم' : 'Today purchases' }}</p><p class="dashboard-kpi__value" dir="ltr">{{ number_format((float)$dashboard['purchases']['total'], 2) }}</p><p class="dashboard-kpi__state">{{ $dashboard['purchases']['count'] }} {{ $isArabic ? 'فاتورة معتمدة' : 'approved invoices' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.truck class="size-5" /></span></a>@endif
        @if($dashboard['open_shifts'] !== null)<a href="{{ route('pos.shift') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'الورديات المفتوحة' : 'Open shifts' }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $dashboard['open_shifts'] }}</p><p class="dashboard-kpi__state">{{ $isArabic ? 'وردية ضمن نطاقك' : 'shifts in your scope' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.banknotes class="size-5" /></span></a>@endif
        @if($dashboard['pending_approvals'] !== null)<a href="{{ route('admin.approvals') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'اعتمادات معلقة' : 'Pending approvals' }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $dashboard['pending_approvals'] }}</p><p class="dashboard-kpi__state {{ $dashboard['pending_approvals'] ? 'text-amber-700' : '' }}">{{ $isArabic ? 'بانتظار قرار مخول' : 'awaiting authorized decision' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.check-badge class="size-5" /></span></a>@endif
        @if($dashboard['low_stock_count'] !== null)<a href="{{ route('inventory.balances') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'تنبيهات المخزون' : 'Stock exceptions' }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $dashboard['low_stock_count'] + $dashboard['out_of_stock_count'] }}</p><p class="dashboard-kpi__state"><span class="text-amber-700">{{ $dashboard['low_stock_count'] }} {{ $isArabic ? 'منخفض' : 'low' }}</span> · <span class="text-rose-700">{{ $dashboard['out_of_stock_count'] }} {{ $isArabic ? 'نافد' : 'out' }}</span></p></div><span class="dashboard-kpi__icon"><flux:icon.exclamation-triangle class="size-5" /></span></a>@endif
        @if($dashboard['pending_orders'] !== null)<a href="{{ route('purchasing.orders') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'أوامر قيد الاستلام' : 'Orders in receiving' }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $dashboard['pending_orders'] }}</p><p class="dashboard-kpi__state">{{ $isArabic ? 'مقدم أو معتمد أو جزئي' : 'submitted, approved, or partial' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.clipboard-document-list class="size-5" /></span></a>@endif
        @if($dashboard['pending_returns'] !== null)<a href="{{ route('purchasing.returns') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'مرتجعات تتطلب إجراء' : 'Returns requiring action' }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $dashboard['pending_returns'] }}</p><p class="dashboard-kpi__state">{{ $isArabic ? 'مرتجعات موردين مقدمة' : 'submitted supplier returns' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.arrow-uturn-left class="size-5" /></span></a>@endif
    </section>

    <div class="grid gap-4 2xl:grid-cols-12">
        <section class="dashboard-panel 2xl:col-span-7" aria-labelledby="trend-heading"><div class="dashboard-panel__header"><div><h2 id="trend-heading" class="font-bold">{{ $isArabic ? 'اتجاه المبيعات والمشتريات' : 'Sales and purchase trend' }}</h2><p class="text-xs text-text-muted">{{ $isArabic ? 'قيم يومية فعلية لآخر سبعة أيام' : 'Actual daily values for the last seven days' }}</p></div><div class="flex gap-3 text-xs"><span><i class="me-1 inline-block size-2 rounded-full bg-teal-500"></i>{{ $isArabic ? 'المبيعات' : 'Sales' }}</span><span><i class="me-1 inline-block size-2 rounded-full bg-sky-500"></i>{{ $isArabic ? 'المشتريات' : 'Purchases' }}</span></div></div>@if($trendHasData)<div class="dashboard-trend" role="img" aria-label="{{ $isArabic ? 'مبيعات سبعة أيام '.number_format($trendSalesTotal,2).' ومشتريات '.number_format($trendPurchasesTotal,2) : 'Seven-day sales '.number_format($trendSalesTotal,2).' and purchases '.number_format($trendPurchasesTotal,2) }}">@foreach($dashboard['trend'] as $day)<div class="dashboard-trend__day"><div class="dashboard-trend__bars"><span class="bg-teal-500" style="height:{{ max(2, ((float)$day['sales']/$trendMax)*100) }}%" title="{{ $day['day'] }} · {{ $isArabic ? 'المبيعات' : 'Sales' }} {{ $day['sales'] }}"></span><span class="bg-sky-500" style="height:{{ max(2, ((float)$day['purchases']/$trendMax)*100) }}%" title="{{ $day['day'] }} · {{ $isArabic ? 'المشتريات' : 'Purchases' }} {{ $day['purchases'] }}"></span></div><small dir="ltr">{{ \Illuminate\Support\Carbon::parse($day['day'])->format('m/d') }}</small></div>@endforeach</div>@else<div class="dashboard-trend-empty" role="status"><flux:icon.chart-bar class="size-6" /><p>{{ app()->isLocale('ar-EG') ? 'مفيش حركة مبيعات أو مشتريات خلال الفترة دي.' : ($isArabic ? 'لا توجد حركة مبيعات أو مشتريات خلال هذه الفترة.' : 'No sales or purchase activity exists in this period.') }}</p><div class="dashboard-trend-empty__dates">@foreach($dashboard['trend'] as $day)<span dir="ltr">{{ \Illuminate\Support\Carbon::parse($day['day'])->format('m/d') }}</span>@endforeach</div></div>@endif<p class="dashboard-trend__summary">{{ $isArabic ? 'إجمالي الفترة' : 'Period totals' }}: <span dir="ltr">{{ number_format($trendSalesTotal,2) }}</span> {{ $isArabic ? 'مبيعات' : 'sales' }} · <span dir="ltr">{{ number_format($trendPurchasesTotal,2) }}</span> {{ $isArabic ? 'مشتريات' : 'purchases' }}</p></section>
        @can('pos_sales.view')<section class="dashboard-panel 2xl:col-span-5"><div class="dashboard-panel__header"><div><h2 class="font-bold">{{ $isArabic ? 'المنتجات الأعلى حركة' : 'Top products' }}</h2><p class="text-xs text-text-muted">{{ $isArabic ? 'حسب الكمية المباعة المعتمدة' : 'By approved sold quantity' }}</p></div><a href="{{ route('catalog.products') }}" class="text-xs font-semibold text-primary">{{ $isArabic ? 'المنتجات' : 'Products' }}</a></div><div class="dashboard-list">@forelse($dashboard['top_products'] as $line)<a href="{{ route('catalog.products') }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate text-sm">{{ $isArabic ? $line->product?->name_ar : $line->product?->name_en }}</strong><small class="text-text-muted" dir="ltr">{{ $line->product?->item_code }}</small></span><strong dir="ltr">{{ $line->units }}</strong></a>@empty<div class="dashboard-empty"><flux:icon.chart-bar class="size-6" /><p>{{ app()->isLocale('ar-EG') ? 'مفيش مبيعات كافية لترتيب المنتجات.' : ($isArabic ? 'لا توجد مبيعات كافية لترتيب المنتجات.' : 'No sales data is available for product ranking.') }}</p></div>@endforelse</div></section>@endcan
    </div>

    <div class="grid gap-4 xl:grid-cols-3">
        @if($dashboard['sales'])<section class="dashboard-panel"><div class="dashboard-panel__header"><div><h2 class="font-bold">{{ $isArabic ? 'أحدث المبيعات' : 'Recent sales' }}</h2><p class="text-xs text-text-muted">{{ $isArabic ? 'آخر العمليات المعتمدة' : 'Latest approved transactions' }}</p></div><a href="{{ route('sales.invoices') }}" class="text-xs font-semibold text-primary">{{ app()->isLocale('ar-EG') ? 'عرض الكل' : ($isArabic ? 'عرض الكل' : 'View all') }}</a></div><div class="dashboard-list">@forelse($dashboard['sales']['recent'] as $sale)<a href="{{ route('sales.show',$sale) }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate text-sm" dir="ltr">{{ $sale->document_number }}</strong><small class="text-text-muted">{{ $sale->store?->code }} · {{ $sale->cashier?->name }}</small></span><strong dir="ltr">{{ number_format((float)$sale->payable_total,2) }}</strong></a>@empty<div class="dashboard-empty"><flux:icon.receipt-percent class="size-6" /><p>{{ app()->isLocale('ar-EG') ? 'مفيش مبيعات معتمدة بعد.' : ($isArabic ? 'لا توجد مبيعات معتمدة بعد.' : 'No approved sales yet.') }}</p></div>@endforelse</div></section>@endif
        @if($dashboard['purchases'])<section class="dashboard-panel"><div class="dashboard-panel__header"><div><h2 class="font-bold">{{ $isArabic ? 'أحدث المشتريات' : 'Recent purchases' }}</h2><p class="text-xs text-text-muted">{{ $isArabic ? 'آخر فواتير الموردين' : 'Latest supplier invoices' }}</p></div><a href="{{ route('purchasing.invoices') }}" class="text-xs font-semibold text-primary">{{ app()->isLocale('ar-EG') ? 'عرض الكل' : ($isArabic ? 'عرض الكل' : 'View all') }}</a></div><div class="dashboard-list">@forelse($dashboard['purchases']['recent'] as $invoice)<a href="{{ route('purchasing.invoices') }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate text-sm" dir="ltr">{{ $invoice->invoice_number }}</strong><small class="text-text-muted">{{ $isArabic ? $invoice->supplier?->name_ar : $invoice->supplier?->name_en }}</small></span><strong dir="ltr">{{ number_format((float)$invoice->total_amount,2) }}</strong></a>@empty<div class="dashboard-empty"><flux:icon.truck class="size-6" /><p>{{ app()->isLocale('ar-EG') ? 'مفيش فواتير مشتريات بعد.' : ($isArabic ? 'لا توجد فواتير مشتريات بعد.' : 'No purchase invoices yet.') }}</p></div>@endforelse</div></section>@endif
        @can('inventory_stock_card.view')<section class="dashboard-panel"><div class="dashboard-panel__header"><div><h2 class="font-bold">{{ $isArabic ? 'أحدث حركات المخزون' : 'Recent stock movements' }}</h2><p class="text-xs text-text-muted">{{ $isArabic ? 'الحركات المرحلة ضمن نطاقك' : 'Posted movements in your scope' }}</p></div><a href="{{ route('inventory.movements') }}" class="text-xs font-semibold text-primary">{{ $isArabic ? 'دفتر الحركة' : 'Movement ledger' }}</a></div><div class="dashboard-list">@forelse($dashboard['recent_movements'] as $movement)<a href="{{ route('inventory.movements') }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate text-sm">{{ $isArabic ? $movement->product?->name_ar : $movement->product?->name_en }}</strong><small class="text-text-muted" dir="ltr">{{ $movement->store?->code }} · {{ $movement->posted_at?->format('Y-m-d H:i') }}</small></span><span class="text-end"><small class="block text-text-muted">{{ \App\Modules\Inventory\Support\InventoryMovementLabel::label($movement->movement_type) }}</small><strong class="{{ (float)$movement->quantity < 0 ? 'text-rose-700' : 'text-emerald-700' }}" dir="ltr"><x-product-quantity :value="$movement->quantity" /></strong></span></a>@empty<div class="dashboard-empty"><flux:icon.archive-box class="size-6" /><p>{{ app()->isLocale('ar-EG') ? 'مفيش حركات مخزون ضمن النطاق.' : ($isArabic ? 'لا توجد حركات مخزون ضمن النطاق.' : 'No stock movements exist in this scope.') }}</p></div>@endforelse</div></section>@endcan
    </div>

    <div class="grid gap-4 xl:grid-cols-12">
        @can('inventory_stock_card.view')<section class="dashboard-panel xl:col-span-7"><div class="dashboard-panel__header"><div><h2 class="font-bold">{{ $isArabic ? 'أصناف منخفضة المخزون' : 'Low-stock products' }}</h2><p class="text-xs text-text-muted">{{ $isArabic ? 'رصيد متاح من وحدة إلى خمس وحدات' : 'Available balance from one to five units' }}</p></div><a href="{{ route('inventory.balances') }}" class="text-xs font-semibold text-primary">{{ $isArabic ? 'مراجعة الأرصدة' : 'Review balances' }}</a></div><div class="dashboard-list">@forelse($dashboard['low_stock'] as $balance)<a href="{{ route('inventory.balances') }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate text-sm">{{ $isArabic ? $balance->product?->name_ar : $balance->product?->name_en }}</strong><small class="text-text-muted" dir="ltr">{{ $balance->product?->item_code }} · {{ $balance->store?->code }}</small></span><span class="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800" dir="ltr"><x-product-quantity :value="bcsub((string)$balance->on_hand,(string)$balance->reserved,6)" /></span></a>@empty<div class="dashboard-empty"><flux:icon.check-circle class="size-6 text-emerald-600" /><p>{{ app()->isLocale('ar-EG') ? 'مفيش تنبيهات مخزون منخفض حالياً.' : ($isArabic ? 'لا توجد تنبيهات مخزون منخفض حالياً.' : 'No low-stock exceptions right now.') }}</p></div>@endforelse</div></section>@endcan
        @can('company_settings.edit')<section class="dashboard-panel xl:col-span-5"><div class="dashboard-panel__header"><div><h2 class="font-bold">{{ $isArabic ? 'جاهزية النظام' : 'System readiness' }}</h2><p class="text-xs text-text-muted">{{ $isArabic ? 'ملخص إداري منخفض الأولوية' : 'Low-priority administrator summary' }}</p></div><span class="text-sm font-bold text-primary" dir="ltr">{{ $setupPercent }}%</span></div><div class="p-4"><div class="h-2 overflow-hidden rounded-full bg-surface-muted"><div class="h-full rounded-full bg-primary" style="width:{{ $setupPercent }}%"></div></div><p class="mt-3 text-sm text-text-muted"><span dir="ltr">{{ $setup['completed_count']??0 }}/{{ $setup['required_count']??0 }}</span> {{ $isArabic ? 'خطوات أساسية مكتملة' : 'required steps completed' }}</p><a href="{{ route('initial-setup') }}" class="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-primary">{{ $isArabic ? 'فتح قائمة الإعداد' : 'Open setup checklist' }}</a></div></section>@endcan
    </div>
</x-app.page>
</x-layouts::app>
