@php($isArabic = str_starts_with(app()->getLocale(), 'ar'))
<div class="mb-4 flex flex-wrap items-center gap-2" aria-label="{{ __('Date presets') }}">
    <span class="me-1 text-xs font-semibold text-text-muted">{{ __('Date presets') }}</span>
    <flux:button size="sm" variant="subtle" href="{{ $action }}?date_from={{ now('Africa/Cairo')->toDateString() }}&date_to={{ now('Africa/Cairo')->toDateString() }}">{{ __('Today') }}</flux:button>
    <flux:button size="sm" variant="subtle" href="{{ $action }}?date_from={{ now('Africa/Cairo')->subDays(6)->toDateString() }}&date_to={{ now('Africa/Cairo')->toDateString() }}">{{ __('Last 7 days') }}</flux:button>
    <flux:button size="sm" variant="subtle" href="{{ $action }}?date_from={{ now('Africa/Cairo')->startOfMonth()->toDateString() }}&date_to={{ now('Africa/Cairo')->toDateString() }}">{{ __('This Month') }}</flux:button>
</div>
<form method="GET" action="{{ $action }}" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
    <flux:input type="date" name="date_from" :label="__('From Date')" :value="$report['filters']['date_from']" required />
    <flux:input type="date" name="date_to" :label="__('To Date')" :value="$report['filters']['date_to']" required />
    @if($stores->count() > 1)<flux:select name="store_id" :label="__('Store')"><option value="">{{ __('All stores') }}</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected((string)$report['filters']['store_id']===(string)$store->id)>{{ $isArabic ? ($store->name_ar ?: $store->name_en) : ($store->name_en ?: $store->name_ar) }}</option>@endforeach</flux:select>@endif
    <flux:select name="user_id" :label="__('Cashier')"><option value="">{{ __('All cashiers') }}</option>@foreach($users as $cashier)<option value="{{ $cashier->id }}" @selected((string)$report['filters']['user_id']===(string)$cashier->id)>{{ $cashier->name }}</option>@endforeach</flux:select>
    @if($showCustomer ?? false)<flux:select name="customer_id" :label="__('Customer')"><option value="">{{ __('All customers') }}</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)$report['filters']['customer_id']===(string)$customer->id)>{{ $isArabic ? ($customer->name_ar ?: $customer->name_en) : ($customer->name_en ?: $customer->name_ar) }}</option>@endforeach</flux:select>@endif
    <flux:select name="customer_group_id" :label="__('Customer Group')"><option value="">{{ __('All customer groups') }}</option>@foreach($customerGroups as $group)<option value="{{ $group->id }}" @selected((string)$report['filters']['customer_group_id']===(string)$group->id)>{{ $isArabic ? ($group->name_ar ?: $group->name_en) : ($group->name_en ?: $group->name_ar) }}</option>@endforeach</flux:select>
    @if($showPayment ?? false)<flux:select name="payment_method_id" :label="__('Payment Type')"><option value="">{{ __('All payment types') }}</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}" @selected((string)$report['filters']['payment_method_id']===(string)$method->id)>{{ $method->code }} · {{ $isArabic ? ($method->name_ar ?: $method->name_en) : ($method->name_en ?: $method->name_ar) }}</option>@endforeach</flux:select>@endif
    @if($showProduct ?? false)
        <flux:select name="product_id" :label="__('Product')"><option value="">{{ __('All products') }}</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((string)$report['filters']['product_id']===(string)$product->id)>{{ $product->item_code }} · {{ $isArabic ? ($product->name_ar ?: $product->name_en) : ($product->name_en ?: $product->name_ar) }}</option>@endforeach</flux:select>
        <flux:select name="category_id" :label="__('Category')"><option value="">{{ __('All categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)$report['filters']['category_id']===(string)$category->id)>{{ $isArabic ? ($category->name_ar ?: $category->name_en) : ($category->name_en ?: $category->name_ar) }}</option>@endforeach</flux:select>
        <flux:select name="product_unit_id" :label="__('Selling Unit')"><option value="">{{ __('All selling units') }}</option>@foreach($productUnits as $option)<option value="{{ $option->id }}" @selected((string)$report['filters']['product_unit_id']===(string)$option->id)>{{ $option->product?->item_code }} · {{ $isArabic ? ($option->unit?->name_ar ?: $option->unit?->name_en) : ($option->unit?->name_en ?: $option->unit?->name_ar) }}</option>@endforeach</flux:select>
    @endif
    <div class="flex flex-wrap items-end gap-2 sm:col-span-2 xl:col-span-full"><flux:button type="submit" variant="primary" icon="funnel">{{ __('Apply filters') }}</flux:button><flux:button href="{{ $action }}" variant="subtle" icon="arrow-path">{{ __('Reset') }}</flux:button><flux:badge class="ms-auto" color="emerald" icon="check-circle">{{ __('Approved sales only') }}</flux:badge></div>
</form>
