@php
    $isArabic = str_starts_with(app()->getLocale(), 'ar');
    $t = fn(string $ar, string $en) => $isArabic ? $ar : $en;
    $qty = fn($value) => \App\Support\ProductQuantity::format($value);
    $money = fn($value) => number_format((float)$value, 2).' '.__('EGP');
@endphp
<x-layouts::app :title="$t('تقييم المخزون في تاريخ', 'Inventory Valuation As Of Date')">
<div class="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6">
    <header class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div class="max-w-3xl"><p class="text-xs font-semibold text-primary">{{ $t('تقارير المخزون', 'Inventory reports') }}</p><flux:heading level="1" size="xl">{{ $t('تقييم المخزون في تاريخ', 'Inventory Valuation As Of Date') }}</flux:heading><flux:text class="mt-1">{{ $t('الكمية والقيمة التاريخية في نهاية اليوم المختار، من الحركات المرحلة وتكلفتها وقت الترحيل.', 'Historical quantity and value at the selected day end, from posted movements and their posting-time cost.') }}</flux:text></div>
        <form method="POST" action="{{ route('reports.export') }}" class="flex flex-wrap gap-2">@csrf<input type="hidden" name="dataset" value="inventory_valuation">@foreach($report['filters'] as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach @can('dashboard_reports.export_xlsx')<flux:button type="submit" name="format" value="csv" variant="subtle">CSV</flux:button><flux:button type="submit" name="format" value="xlsx" variant="subtle">XLSX</flux:button>@endcan @can('dashboard_reports.export_pdf')<flux:button type="submit" name="format" value="pdf" variant="primary">PDF</flux:button>@endcan</form>
    </header>
    <nav class="flex flex-wrap gap-2" aria-label="{{ $t('تقارير المخزون', 'Inventory reports') }}"><flux:button href="{{ route('reports.stock-movement') }}" variant="subtle">{{ $t('كارت حركة الصنف', 'Stock Movement Card') }}</flux:button><flux:button href="{{ route('reports.inventory-valuation') }}" variant="primary">{{ $t('تقييم المخزون', 'Inventory Valuation') }}</flux:button></nav>
    @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle"><ul class="list-disc ps-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></flux:callout>@endif
    <section class="overflow-hidden rounded-2xl border border-border bg-surface shadow-card"><header class="border-b border-border bg-surface-muted/40 px-4 py-3"><h2 class="font-semibold">{{ $t('نطاق التقييم', 'Valuation scope') }}</h2><p class="mt-1 text-sm text-text-muted">{{ $t('التاريخ يعني نهاية اليوم بتوقيت القاهرة. اختيار المخزن إلزامي.', 'The date means Cairo day end. Store selection is required.') }}</p></header><form method="GET" action="{{ route('reports.inventory-valuation') }}" class="grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-5">
        <flux:input type="date" name="as_of_date" :label="$t('التقييم في نهاية يوم', 'As of day end')" value="{{ $report['filters']['as_of_date'] }}" required />
        <flux:select name="store_id" :label="$t('المخزن', 'Store')" required>@foreach($stores as $store)<option value="{{ $store->id }}" @selected($report['store']->id===$store->id)>{{ $store->code }} · {{ $isArabic ? $store->name_ar : $store->name_en }}</option>@endforeach</flux:select>
        <flux:select name="product_id" :label="$t('الصنف (اختياري)', 'Product (optional)')"><option value="">{{ $t('كل الأصناف', 'All products') }}</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((int)request('product_id')===$product->id)>{{ $product->item_code }} · {{ $isArabic ? $product->name_ar : $product->name_en }}</option>@endforeach</flux:select>
        <flux:select name="category_id" :label="$t('التصنيف (اختياري)', 'Category (optional)')"><option value="">{{ $t('كل التصنيفات', 'All categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)request('category_id')===$category->id)>{{ $category->code }} · {{ $isArabic ? $category->name_ar : $category->name_en }}</option>@endforeach</flux:select>
        <div class="flex items-end"><flux:button type="submit" variant="primary" icon="calculator" class="w-full">{{ $t('احسب التقييم', 'Calculate valuation') }}</flux:button></div>
    </form></section>
    @if($report['today_reconciliation_difference'] !== null && bccomp($report['today_reconciliation_difference'],'0',6)!==0)<flux:callout variant="warning" icon="exclamation-triangle">{{ $t('يوجد فرق يحتاج مراجعة بين دفتر الحركات والرصيد الحالي:', 'A difference needs review between the movement ledger and current balance:') }} <bdi>{{ $qty($report['today_reconciliation_difference']) }}</bdi></flux:callout>@endif
    <section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><x-reports.kpi :label="$t('إجمالي قيمة المخزون', 'Total inventory value')" :value="$money($report['summary']['total_value'])" :description="$t('مجموع قيم الحركات حتى التاريخ', 'Sum of movement values through cutoff')" icon="banknotes" tone="primary" /><x-reports.kpi :label="$t('أصناف لها رصيد', 'Products with stock')" :value="number_format($report['summary']['positive_products'])" :description="$t('رصيد موجب', 'Positive balance')" icon="archive-box" tone="success" /><x-reports.kpi :label="$t('إجمالي الأصناف', 'Total products')" :value="number_format($report['summary']['total_products'])" :description="$t('لها حركة حتى التاريخ', 'With movement through cutoff')" icon="cube" tone="info" /><x-reports.kpi :label="$t('رصيد صفر', 'Zero balance')" :value="number_format($report['summary']['zero_products'])" :description="$t('لا قيمة كمية حالية', 'No quantity balance')" icon="minus-circle" tone="warning" /><x-reports.kpi :label="$t('رصيد سالب', 'Negative balance')" :value="number_format($report['summary']['negative_products'])" :description="$t('استثناء يحتاج مراجعة', 'Exception requiring review')" icon="exclamation-triangle" tone="danger" /></section>
    <section class="overflow-hidden rounded-2xl border border-border bg-surface shadow-card"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><div><h2 class="font-semibold">{{ $t('قيمة المخزون التاريخية', 'Historical inventory value') }}</h2><p class="mt-1 text-sm text-text-muted">{{ $t('القيمة لا تستخدم متوسط تكلفة اليوم؛ هي مجموع قيمة الحركات التاريخية.', 'Value never uses today’s average cost; it sums historical movement value.') }}</p></div><strong>{{ $money($report['summary']['total_value']) }}</strong></header>
        <div class="overflow-x-auto"><table class="data-table min-w-[980px] w-full"><thead><tr><th>{{ $t('الصنف', 'Product') }}</th><th>{{ $t('الكود', 'Code') }}</th><th>{{ $t('التصنيف', 'Category') }}</th><th>{{ $t('الوحدة الأساسية', 'Base unit') }}</th><th class="text-end">{{ $t('الكمية في التاريخ', 'Quantity as of') }}</th><th class="text-end">{{ $t('تكلفة الوحدة في التاريخ', 'Unit cost as of') }}</th><th class="text-end">{{ $t('قيمة المخزون في التاريخ', 'Value as of') }}</th><th>{{ $t('آخر حركة', 'Last movement') }}</th><th>{{ $t('الحركة', 'Movement') }}</th></tr></thead><tbody>
        @forelse($report['rows'] as $row)<tr class="{{ bccomp((string)$row->quantity_as_of,'0',6)<0 ? 'bg-rose-50/60 dark:bg-rose-950/20' : '' }}"><td class="font-semibold">{{ $isArabic ? $row->name_ar : $row->name_en }}</td><td class="font-mono" dir="ltr">{{ $row->item_code }}</td><td>{{ $isArabic ? $row->category_ar : $row->category_en }}</td><td>{{ $row->base_unit ?: '—' }}</td><td class="text-end font-semibold" dir="ltr">{{ $qty($row->quantity_as_of) }}</td><td class="text-end" dir="ltr">{{ $row->unit_cost_as_of===null?'—':$money($row->unit_cost_as_of) }}</td><td class="text-end font-bold" dir="ltr">{{ $money($row->value_as_of) }}</td><td class="whitespace-nowrap" dir="ltr">{{ \Carbon\CarbonImmutable::parse($row->last_movement_at,'UTC')->setTimezone('Africa/Cairo')->format('Y-m-d H:i') }}</td><td><flux:button size="sm" href="{{ route('reports.stock-movement',['product_id'=>$row->product_id,'store_id'=>$report['store']->id,'date_to'=>$report['filters']['as_of_date']]) }}">{{ $t('كارت الصنف', 'Stock card') }}</flux:button></td></tr>
        @empty<tr><td colspan="9"><x-state.empty :title="$t('لا يوجد مخزون في النطاق المحدد في هذا التاريخ', 'No inventory exists in the selected scope at this date')" /></td></tr>@endforelse
        </tbody></table></div>@if($report['rows'] instanceof \Illuminate\Pagination\LengthAwarePaginator && $report['rows']->hasPages())<div class="border-t border-border p-4">{{ $report['rows']->links() }}</div>@endif
    </section>
</div>
</x-layouts::app>
