@php
    $isArabic = str_starts_with(app()->getLocale(), 'ar');
    $money = fn($value) => number_format((float)$value, 2).' '.__('EGP');
    $displayQuantity = static function ($value, ?string $unit = null): string {
        $value = (string) ($value ?? '0');
        if (strtoupper(trim((string) $unit)) === 'KG' && (bccomp($value, '1000', 13) >= 0 || bccomp($value, '-1000', 13) <= 0)) {
            $value = bcdiv($value, '1000', 13);
            $unit = 'TON';
        }
        $parts = explode('.', $value);
        $whole = preg_replace('/\B(?=(\d{3})+(?!\d))/', ',', $parts[0]);
        $fraction = rtrim($parts[1] ?? '', '0');
        return $whole.($fraction === '' ? '' : '.'.$fraction).($unit ? ' '.$unit : '');
    };
@endphp
<x-layouts::app :title="__('Sales by Product')"><div class="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6">
    <header class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div class="max-w-3xl"><p class="text-xs font-semibold uppercase tracking-wide text-primary">{{ __('Sales Reports') }}</p><flux:heading level="1" size="xl">{{ __('Sales by Product') }}</flux:heading><flux:text class="mt-1">{{ __('Product and selling unit remain separate so BAG, KG, and TON quantities are never mixed.') }}</flux:text></div><form method="POST" action="{{ route('reports.export') }}" class="flex flex-wrap gap-2">@csrf<input type="hidden" name="dataset" value="sales_by_product">@foreach($report['filters'] as $key=>$value)@if(is_scalar($value)&&filled($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach @can('dashboard_reports.export_xlsx')<flux:button type="submit" name="format" value="csv" variant="subtle" icon="document-arrow-down" :aria-label="__('Create :format export', ['format' => 'CSV'])">CSV</flux:button><flux:button type="submit" name="format" value="xlsx" variant="subtle" icon="table-cells" :aria-label="__('Create :format export', ['format' => 'Excel'])">XLSX</flux:button>@endcan @can('dashboard_reports.export_pdf')<flux:button type="submit" name="format" value="pdf" variant="primary" icon="document-arrow-down" :aria-label="__('Create :format export', ['format' => 'PDF'])">PDF</flux:button>@endcan</form></header>
    @include('pages.reports._navigation', ['active' => 'product'])
    @if(session('success'))<flux:callout variant="success" icon="check-circle">{{ session('success') }}</flux:callout>@endif
    @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle"><ul class="list-disc ps-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></flux:callout>@endif
    <section class="overflow-hidden rounded-2xl border border-border bg-surface shadow-card" aria-labelledby="sales-product-filters"><header class="border-b border-border bg-surface-muted/40 px-4 py-3"><h2 id="sales-product-filters" class="font-semibold text-text-primary">{{ __('Report scope') }}</h2><p class="mt-1 text-sm text-text-muted">{{ __('Choose the period, product, category, or selling unit. Every row keeps its historical unit.') }}</p></header><div class="p-4">@include('pages.reports._sales-filters',['action'=>route('reports.sales-by-product'),'showCustomer'=>false,'showPayment'=>false,'showProduct'=>true])</div></section>
    <section id="product-summary" class="scroll-mt-24 rounded-2xl border border-border bg-surface shadow-card"><header class="border-b border-border p-4"><flux:heading size="lg">{{ __('Product + Selling Unit') }}</flux:heading><flux:text>{{ __('All amounts use historical sale-line and completed-return snapshots. Profit and COGS are intentionally excluded from R1.') }}</flux:text><p class="mt-2 text-sm text-text-muted">{{ $isArabic ? 'الكميات بالكيلو تُعرض بالطن من 1,000 كيلو (الطن = 1,000 كيلو). سعر الوحدة يظل لكل وحدة بيع أصلية؛ التحويل للعرض فقط.' : 'KG quantities display as TON from 1,000 KG (1 TON = 1,000 KG). Unit prices remain per original selling unit; conversion is display-only.' }}</p></header><div class="responsive-resource-table"><table class="data-table data-table--mobile-summary w-full"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('SKU') }}</th><th>{{ __('Category') }}</th><th>{{ __('Selling Unit') }}</th><th>{{ __('Gross Quantity Sold') }}</th><th>{{ __('Returned Quantity') }}</th><th>{{ __('Net Quantity') }}</th><th>{{ __('Gross Sales') }}</th><th>{{ __('Discount') }}</th><th>{{ __('Returns Value') }}</th><th>{{ __('Net Sales') }}</th><th>{{ __('Average Selling Price') }}</th><th>{{ __('Invoice Count') }}</th><th>{{ __('View') }}</th></tr></thead><tbody>@forelse($report['products'] as $row)<tr><td>{{ $isArabic?$row['name_ar']:$row['name_en'] }}</td><td dir="ltr">{{ $row['item_code'] }}</td><td>{{ $isArabic?$row['category_name_ar']:$row['category_name_en'] }}</td><td><flux:badge>{{ $row['unit_code'] }}</flux:badge></td><td dir="ltr">{{ $displayQuantity($row['sold_quantity'], $row['unit_code']) }}</td><td dir="ltr">{{ $displayQuantity($row['returned_quantity'], $row['unit_code']) }}</td><td dir="ltr">{{ $displayQuantity($row['net_quantity'], $row['unit_code']) }}</td><td dir="ltr">{{ $money($row['gross_sales']) }}</td><td dir="ltr">{{ $money($row['discount']) }}</td><td dir="ltr">{{ $money($row['returns_value']) }}</td><td dir="ltr">{{ $money($row['net_sales']) }}</td><td dir="ltr">{{ $money($row['average_price']) }}</td><td>{{ $row['invoice_count'] }}</td><td><flux:button size="sm" aria-controls="product-detail" href="{{ route('reports.sales-by-product',array_merge(request()->except(['detail_page']),['detail_product_id'=>$row['product_id'],'detail_product_unit_id'=>$row['product_unit_id']??'legacy'])).'#product-detail' }}">{{ __('Details') }}</flux:button></td></tr>@empty<tr><td colspan="14"><x-state.empty :title="__('No product sales in the selected period')" /></td></tr>@endforelse</tbody></table></div>@if($report['products']->hasPages())<div class="border-t border-border p-4">{{ $report['products']->links() }}</div>@endif</section>
    @if($report['detail'])<section id="product-detail" tabindex="-1" class="scroll-mt-24 rounded-2xl border border-primary/30 bg-surface shadow-card"><header class="border-b border-border p-4"><flux:heading size="lg">{{ __('Product Sale Lines') }}</flux:heading><a class="mt-2 inline-flex text-sm font-semibold text-primary hover:underline" href="{{ route('reports.sales-by-product', request()->except(['detail_product_id', 'detail_product_unit_id', 'detail_page'])).'#product-summary' }}">{{ $isArabic ? 'الرجوع إلى ملخص الأصناف' : 'Back to product summary' }}</a><flux:text>{{ __('Historical price and quantity snapshots for the selected product and selling unit.') }}</flux:text><p class="mt-2 text-sm text-text-muted">{{ $isArabic ? 'الكميات بالكيلو تُعرض بالطن من 1,000 كيلو (الطن = 1,000 كيلو). سعر الوحدة يظل لكل وحدة بيع أصلية؛ التحويل للعرض فقط.' : 'KG quantities display as TON from 1,000 KG (1 TON = 1,000 KG). Unit prices remain per original selling unit; conversion is display-only.' }}</p></header><div class="responsive-resource-table"><table class="data-table w-full"><thead><tr><th>{{ __('Invoice') }}</th><th>{{ __('Date') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Customer Group') }}</th><th>{{ __('Unit') }}</th><th>{{ __('Quantity') }}</th><th>{{ __('Historical Unit Price') }}</th><th>{{ __('Discount') }}</th><th>{{ __('Net Line Amount') }}</th><th>{{ __('Returned Quantity') }}</th><th>{{ __('Returned Value') }}</th></tr></thead><tbody>@forelse($report['detail'] as $line)<tr><td><a class="font-semibold text-primary hover:underline" href="{{ route('sales.show',$line->sale_id) }}">{{ $line->document_number }}</a></td><td>{{ \Carbon\CarbonImmutable::parse($line->approved_at,'UTC')->setTimezone('Africa/Cairo')->format('Y-m-d H:i') }}</td><td>{{ $isArabic?$line->customer_name_ar:$line->customer_name_en }}</td><td>{{ $isArabic?$line->group_name_ar:$line->group_name_en }}</td><td>{{ $line->unit_code ?: __('Legacy') }}</td><td dir="ltr">{{ $displayQuantity($line->entered_quantity ?? $line->quantity, $line->unit_code) }}</td><td dir="ltr">{{ $money($line->entered_unit_price ?? $line->unit_price) }}</td><td dir="ltr">{{ $money(bcadd((string)$line->discount_amount,(string)$line->allocated_invoice_discount,2)) }}</td><td dir="ltr">{{ $money($line->net_amount) }}</td><td dir="ltr">{{ $displayQuantity($line->returned_quantity, $line->unit_code) }}</td><td dir="ltr">{{ $money($line->returned_value) }}</td></tr>@empty<tr><td colspan="11"><x-state.empty :title="__('No qualifying sale lines')" /></td></tr>@endforelse</tbody></table></div>@if($report['detail']->hasPages())<div class="border-t border-border p-4">{{ $report['detail']->links() }}</div>@endif</section>@endif
</div></x-layouts::app>
