@php
    $isArabic = str_starts_with(app()->getLocale(), 'ar');
    $money = fn($value) => number_format((float)$value, 2).' '.__('EGP');
    $visual = ['key'=>'sales-summary-trend','title'=>__('Sales Trend'),'description'=>__('Approved sales less completed returns by Cairo business day.'),'type'=>'line','unit'=>'money','labels'=>$report['trend']->pluck('date')->all(),'series'=>[['label'=>__('Sales'),'data'=>$report['trend']->pluck('sales')->all()],['label'=>__('Returns'),'data'=>$report['trend']->pluck('returns')->all()],['label'=>__('Net Sales'),'data'=>$report['trend']->pluck('net')->all()]]];
@endphp
<x-layouts::app :title="__('Sales Summary')">
<div class="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6">
    <header class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div class="max-w-3xl"><p class="text-xs font-semibold uppercase tracking-wide text-primary">{{ __('Sales Reports') }}</p><flux:heading level="1" size="xl">{{ __('Sales Summary') }}</flux:heading><flux:text class="mt-1">{{ __('Approved sales, completed returns, checkout collections, and credit created in one reconciled view.') }}</flux:text></div>
        <form method="POST" action="{{ route('reports.export') }}" class="flex flex-wrap gap-2">@csrf<input type="hidden" name="dataset" value="sales_summary">@foreach($report['filters'] as $key=>$value)@if(is_scalar($value)&&filled($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach
            @can('dashboard_reports.export_xlsx')<flux:button type="submit" name="format" value="csv" variant="subtle" icon="document-arrow-down" :aria-label="__('Create :format export', ['format' => 'CSV'])">CSV</flux:button><flux:button type="submit" name="format" value="xlsx" variant="subtle" icon="table-cells" :aria-label="__('Create :format export', ['format' => 'Excel'])">XLSX</flux:button>@endcan @can('dashboard_reports.export_pdf')<flux:button type="submit" name="format" value="pdf" variant="primary" icon="document-arrow-down" :aria-label="__('Create :format export', ['format' => 'PDF'])">PDF</flux:button>@endcan
        </form></header>
    @include('pages.reports._navigation', ['active' => 'summary'])
    @if(session('success'))<flux:callout variant="success" icon="check-circle">{{ session('success') }}</flux:callout>@endif
    @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle"><ul class="list-disc ps-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></flux:callout>@endif
    <section class="overflow-hidden rounded-2xl border border-border bg-surface shadow-card" aria-labelledby="sales-summary-filters"><header class="border-b border-border bg-surface-muted/40 px-4 py-3"><h2 id="sales-summary-filters" class="font-semibold text-text-primary">{{ __('Report scope') }}</h2><p class="mt-1 text-sm text-text-muted">{{ __('Choose the period and optional filters. Every section and export uses the same scope.') }}</p></header><div class="p-4">@include('pages.reports._sales-filters',['action'=>route('reports.sales-summary'),'showCustomer'=>true,'showPayment'=>true,'showProduct'=>false])</div></section>
    <section><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <x-reports.kpi :label="__('Gross Sales')" :value="$money($report['metrics']['gross_sales'])" :description="__('Approved subtotal after authoritative discounts, before returns.')" icon="banknotes" tone="info" />
        <x-reports.kpi :label="__('Returns')" :value="$money($report['metrics']['returns'])" :description="__('Completed return eligible value, counted once.')" icon="receipt-refund" tone="danger" />
        <x-reports.kpi :label="__('Net Sales')" :value="$money($report['metrics']['net_sales'])" :description="__('Gross sales less completed returns.')" icon="arrow-trending-up" tone="success" />
        <x-reports.kpi :label="__('Collected at Sale')" :value="$money($report['metrics']['collected_at_sale'])" :description="__('Captured checkout payments only; later receipts are excluded.')" icon="credit-card" tone="success" />
        <x-reports.kpi :label="__('Credit Created')" :value="$money($report['metrics']['credit_created'])" :description="__('Sale payable value not captured at checkout.')" icon="scale" tone="warning" />
        <x-reports.kpi :label="__('Invoice Count')" :value="number_format($report['metrics']['invoice_count'])" :description="__('Distinct approved invoices.')" icon="document-check" tone="primary" />
        <x-reports.kpi :label="__('Average Invoice')" :value="$money($report['metrics']['average_invoice'])" :description="__('Net sales divided by qualifying invoice count.')" icon="calculator" tone="info" />
        <x-reports.kpi :label="__('Discounts')" :value="$money($report['metrics']['discounts'])" :description="__('Authoritative line and invoice discounts.')" icon="receipt-percent" tone="warning" />
    </div></section>
    <section class="rounded-2xl border border-border bg-surface p-4 shadow-card"><div class="mb-4"><flux:heading size="lg">{{ __('Previous Equivalent Period') }}</flux:heading><flux:text>{{ __('Net Sales, invoice count, and average invoice use the immediately preceding range of equal length.') }}</flux:text></div><div class="grid gap-3 sm:grid-cols-3">@foreach(['net_sales'=>__('Net Sales'),'invoice_count'=>__('Invoice Count'),'average_invoice'=>__('Average Invoice')] as $key=>$label)<div class="rounded-xl bg-surface-muted p-4"><p class="text-xs text-text-muted">{{ $label }}</p><p class="mt-1 text-xl font-bold tabular-nums" dir="ltr">{{ $key==='invoice_count'?number_format($report['previous'][$key]):$money($report['previous'][$key]) }}</p><p class="mt-1 text-xs text-text-muted">{{ $report['comparison'][$key]['percent']===null?__('No comparable base'):number_format($report['comparison'][$key]['percent'],1).'%' }}</p></div>@endforeach</div></section>
    <x-reports.visual :$visual />
    <div class="grid gap-5 lg:grid-cols-2">
        <section class="rounded-2xl border border-border bg-surface shadow-card"><header class="border-b border-border p-4"><flux:heading size="lg">{{ __('Payment Breakdown') }}</flux:heading></header><div class="responsive-resource-table"><table class="data-table w-full"><thead><tr><th>{{ __('Payment Type') }}</th><th class="text-end">{{ __('Amount') }}</th></tr></thead><tbody>@forelse($report['payments'] as $row)<tr><td>{{ $isArabic?$row->name_ar:$row->name_en }}</td><td class="text-end tabular-nums" dir="ltr">{{ $money($row->amount) }}</td></tr>@empty<tr><td colspan="2"><x-state.empty :title="__('No checkout payments in this period')" /></td></tr>@endforelse</tbody></table></div></section>
        <section class="rounded-2xl border border-border bg-surface shadow-card"><header class="border-b border-border p-4"><flux:heading size="lg">{{ __('Sales by Cashier') }}</flux:heading></header><div class="responsive-resource-table"><table class="data-table w-full"><thead><tr><th>{{ __('Cashier') }}</th><th>{{ __('Invoice Count') }}</th><th class="text-end">{{ __('Net Sales') }}</th><th class="text-end">{{ __('Amount Collected') }}</th></tr></thead><tbody>@forelse($report['cashiers'] as $row)<tr><td>{{ $row['cashier'] }}</td><td>{{ $row['invoice_count'] }}</td><td class="text-end tabular-nums" dir="ltr">{{ $money($row['net_sales']) }}</td><td class="text-end tabular-nums" dir="ltr">{{ $money($row['collected']) }}</td></tr>@empty<tr><td colspan="4"><x-state.empty :title="__('No sales in this period')" /></td></tr>@endforelse</tbody></table></div></section>
    </div>
    <section class="rounded-2xl border border-border bg-surface shadow-card"><header class="border-b border-border p-4"><flux:heading size="lg">{{ __('Invoice Drill-down') }}</flux:heading></header><div class="responsive-resource-table"><table class="data-table data-table--mobile-summary w-full"><thead><tr><th>{{ __('Invoice') }}</th><th>{{ __('Date / Time') }}</th><th>{{ __('Customer') }}</th><th>{{ __('Customer Group') }}</th><th>{{ __('Cashier') }}</th><th>{{ __('Gross') }}</th><th>{{ __('Discount') }}</th><th>{{ __('Net') }}</th><th>{{ __('Paid') }}</th><th>{{ __('Outstanding') }}</th><th>{{ __('Payment Status') }}</th><th>{{ __('Sale Status') }}</th><th>{{ __('View') }}</th></tr></thead><tbody>@forelse($report['invoices'] as $sale)<tr><td>{{ $sale->document_number }}</td><td>{{ \Carbon\CarbonImmutable::parse($sale->approved_at,'UTC')->setTimezone('Africa/Cairo')->format('Y-m-d H:i') }}</td><td>{{ $isArabic?$sale->customer_name_ar:$sale->customer_name_en }}</td><td>{{ $isArabic?$sale->group_name_ar:$sale->group_name_en }}</td><td>{{ $sale->cashier }}</td><td dir="ltr">{{ $money($sale->subtotal) }}</td><td dir="ltr">{{ $money($sale->discount_total) }}</td><td dir="ltr">{{ $money(bcsub((string)$sale->subtotal,(string)$sale->discount_total,2)) }}</td><td dir="ltr">{{ $money($sale->paid) }}</td><td dir="ltr">{{ $money($sale->outstanding) }}</td><td><x-status.badge :status="$sale->payment_status" /></td><td><x-status.badge :status="$sale->status" /></td><td><flux:button size="sm" href="{{ route('sales.show',$sale->id) }}">{{ __('View') }}</flux:button></td></tr>@empty<tr><td colspan="13"><x-state.empty :title="__('No approved sales in the selected period')" /></td></tr>@endforelse</tbody></table></div>@if($report['invoices']->hasPages())<div class="border-t border-border p-4">{{ $report['invoices']->links() }}</div>@endif</section>
</div>
</x-layouts::app>
