@php($currency = $store?->company?->currency_code ?? $store?->branch?->currency ?? 'EGP')
<section class="flex min-w-0 flex-col overflow-hidden rounded-xl bg-white shadow-xs ring-1 ring-zinc-200 dark:bg-zinc-900 dark:ring-zinc-800 xl:sticky xl:top-2 xl:h-[calc(100vh-5.5rem)]" aria-labelledby="pos-cart-heading">
    <header class="border-b border-zinc-100 px-3 py-2 dark:border-zinc-800">
        <div class="flex items-center gap-2" data-open-order-tabs>
            <div class="min-w-0 flex-1 overflow-x-auto"><div class="flex gap-1.5" role="tablist" aria-label="{{ __('Open customer orders') }}">@foreach($openOrders as $openOrder)@php($active = $activeOrder && $activeOrder->is($openOrder))<div class="flex shrink-0 overflow-hidden rounded-lg border {{ $active ? 'border-cyan-500 bg-cyan-50 dark:bg-cyan-950/35' : 'border-zinc-200 bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-950' }}"><form method="POST" action="{{ route('pos.orders.switch') }}">@csrf<input type="hidden" name="open_order_uuid" value="{{ $openOrder->uuid }}"><button type="submit" role="tab" aria-selected="{{ $active ? 'true' : 'false' }}" class="min-h-9 max-w-40 px-2 text-start text-xs"><strong>{{ __('Order :number', ['number' => $openOrder->sequence_number]) }}</strong><span class="ms-1 text-zinc-500">{{ $openOrder->customer ? \Illuminate\Support\Str::limit(str_starts_with(app()->getLocale(), 'ar') ? $openOrder->customer->name_ar : $openOrder->customer->name_en, 11) : '' }} · {{ $openOrder->lines_count }}</span></button></form><form method="POST" action="{{ route('pos.orders.cancel') }}" onsubmit="return window.confirm({{ \Illuminate\Support\Js::from(__('Cancel this open order? Its draft will be closed without posting a sale.')) }})">@csrf<input type="hidden" name="open_order_uuid" value="{{ $openOrder->uuid }}"><button type="submit" class="flex w-7 items-center justify-center border-s border-zinc-200 text-zinc-400 hover:bg-rose-50 hover:text-rose-600 dark:border-zinc-700" aria-label="{{ __('Cancel order :number', ['number' => $openOrder->sequence_number]) }}"><flux:icon name="x-mark" class="size-3.5" /></button></form></div>@endforeach</div></div>
            <form method="POST" action="{{ route('pos.orders.store') }}">@csrf<input type="hidden" name="creation_token" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><button type="submit" title="{{ __('New order') }}" aria-label="{{ __('New order') }}" class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-cyan-700 text-white hover:bg-cyan-800"><flux:icon name="plus" class="size-4" /></button></form>
            @if($cart->isNotEmpty())<form method="POST" action="{{ route('pos.suspend') }}">@csrf<button type="submit" title="{{ __('Hold order') }}" aria-label="{{ __('Hold order') }}" class="flex size-9 shrink-0 items-center justify-center rounded-lg border border-zinc-300 text-zinc-600 hover:bg-zinc-50 dark:border-zinc-700 dark:text-zinc-300"><flux:icon name="pause-circle" class="size-4" /></button></form>@endif
        </div>
        <div class="mt-2 flex items-center justify-between"><h2 id="pos-cart-heading" class="text-sm font-extrabold">{{ __('Cart') }} <span class="text-zinc-400">({{ $cart->count() }})</span></h2>@if($cart->isNotEmpty())<button wire:click="clear" wire:confirm="{{ __('Clear every item from this cart?') }}" class="rounded px-2 py-1 text-xs font-semibold text-rose-600 hover:bg-rose-50">{{ __('Clear cart') }}</button>@endif</div>
    </header>
    @if($errors->has('cart') || $error)<div class="px-3 pt-2"><p class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{{ $errors->first('cart') ?: $error }}</p></div>@endif
    <div wire:loading class="space-y-2 p-3"><div class="h-20 animate-pulse rounded-lg bg-zinc-100 dark:bg-zinc-800"></div><div class="h-20 animate-pulse rounded-lg bg-zinc-100 dark:bg-zinc-800"></div></div>
    <div wire:loading.remove class="min-h-0 flex-1 space-y-2 overflow-y-auto p-2.5">
        @forelse($lines as $index => $line)
            @php($product = $line['product'])
            @php($family = $product->family())
            @php($image = $product->effectiveMainImage())
            @php($computed = $preview['lines'][$index] ?? null)
            @php($up = bcadd($line['quantity'], '1', 6))
            @php($down = bcsub($line['quantity'], '1', 6))
            @php($display = \App\Support\ProductQuantity::format($line['quantity']))
            <div class="flex items-center justify-between px-1 text-[10px] font-semibold text-cyan-700"><span>{{ __($line['price']->price_label) }}</span>@if($line['price']->minimum_selling_price !== null)<span dir="ltr">{{ __('الحد الأدنى') }} {{ $line['price']->minimum_selling_price }} {{ __('ج.م') }}</span>@endif</div>
            <article class="rounded-lg bg-zinc-50 p-2 ring-1 ring-zinc-200 dark:bg-zinc-950/60 dark:ring-zinc-800" data-cart-line="{{ $product->id }}"><div class="flex gap-2">@if($image)<img src="{{ route('pos.products.thumbnail', ['product'=>$image->product_id,'attachment'=>$image->attachment_id]) }}" alt="" width="80" height="80" loading="lazy" class="size-11 shrink-0 rounded-md object-cover">@else<div class="flex size-11 shrink-0 items-center justify-center rounded-md bg-zinc-200 dark:bg-zinc-800"><flux:icon name="cube" class="size-5 text-zinc-400" /></div>@endif<div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><span class="block text-[9px] font-semibold text-zinc-500">{{ __('Product') }}</span><h3 class="truncate text-xs font-bold">{{ str_starts_with(app()->getLocale(), 'ar')?$family->name_ar:$family->name_en }}</h3><p class="truncate font-mono text-[10px] text-zinc-500">{{ $product->item_code }}@if($product->isVariant()) · {{ $product->localizedVariationLabel() }}@endif</p></div><div class="shrink-0 text-end"><span class="block text-[9px] font-semibold text-zinc-500">{{ __('Line total') }}</span><strong class="text-xs"><x-money :amount="$computed['net_amount'] ?? '0.00'" :currency="$currency" /></strong></div></div><div class="mt-1.5 flex items-end justify-between gap-2"><div>@if($product->productUnits->isNotEmpty())<select wire:change="unit({{ $product->id }}, $event.target.value)" class="mb-1 h-7 rounded-md border-zinc-300 bg-white text-[10px] dark:border-zinc-700 dark:bg-zinc-900" aria-label="{{ __('Unit') }}">@foreach($product->productUnits as $productUnit)<option value="{{ $productUnit->id }}" @selected((int)($line['cart']['product_unit_id']??0)===$productUnit->id)>{{ str_starts_with(app()->getLocale(), 'ar')?$productUnit->unit->name_ar:$productUnit->unit->name_en }}</option>@endforeach</select>@endif<span class="block text-[9px] font-semibold text-zinc-500">{{ __('Quantity') }}</span><div class="inline-grid grid-cols-[1.9rem_2.7rem_1.9rem] overflow-hidden rounded-md border border-zinc-300 bg-white dark:border-zinc-700 dark:bg-zinc-900"><button wire:click="quantity({{ $product->id }}, '{{ $down }}')" @disabled(bccomp($down,'0',6)<=0) class="h-7 disabled:opacity-30">−</button><span class="flex h-7 items-center justify-center border-x border-zinc-300 text-xs font-bold dark:border-zinc-700">{{ $display }}</span><button wire:click="quantity({{ $product->id }}, '{{ $up }}')" class="h-7">+</button></div></div><div class="text-end"><span class="block text-[9px] font-semibold text-zinc-500">{{ __('Unit price') }}</span><strong class="text-xs"><x-money :amount="$line['unit_price']" :currency="$currency" /></strong></div><button wire:click="remove({{ $product->id }})" title="{{ __('Remove') }}" aria-label="{{ __('Remove') }}" class="flex size-7 items-center justify-center rounded text-rose-600 hover:bg-rose-50"><flux:icon name="trash" class="size-3.5" /></button></div></div></div>
                @if($line['price']->open_price_allowed || auth()->user()->can('pos_sales.apply_discount'))<details class="mt-1.5 border-t border-zinc-200 pt-1.5 dark:border-zinc-800"><summary class="cursor-pointer text-[11px] font-bold text-cyan-700">{{ __('Adjust price or discount') }}</summary><div class="mt-2 grid gap-2">@can('pos_sales.apply_discount')<form method="POST" action="{{ route('pos.cart.discount') }}" class="grid grid-cols-[1fr_1fr_auto] gap-1.5">@csrf<input type="hidden" name="product_id" value="{{ $product->id }}"><input type="hidden" name="expected_revision" value="{{ (int)($line['cart']['discount_revision']??0) }}"><input type="hidden" name="discount_type" value="line"><input name="discount_amount" type="number" min="0.01" step="0.01" required class="h-8 rounded-md border-zinc-300 text-xs" placeholder="{{ __('Discount amount') }}"><input name="reason" class="h-8 rounded-md border-zinc-300 text-xs" placeholder="{{ __('Reason') }}"><button class="rounded-md bg-cyan-700 px-2 text-xs font-bold text-white">{{ __('Apply') }}</button></form>@endcan @can('pos_sales.open_price')@if($line['price']->open_price_allowed)<form method="POST" action="{{ route('pos.cart.open-price') }}" class="grid grid-cols-[1fr_1fr_auto] gap-1.5">@csrf<input type="hidden" name="product_id" value="{{ $product->id }}"><input type="hidden" name="expected_revision" value="{{ (int)($line['cart']['pricing_revision']??0) }}"><input name="amount" type="number" min="0.0001" step="0.0001" required class="h-8 rounded-md border-zinc-300 text-xs" placeholder="{{ __('Open price amount') }}"><input name="reason" required class="h-8 rounded-md border-zinc-300 text-xs" placeholder="{{ __('Required reason') }}"><button class="rounded-md bg-cyan-700 px-2 text-xs font-bold text-white">{{ __('Apply') }}</button></form>@endif@endcan</div></details>@endif
            </article>
        @empty<div class="flex min-h-36 flex-col items-center justify-center px-4 text-center"><flux:icon name="shopping-cart" class="size-7 text-zinc-300" /><p class="mt-2 text-sm font-bold">{{ __('Cart is empty') }}</p><p class="text-xs text-zinc-500">{{ __('Scan a barcode or select a product.') }}</p></div>@endforelse
    </div>
    @if($preview)<footer class="border-t border-zinc-200 bg-zinc-50 px-3 py-2 dark:border-zinc-800 dark:bg-zinc-950"><div class="flex items-center justify-between"><span class="text-xs font-semibold text-zinc-500">{{ __('Cart total') }}</span><strong class="text-lg"><x-money :amount="$preview['total']" :currency="$currency" /></strong></div></footer>@endif
</section>
