@php
    $currency = $store?->company?->currency_code ?? $store?->branch?->currency ?? 'EGP';
    $checkoutBlocker = $cart->isEmpty() ? __('Add an item to begin checkout.') : (! $context->isReady() ? $context->disabledReason : (! $preview ? (($error ?? null) ?: __('Review the cart before checkout.')) : null));
    $selectedCustomer = $order?->customer;
    $creditEligible = $selectedCustomer?->status === 'active' && in_array($selectedCustomer?->customer_type, ['credit', 'both'], true);
    $cashDraft = collect($paymentLines)->first(fn($line) => $cashMethod && (int)($line['method_id'] ?? 0) === (int)$cashMethod->id);
    $quickCash = config('pos.cash_quick_denominations', [20, 50, 100, 200, 500, 1000]);
@endphp
<section class="rounded-xl bg-white p-3 shadow-xs ring-1 ring-zinc-200 dark:bg-zinc-900 dark:ring-zinc-800" data-guide="pos-summary-actions" aria-labelledby="pos-payment-heading">
    <div class="flex items-center justify-between"><h2 id="pos-payment-heading" class="text-sm font-extrabold">{{ __('Payment') }}</h2>@can('pos_sales.apply_tax')<form method="POST" action="{{ route('pos.cart.tax') }}">@csrf<input type="hidden" name="tax_applicable" value="{{ ($taxApplicable??false)?0:1 }}"><button class="rounded px-2 py-1 text-xs font-bold text-cyan-700 hover:bg-cyan-50 dark:text-cyan-300">{{ ($taxApplicable??false)?__('Remove tax'):__('Add tax') }}</button></form>@endcan</div>
    @error('paymentLines')<p class="mt-2 rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{{ $message }}</p>@enderror

    <div class="mt-2 grid gap-1.5" role="radiogroup" aria-label="{{ __('Payment mode') }}">
        @if($cashMethod)<button type="button" wire:click="chooseMode('cash')" role="radio" aria-checked="{{ $mode==='cash'?'true':'false' }}" class="flex items-center gap-2 rounded-lg border px-2.5 py-2 text-start {{ $mode==='cash'?'border-cyan-600 bg-cyan-50 ring-1 ring-cyan-600 dark:bg-cyan-950/25':'border-zinc-200 dark:border-zinc-700' }}"><span class="size-3 rounded-full border-2 {{ $mode==='cash'?'border-cyan-700 bg-cyan-700':'border-zinc-400' }}"></span><flux:icon name="banknotes" class="size-4" /><span class="min-w-0"><strong class="block text-xs">{{ __('Cash') }}</strong><span class="block text-[10px] text-zinc-500">{{ __('Cash received, exact amount and change') }}</span></span></button>@endif
        @if($electronicMethods->isNotEmpty())<button type="button" wire:click="chooseMode('card')" role="radio" aria-checked="{{ $mode==='card'?'true':'false' }}" class="flex items-center gap-2 rounded-lg border px-2.5 py-2 text-start {{ $mode==='card'?'border-cyan-600 bg-cyan-50 ring-1 ring-cyan-600 dark:bg-cyan-950/25':'border-zinc-200 dark:border-zinc-700' }}"><span class="size-3 rounded-full border-2 {{ $mode==='card'?'border-cyan-700 bg-cyan-700':'border-zinc-400' }}"></span><flux:icon name="credit-card" class="size-4" /><span><strong class="block text-xs">{{ __('Card or electronic') }}</strong><span class="block text-[10px] text-zinc-500">{{ __('One card or multiple cards') }}</span></span></button>@endif
        @if($methods->count()>1)<button type="button" wire:click="chooseMode('split')" role="radio" aria-checked="{{ in_array($mode,['split','other'],true)?'true':'false' }}" class="flex items-center gap-2 rounded-lg border px-2.5 py-2 text-start {{ in_array($mode,['split','other'],true)?'border-cyan-600 bg-cyan-50 ring-1 ring-cyan-600 dark:bg-cyan-950/25':'border-zinc-200 dark:border-zinc-700' }}"><span class="size-3 rounded-full border-2 {{ in_array($mode,['split','other'],true)?'border-cyan-700 bg-cyan-700':'border-zinc-400' }}"></span><flux:icon name="ellipsis-horizontal" class="size-4" /><span><strong class="block text-xs">{{ __('Mixed payment / other methods') }}</strong><span class="block text-[10px] text-zinc-500">{{ __('Cash, cards and active configured methods') }}</span></span></button>@endif
        @if($creditEligible)<button type="button" wire:click="chooseMode('credit')" role="radio" aria-checked="{{ $mode==='credit'?'true':'false' }}" class="flex items-center gap-2 rounded-lg border px-2.5 py-2 text-start {{ $mode==='credit'?'border-cyan-600 bg-cyan-50 ring-1 ring-cyan-600 dark:bg-cyan-950/25':'border-zinc-200 dark:border-zinc-700' }}"><span class="size-3 rounded-full border-2 {{ $mode==='credit'?'border-cyan-700 bg-cyan-700':'border-zinc-400' }}"></span><flux:icon name="document-text" class="size-4" /><span><strong class="block text-xs">{{ __('Credit sale') }}</strong><span class="block text-[10px] text-zinc-500">{{ __('No payment now; balance on customer account') }}</span></span></button>@endif
    </div>

    <dl class="mt-3 space-y-1.5 border-t border-zinc-200 pt-2 text-xs tabular-nums dark:border-zinc-700"><div class="flex justify-between"><dt class="text-zinc-500">{{ __('Subtotal') }}</dt><dd><x-money :amount="$preview['subtotal']??'0.00'" :currency="$currency" /></dd></div><div class="flex justify-between"><dt class="text-zinc-500">{{ __('Discounts') }}</dt><dd>− <x-money :amount="$preview['discount_total']??'0.00'" :currency="$currency" /></dd></div><div class="flex justify-between"><dt class="text-zinc-500">{{ __('Tax') }}</dt><dd><x-money :amount="$preview['tax_total']??'0.00'" :currency="$currency" /></dd></div>@if(bccomp((string)$cashAdjustment,'0',2)!==0)<div class="flex justify-between"><dt class="text-zinc-500">{{ __('Cash rounding') }}</dt><dd><x-money :amount="$cashAdjustment" :currency="$currency" /></dd></div>@endif<div class="flex items-end justify-between border-t border-zinc-200 pt-2 dark:border-zinc-700"><dt class="font-extrabold">{{ __('Final amount') }}</dt><dd class="text-xl font-black text-cyan-700 dark:text-cyan-300"><x-money :amount="$preview['total']??'0.00'" :currency="$currency" /></dd></div></dl>
    @if($cashRoundingError)<p class="mt-2 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-900">{{ $cashRoundingError }}</p>@endif @if($checkoutBlocker)<p id="pos-checkout-blocker" class="mt-2 rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900">{{ $checkoutBlocker }}</p>@endif
    <div class="mt-3 flex gap-2">
        <button type="button" wire:click="startCheckout('{{ $mode }}')" wire:loading.attr="disabled" @disabled($checkoutBlocker || $cashRoundingError) class="inline-flex min-h-10 min-w-0 flex-1 items-center justify-center gap-2 rounded-lg bg-cyan-700 px-3 text-sm font-extrabold text-white hover:bg-cyan-800 disabled:cursor-not-allowed disabled:bg-zinc-300"><flux:icon name="check-circle" class="size-4" />{{ __('Checkout') }}</button>
        @can('returns.create')
            @can('returns.submit')
                <button type="button" wire:click="$dispatch('open-pos-refund')" title="{{ __('Refund a previous sale') }}" aria-label="{{ __('Refund a previous sale') }}" class="flex size-10 shrink-0 items-center justify-center rounded-lg border border-rose-300 text-rose-700 hover:bg-rose-50 focus-visible:outline-2 focus-visible:outline-rose-600 dark:border-rose-900 dark:text-rose-300"><flux:icon name="arrow-uturn-left" class="size-4" /></button>
            @endcan
        @endcan
    </div>

    <dialog wire:key="pos-checkout-dialog-{{ $order?->uuid }}-{{ $payable }}-{{ $mode }}-{{ count($paymentLines) }}" class="m-auto max-h-[96vh] w-[min(97vw,76rem)] overflow-y-auto rounded-xl bg-white p-0 text-start shadow-2xl backdrop:bg-zinc-950/70 dark:bg-zinc-900 dark:text-zinc-100 md:overflow-visible" x-data="posPaymentCalculator({ payable: @js($payable), cashReceived: @js($cashDraft['tendered'] ?? ''), allowOutstanding: @js($creditEligible), creditOnly: @js($mode==='credit') })" x-on:open-pos-checkout.window="$el.showModal()" x-on:close="submitting=false" aria-labelledby="pos-checkout-dialog-title">
        <form method="POST" action="{{ route('pos.checkout') }}" enctype="multipart/form-data" x-on:submit="if(submitting || !canComplete()){$event.preventDefault()}else{submitting=true}">
            @csrf<input type="hidden" name="checkout_token" value="{{ $order?->checkout_token }}"><input type="hidden" name="open_order_uuid" value="{{ $order?->uuid }}"><input type="hidden" name="tax_applicable" value="{{ ($taxApplicable??false)?1:0 }}"><input type="hidden" name="payment_mode" value="{{ $mode }}">
            <header class="flex items-center justify-between gap-3 border-b border-zinc-200 px-4 py-3 dark:border-zinc-800"><div class="flex items-center gap-2"><span class="flex size-9 items-center justify-center rounded-lg bg-cyan-100 text-cyan-700 dark:bg-cyan-950/40 dark:text-cyan-300">@if($mode==='cash')<flux:icon name="banknotes" class="size-5" />@elseif($mode==='credit')<flux:icon name="document-text" class="size-5" />@else<flux:icon name="credit-card" class="size-5" />@endif</span><div><h2 id="pos-checkout-dialog-title" class="font-extrabold">{{ $mode==='credit'?__('Credit sale'):($mode==='cash'?__('Cash payment'):($mode==='card'?__('Card / electronic payment'):__('Mixed split payment'))) }}</h2><p class="text-xs text-zinc-500">{{ __('Secure atomic checkout') }}</p></div></div><button type="button" x-on:click="$el.closest('dialog').close()" class="flex size-9 items-center justify-center rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800" aria-label="{{ __('Cancel checkout') }}"><flux:icon name="x-mark" class="size-5" /></button></header>
            <div class="grid gap-3 p-4 md:grid-cols-[.78fr_1.5fr]">
                <aside class="space-y-3"><section class="grid grid-cols-2 gap-x-3 gap-y-2 rounded-lg bg-zinc-50 p-3 text-xs dark:bg-zinc-950"><div><span class="block text-zinc-500">{{ __('Customer') }}</span><strong>{{ $selectedCustomer?(str_starts_with(app()->getLocale(), 'ar')?$selectedCustomer->name_ar:$selectedCustomer->name_en):__('Walk-in customer') }}</strong></div><div><span class="block text-zinc-500">{{ __('Branch / outlet') }}</span><strong>{{ str_starts_with(app()->getLocale(), 'ar')?$context->branch?->name_ar:$context->branch?->name_en }} · {{ str_starts_with(app()->getLocale(), 'ar')?$store?->name_ar:$store?->name_en }}</strong></div></section><section class="rounded-lg border border-zinc-200 p-3 dark:border-zinc-700"><dl class="space-y-1.5 text-xs"><div class="flex justify-between"><dt class="text-zinc-500">{{ __('Subtotal') }}</dt><dd><x-money :amount="$preview['subtotal']??'0.00'" :currency="$currency" /></dd></div><div class="flex justify-between"><dt class="text-zinc-500">{{ __('Discounts') }}</dt><dd><x-money :amount="$preview['discount_total']??'0.00'" :currency="$currency" /></dd></div><div class="flex justify-between"><dt class="text-zinc-500">{{ __('Tax') }}</dt><dd><x-money :amount="$preview['tax_total']??'0.00'" :currency="$currency" /></dd></div><div class="flex justify-between"><dt class="text-zinc-500">{{ __('Cash rounding') }}</dt><dd><x-money :amount="$cashAdjustment" :currency="$currency" /></dd></div><div class="mt-2 flex justify-between border-t border-zinc-200 pt-2 text-lg font-black dark:border-zinc-700"><dt>{{ __('Final') }}</dt><dd><x-money :amount="$payable" :currency="$currency" /></dd></div></dl></section><textarea name="notes" wire:model.blur="notes" rows="2" maxlength="1000" aria-label="{{ __('Order notes (optional)') }}" placeholder="{{ __('Order notes (optional)') }}" class="block w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950"></textarea></aside>
                <main class="min-w-0 space-y-3">
                    @if(in_array($mode,['cash','split'],true))<div class="inline-flex rounded-lg bg-zinc-100 p-1 text-xs font-bold dark:bg-zinc-800"><button type="button" wire:click="chooseMode('cash')" class="rounded-md px-3 py-1.5 {{ $mode==='cash'?'bg-white shadow-sm dark:bg-zinc-700':'' }}">{{ __('Single payment') }}</button><button type="button" wire:click="chooseMode('split')" class="rounded-md px-3 py-1.5 {{ $mode==='split'?'bg-white shadow-sm dark:bg-zinc-700':'' }}">{{ __('Split payment') }}</button></div>@endif
                    <div class="flex items-center justify-between"><h3 class="text-sm font-extrabold">{{ $mode==='credit'?__('Credit sale'): (count($paymentLines)>1?__('Payment portions'):__('Payment details')) }}</h3>@if(in_array($mode,['card','split'],true))<button type="button" wire:click="addPaymentLine" class="rounded-lg px-3 py-1.5 text-xs font-bold text-cyan-700 hover:bg-cyan-50 dark:text-cyan-300">{{ $mode==='card'?__('Add card portion'):__('Add payment portion') }}</button>@endif</div>
                    @if($mode==='credit')<p class="rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900">{{ __('No payment now; balance on customer account') }}</p>@elseif($creditEligible)<p class="rounded-lg bg-cyan-50 px-3 py-2 text-xs font-semibold text-cyan-900">{{ __('You may collect part now; the remainder stays on the customer account') }}</p>@endif
                    @if($creditEligible)<div x-show="hasRemaining()" class="rounded-lg bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-900">{{ __('Remaining on customer account') }}: <strong x-text="amountRemaining()"></strong></div>@endif
                    <div class="grid gap-2 {{ count($paymentLines)>1?'md:grid-cols-2':'' }}">@foreach($paymentLines as $index=>$line)@php($selectedMethod=$methods->firstWhere('id',(int)($line['method_id']??0)))@php($isCashLine=$selectedMethod?->isCash()??false)@php($isGiftCardLine=(string)($selectedMethod?->type??'')==='gift_card')<fieldset data-payment-part @if($isCashLine||($mode==='cash'&&$cashMethod)) data-cash-payment @endif class="rounded-lg border border-zinc-200 p-3 dark:border-zinc-700">@if(count($paymentLines)>1)<legend class="px-1 text-[11px] font-bold">{{ __('Payment portion :number',['number'=>$index+1]) }}</legend>@endif<div class="grid gap-2 sm:grid-cols-2">
                        @if($mode==='cash'&&$cashMethod)<input type="hidden" name="payments[{{ $index }}][method_id]" value="{{ $cashMethod->id }}" data-payment-method><div class="text-sm font-bold sm:col-span-2">{{ str_starts_with(app()->getLocale(), 'ar')?$cashMethod->name_ar:$cashMethod->name_en }}</div>@else<label class="text-xs font-bold">{{ __('Payment method') }}<select name="payments[{{ $index }}][method_id]" data-payment-method x-on:change="revision++" wire:model.blur="paymentLines.{{ $index }}.method_id" required class="mt-1 h-9 w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="">{{ __('Select a method') }}</option>@foreach($methods as $method)@if(!($mode==='card'&&$method->isCash()))<option value="{{ $method->id }}">{{ str_starts_with(app()->getLocale(), 'ar')?$method->name_ar:$method->name_en }}</option>@endif @endforeach</select></label>@endif
                        @if($isCashLine||($mode==='cash'&&$cashMethod))<input type="hidden" name="payments[{{ $index }}][amount]" value="0"><div class="sm:col-span-2"><label for="cash-received-{{ $index }}" class="text-xs font-bold">{{ __('Cash received') }}</label><div class="mt-1 flex gap-2"><input id="cash-received-{{ $index }}" name="payments[{{ $index }}][tendered]" wire:model.blur="paymentLines.{{ $index }}.tendered" x-model="cashReceived" x-on:input="revision++" type="number" min="0.01" step="0.01" inputmode="decimal" required class="h-10 min-w-0 flex-1 rounded-lg border-zinc-300 text-lg font-black dark:border-zinc-700 dark:bg-zinc-950"><button type="button" x-on:click="useExactCash('cash-received-{{ $index }}')" class="shrink-0 rounded-lg bg-cyan-50 px-3 text-xs font-bold text-cyan-800 dark:bg-cyan-950/30 dark:text-cyan-200">{{ __('Exact amount') }}</button></div><div class="mt-1.5 flex flex-wrap gap-1">@foreach($quickCash as $denomination)<button type="button" x-on:click="useQuickCash('{{ (int)$denomination }}','cash-received-{{ $index }}')" class="h-7 rounded border border-zinc-300 px-2 text-[11px] font-bold tabular-nums dark:border-zinc-700">{{ $denomination }}</button>@endforeach</div><div class="mt-2 grid grid-cols-2 gap-2 text-xs"><div x-show="hasRemaining()" class="rounded-lg bg-amber-50 px-2 py-1.5 text-amber-900"><span>{{ __('Amount remaining to pay') }}</span><strong class="ms-1" x-text="amountRemaining()"></strong></div><div x-show="hasChange()" class="rounded-lg bg-emerald-50 px-2 py-1.5 text-emerald-900"><span>{{ __('Change due to customer') }}</span><strong class="ms-1" x-text="changeDue()"></strong></div><div x-show="isExact()" class="rounded-lg bg-zinc-100 px-2 py-1.5 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-200"><span>{{ __('Remaining / change') }}</span><strong class="ms-1">0.00</strong></div></div></div>
                        @else<label class="text-xs font-bold">{{ __('Allocated amount') }}<input name="payments[{{ $index }}][amount]" wire:model.blur="paymentLines.{{ $index }}.amount" x-on:input="revision++" type="number" min="0.01" step="0.01" inputmode="decimal" data-noncash-amount required class="mt-1 h-9 w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950"></label>@if($selectedMethod?->requires_evidence)<label class="text-xs font-bold">{{ __('Transaction reference') }}<input name="payments[{{ $index }}][evidence_reference]" wire:model.blur="paymentLines.{{ $index }}.evidence_reference" maxlength="190" autocomplete="off" required class="mt-1 h-9 w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950"></label>@can('pos_sales.payment_evidence_upload')<label class="text-xs font-bold sm:col-span-2">{{ __('Payment evidence') }}<input name="payments[{{ $index }}][evidence]" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" class="mt-1 block w-full text-xs"></label>@endcan @endif @if($isGiftCardLine)<label class="text-xs font-bold">{{ __('Gift Card identifier') }}<input name="payments[{{ $index }}][gift_card_identifier]" wire:model.blur="paymentLines.{{ $index }}.gift_card_identifier" required class="mt-1 h-9 w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950"></label>@endif @endif
                    </div>@if(($mode==='split'||$mode==='card')&&count($paymentLines)>1)<button type="button" wire:click="removePaymentLine({{ $index }})" class="mt-2 text-[11px] font-bold text-rose-600">{{ __('Remove portion') }}</button>@endif</fieldset>@endforeach</div>
                    @if($mode!=='cash')<p class="text-[10px] text-zinc-500">{{ __('Never enter a card number, security code, magnetic-stripe data, or PIN.') }}</p>@endif
                </main>
            </div>
            <footer class="flex justify-end gap-2 border-t border-zinc-200 px-4 py-3 dark:border-zinc-800"><button type="button" x-on:click="$el.closest('dialog').close()" class="min-h-10 rounded-lg px-4 text-sm font-bold hover:bg-zinc-100 dark:hover:bg-zinc-800">{{ __('Cancel') }}</button><button type="submit" x-bind:disabled="submitting || !canComplete()" class="inline-flex min-h-10 items-center rounded-lg bg-cyan-700 px-5 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-60"><span x-show="!submitting">{{ __('Complete sale') }}</span><span x-show="submitting" x-cloak>{{ __('Completing sale…') }}</span></button></footer>
        </form>
    </dialog>
</section>
