<section class="flex min-w-0 flex-col overflow-hidden rounded-xl bg-white shadow-xs ring-1 ring-zinc-200 dark:bg-zinc-900 dark:ring-zinc-800 xl:h-[calc(100vh-5.5rem)]" aria-labelledby="pos-products-heading">
    <header class="p-3 pb-2"><div class="flex items-center justify-between"><h2 id="pos-products-heading" class="text-sm font-extrabold">{{ __('Products') }}</h2><span class="rounded-full bg-zinc-100 px-2 py-0.5 text-[11px] font-bold dark:bg-zinc-800">{{ $products->count() }}</span></div>
        <form wire:submit="submitSearch" class="mt-2"><div class="flex gap-2"><label for="live-pos-product-search" class="sr-only">{{ __('Scan or search by name, SKU, barcode, or option') }}</label><div class="relative min-w-0 flex-1"><flux:icon name="magnifying-glass" class="pointer-events-none absolute start-3 top-1/2 z-10 size-4 -translate-y-1/2 text-zinc-400" /><input id="live-pos-product-search" wire:model.live.debounce.250ms="search" autocomplete="off" inputmode="search" dir="auto" autofocus class="block h-10 w-full rounded-lg border border-zinc-300 bg-zinc-50 ps-9 pe-3 text-sm outline-none focus:border-cyan-600 focus:ring-2 focus:ring-cyan-600/15 dark:border-zinc-700 dark:bg-zinc-950" placeholder="{{ __('Search products or scan barcode') }}"></div><button type="button" onclick="document.getElementById('live-pos-product-search').focus()" title="{{ __('Activate barcode scanning') }}" aria-label="{{ __('Activate barcode scanning') }}" class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:outline-2 focus-visible:outline-cyan-600 dark:bg-zinc-100 dark:text-zinc-900"><flux:icon name="qr-code" class="size-5" /></button></div></form>
        <nav class="mt-2 flex gap-1.5 overflow-x-auto pb-1" aria-label="{{ __('Product categories') }}"><button wire:click="chooseCategory(null)" class="h-8 shrink-0 rounded-lg px-2.5 text-xs font-semibold {{ $categoryId===null?'bg-cyan-700 text-white':'bg-zinc-100 dark:bg-zinc-800' }}">{{ __('All') }}</button>@foreach($categories as $category)<button wire:click="chooseCategory({{ $category->id }})" class="h-8 shrink-0 rounded-lg px-2.5 text-xs font-semibold {{ $categoryId===$category->id?'bg-cyan-700 text-white':'bg-zinc-100 dark:bg-zinc-800' }}">{{ str_starts_with(app()->getLocale(), 'ar')?$category->name_ar:$category->name_en }}</button>@endforeach</nav>
    </header>
    @if(!$context->isReady())<div class="px-3 pb-2"><p class="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-900 dark:bg-amber-950/30 dark:text-amber-100">{{ $context->disabledReason ?? __('POS is not ready for selling.') }}</p></div>@endif
    @error('selection')<div class="px-3 pb-2"><p class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{{ $message }}</p></div>@enderror
    <div wire:loading class="grid grid-cols-3 gap-2 p-3"><div class="h-32 animate-pulse rounded-lg bg-zinc-100 dark:bg-zinc-800"></div><div class="h-32 animate-pulse rounded-lg bg-zinc-100 dark:bg-zinc-800"></div><div class="h-32 animate-pulse rounded-lg bg-zinc-100 dark:bg-zinc-800"></div></div>
    <div wire:loading.remove class="min-h-0 flex-1 overflow-y-auto border-t border-zinc-100 p-2.5 dark:border-zinc-800"><div class="grid grid-cols-2 gap-2 sm:grid-cols-3 2xl:grid-cols-4" data-pos-product-grid>
        @forelse($products as $product)
            @php($isFamily=$product->isFamily()) @php($price=$isFamily?$familyRanges->get($product->id):$simplePrices->get($product->id)) @php($stock=$isFamily?$familyStock->has($product->id):(($balance=$simpleStock->get($product->id))&&bccomp(bcsub((string)$balance->on_hand,(string)$balance->reserved,6),'0',6)>0)) @php($image=$product->images->firstWhere('role','main')??$product->images->first()??($isFamily?$familyChildImages->get($product->id):null))
            <article class="group flex min-w-0 flex-col overflow-hidden rounded-lg border border-zinc-200 bg-white hover:border-cyan-400 dark:border-zinc-800 dark:bg-zinc-950" data-product-family="{{ $product->id }}"><div class="relative flex h-20 items-center justify-center overflow-hidden bg-zinc-100 dark:bg-zinc-800">@if($image)<img src="{{ route('pos.products.thumbnail',['product'=>$image->product_id,'attachment'=>$image->attachment_id]) }}" alt="" width="240" height="160" loading="lazy" class="h-full w-full object-cover">@else<flux:icon name="cube" class="size-7 text-zinc-400" />@endif<span class="absolute start-1.5 top-1.5 rounded px-1.5 py-0.5 text-[9px] font-bold {{ $stock?'bg-emerald-50 text-emerald-700':'bg-zinc-50 text-zinc-600' }}">{{ $stock?__('In stock'):__('Out of stock') }}</span></div><div class="flex flex-1 flex-col p-2"><h3 class="line-clamp-2 min-h-8 text-xs font-bold">{{ str_starts_with(app()->getLocale(), 'ar')?$product->name_ar:$product->name_en }}</h3><p class="truncate font-mono text-[10px] text-zinc-500">{{ $product->item_code }}</p><div class="mt-auto pt-1.5">@if($price)<strong class="text-xs tabular-nums">@if($isFamily){{ number_format((float)$price->min_price,2) }}@if((string)$price->min_price!==(string)$price->max_price) – {{ number_format((float)$price->max_price,2) }}@endif {{ $store?->branch?->currency??'EGP' }}@else<x-money :amount="$price->amount" :currency="$store?->branch?->currency ?? 'EGP'" />@endif</strong>@else<span class="text-[10px] font-semibold text-amber-700">{{ __('No selling price') }}</span>@endif @if($isFamily)<button wire:click="openFamily({{ $product->id }})" @disabled(!$price||!$context->isReady()) class="mt-1.5 h-8 w-full rounded-md bg-cyan-700 px-2 text-[11px] font-bold text-white disabled:bg-zinc-300">{{ __('Choose variation') }}</button>@else<button wire:click="addProduct({{ $product->id }})" @disabled(!$price||!$stock||!$context->isReady()) class="mt-1.5 h-8 w-full rounded-md bg-cyan-700 px-2 text-[11px] font-bold text-white disabled:bg-zinc-300">{{ __('Add to cart') }}</button>@endif</div></div></article>
        @empty<div class="col-span-full flex min-h-40 flex-col items-center justify-center text-center"><flux:icon name="magnifying-glass" class="size-7 text-zinc-300" /><p class="mt-2 text-sm font-semibold">{{ __('No products available.') }}</p></div>@endforelse
    </div></div>

    @if($drawer)
        @php($selected=$selectedVariantId?$drawer->variants->firstWhere('id',$selectedVariantId):null) @php($selectedPrice=$selected?$drawerPrices->get($selected->id):null) @php($selectedStock=$selected?$drawerStock->get($selected->id):null) @php($selectedAvailable=$selectedStock?bcsub((string)$selectedStock->on_hand,(string)$selectedStock->reserved,6):'0') @php($canAdd=$selected&&$selected->status==='active'&&$selectedPrice&&bccomp($selectedAvailable,'0',6)>0)
        <div class="fixed inset-0 z-50 flex justify-end bg-zinc-950/60" wire:click.self="$set('openFamilyId', null)"><aside class="h-full w-full max-w-xl overflow-y-auto bg-white p-4 shadow-2xl dark:bg-zinc-900" role="dialog" aria-modal="true"><div class="flex items-center justify-between"><div><h2 class="font-extrabold">{{ str_starts_with(app()->getLocale(), 'ar')?$drawer->name_ar:$drawer->name_en }}</h2><p class="text-xs text-zinc-500">{{ $selected?->item_code?:__('Select every option to resolve a SKU') }}</p></div><button wire:click="$set('openFamilyId', null)" class="flex size-9 items-center justify-center rounded-lg hover:bg-zinc-100" aria-label="{{ __('Close') }}"><flux:icon name="x-mark" class="size-5" /></button></div><div class="mt-4 space-y-4">@foreach($drawer->familyOptionGroups as $group)<fieldset><legend class="text-sm font-bold">{{ str_starts_with(app()->getLocale(), 'ar')?$group->name_ar:$group->name_en }}</legend><div class="mt-2 flex flex-wrap gap-1.5">@foreach($group->values as $value)@php($available=$optionAvailability[$group->id][$value->id]??false)<button wire:click="selectValue({{ $group->id }}, {{ $value->id }})" @disabled(!$available) class="min-h-9 rounded-lg border px-3 text-xs font-semibold {{ ($selectedValues[$group->id]??null)===$value->id?'border-cyan-700 bg-cyan-50':'border-zinc-200 dark:border-zinc-700' }} disabled:opacity-35">{{ str_starts_with(app()->getLocale(), 'ar')?$value->name_ar:$value->name_en }}</button>@endforeach</div></fieldset>@endforeach</div><div class="mt-5 grid grid-cols-[1fr_6rem] items-end gap-3 rounded-lg bg-zinc-50 p-3 dark:bg-zinc-950"><div>@if($selectedPrice)<strong><x-money :amount="$selectedPrice->amount" :currency="$store?->branch?->currency ?? 'EGP'" /></strong><p class="text-xs text-zinc-500">{{ __('Available') }}: <x-product-quantity :value="$selectedAvailable" /></p>@else<p class="text-xs text-amber-700">{{ __('Complete the selection to see price and availability.') }}</p>@endif</div><input wire:model="quantity" type="number" min="1" step="1" aria-label="{{ __('Quantity') }}" class="h-10 rounded-lg border-zinc-300"></div><button wire:click="addSelected" @disabled(!$canAdd) class="mt-3 h-11 w-full rounded-lg bg-cyan-700 font-extrabold text-white disabled:bg-zinc-300">{{ __('Add selected SKU to cart') }}</button></aside></div>
    @endif
</section>
