<div data-pos-refund-wizard>
@if($open)
<dialog open class="m-auto max-h-[96vh] w-[min(97vw,80rem)] overflow-hidden rounded-xl bg-white p-0 text-start shadow-2xl backdrop:bg-zinc-950/75 dark:bg-zinc-900 dark:text-zinc-100" aria-modal="true" aria-labelledby="pos-refund-heading" x-data x-init="$nextTick(() => document.getElementById('pos-refund-lookup')?.focus())">
    <section class="flex max-h-[96vh] flex-col" dir="{{ str_starts_with(app()->getLocale(), 'ar') ? 'rtl' : 'ltr' }}">
        <header class="flex items-center justify-between gap-3 border-b border-zinc-200 px-4 py-3 dark:border-zinc-800">
            <div class="flex min-w-0 items-center gap-3"><span class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-rose-100 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300"><flux:icon name="arrow-uturn-left" class="size-5" /></span><div class="min-w-0"><h2 id="pos-refund-heading" class="font-extrabold">{{ __('Refund sale') }}</h2><p class="truncate text-xs text-zinc-500">{{ __('Linked refund without changing the original sale') }}</p></div></div>
            <button type="button" wire:click="close" class="flex size-9 items-center justify-center rounded-lg hover:bg-zinc-100 focus-visible:outline-2 focus-visible:outline-cyan-600 dark:hover:bg-zinc-800" aria-label="{{ __('Close refund wizard') }}"><flux:icon name="x-mark" class="size-5" /></button>
        </header>

        <ol class="grid grid-cols-7 border-b border-zinc-200 bg-zinc-50 text-[11px] font-bold dark:border-zinc-800 dark:bg-zinc-950" aria-label="{{ __('Refund steps') }}">
            @foreach([1 => __('Find sale'), 2 => __('Verify'), 3 => __('Items'), 4 => __('Condition'), 5 => __('Refund method'), 6 => __('Review'), 7 => __('Result')] as $number => $label)
                <li class="border-e border-zinc-200 px-1 py-2 text-center last:border-e-0 dark:border-zinc-800 {{ $step === $number ? 'bg-cyan-700 text-white' : ($step > $number ? 'text-emerald-700 dark:text-emerald-300' : 'text-zinc-500') }}"><span class="me-1 tabular-nums">{{ $number }}</span><span class="hidden sm:inline">{{ $label }}</span></li>
            @endforeach
        </ol>

        <div class="min-h-0 flex-1 overflow-y-auto p-4 md:p-5">
            @error('refund')<div class="mb-3 rounded-lg bg-rose-50 px-3 py-2 text-sm font-semibold text-rose-800 dark:bg-rose-950/30 dark:text-rose-200">{{ $message }}</div>@enderror

            @if($step === 1)
                <form wire:submit="lookup" class="mx-auto max-w-3xl space-y-4">
                    <div><h3 class="text-lg font-extrabold">{{ __('Find the original sale') }}</h3><p class="mt-1 text-sm text-zinc-500">{{ __('Enter or scan the invoice, order, receipt, or Gift Receipt code.') }}</p></div>
                    <div class="flex gap-2"><label for="pos-refund-lookup" class="sr-only">{{ __('Original sale code') }}</label><div class="relative min-w-0 flex-1"><flux:icon name="magnifying-glass" class="pointer-events-none absolute start-3 top-1/2 z-10 size-5 -translate-y-1/2 text-zinc-400" /><input id="pos-refund-lookup" wire:model="lookupTerm" autocomplete="off" dir="auto" class="block min-h-12 w-full rounded-lg border-zinc-300 bg-zinc-50 ps-11 pe-3 text-base font-semibold focus:border-cyan-600 focus:ring-cyan-600 dark:border-zinc-700 dark:bg-zinc-950" placeholder="{{ __('Invoice / order / receipt code') }}"></div><button type="button" onclick="document.getElementById('pos-refund-lookup').focus()" title="{{ __('Activate barcode scanning') }}" aria-label="{{ __('Activate barcode scanning') }}" class="flex size-12 shrink-0 items-center justify-center rounded-lg bg-zinc-900 text-white hover:bg-zinc-800 dark:bg-zinc-100 dark:text-zinc-900"><flux:icon name="qr-code" class="size-5" /></button></div>
                    @error('lookupTerm')<p class="text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror
                    <button type="submit" wire:loading.attr="disabled" class="inline-flex min-h-11 items-center justify-center rounded-lg bg-cyan-700 px-5 text-sm font-extrabold text-white disabled:opacity-60">{{ __('Verify sale') }}</button>
                </form>
            @elseif($step === 2 && $sale)
                <div class="space-y-4">
                    <div class="grid gap-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-950 md:grid-cols-4 dark:bg-emerald-950/25 dark:text-emerald-100"><div><span class="block text-xs opacity-70">{{ __('Invoice') }}</span><strong dir="ltr">{{ $sale->document_number }}</strong></div><div><span class="block text-xs opacity-70">{{ __('Customer') }}</span><strong>{{ $sale->customer ? (str_starts_with(app()->getLocale(), 'ar') ? $sale->customer->name_ar : $sale->customer->name_en) : __('Walk-in customer') }}</strong></div><div><span class="block text-xs opacity-70">{{ __('Branch / outlet') }}</span><strong>{{ str_starts_with(app()->getLocale(), 'ar') ? $sale->branch?->name_ar : $sale->branch?->name_en }} · {{ str_starts_with(app()->getLocale(), 'ar') ? $sale->store?->name_ar : $sale->store?->name_en }}</strong></div><div><span class="block text-xs opacity-70">{{ __('Original total') }}</span><strong><x-money :amount="$sale->payable_total" :currency="$sale->currency_code" /></strong></div></div>
                    <section><h3 class="text-sm font-extrabold">{{ __('Original payment methods') }}</h3><div class="mt-2 flex flex-wrap gap-2">@foreach($sale->payments as $payment)<span class="rounded-lg border border-zinc-200 px-3 py-2 text-sm dark:border-zinc-700">{{ str_starts_with(app()->getLocale(), 'ar') ? $payment->paymentMethod?->name_ar : $payment->paymentMethod?->name_en }} · <strong><x-money :amount="$payment->amount" :currency="$sale->currency_code" /></strong></span>@endforeach</div></section>
                </div>
            @elseif($step === 3 && $sale)
                <div class="space-y-3"><div class="flex items-center justify-between"><div><h3 class="font-extrabold">{{ __('Select refundable items and quantities') }}</h3><p class="text-xs text-zinc-500">{{ __('Quantities cannot exceed the remaining refundable quantity.') }}</p></div><button type="button" wire:click="setAllRefundable" class="rounded-lg px-3 py-2 text-xs font-bold text-cyan-700 hover:bg-cyan-50 dark:text-cyan-300">{{ __('Select all remaining') }}</button></div>
                <div class="overflow-x-auto rounded-lg border border-zinc-200 dark:border-zinc-800"><table class="w-full text-sm"><thead class="bg-zinc-50 text-xs text-zinc-500 dark:bg-zinc-950"><tr><th class="p-2 text-start">{{ __('Item') }}</th><th class="p-2 text-start">{{ __('Sold') }}</th><th class="p-2 text-start">{{ __('Remaining') }}</th><th class="w-36 p-2 text-start">{{ __('Refund quantity') }}</th></tr></thead><tbody class="divide-y divide-zinc-100 dark:divide-zinc-800">@foreach($sale->lines as $line)<tr><td class="p-2"><strong>{{ str_starts_with(app()->getLocale(), 'ar') ? $line->name_ar : $line->name_en }}</strong><span class="ms-2 font-mono text-xs text-zinc-500" dir="ltr">{{ $line->item_code }}</span></td><td class="p-2"><x-product-quantity :value="$line->quantity" /></td><td class="p-2"><x-product-quantity :value="$remaining[$line->id] ?? '0'" /></td><td class="p-2"><input wire:model="quantities.{{ $line->id }}" type="number" min="0" max="{{ $remaining[$line->id] ?? 0 }}" step="1" class="h-9 w-full rounded-lg border-zinc-300 bg-white px-2 font-bold dark:border-zinc-700 dark:bg-zinc-950" @disabled(bccomp($remaining[$line->id] ?? '0', '0', 6) <= 0)></td></tr>@endforeach</tbody></table></div></div>
            @elseif($step === 4 && $sale)
                <div class="space-y-3"><div><h3 class="font-extrabold">{{ __('Condition and inventory return location') }}</h3><p class="text-xs text-zinc-500">{{ __('Non-saleable and damaged items must return to an authorized damaged location.') }}</p></div>
                <div class="grid gap-2">@foreach($sale->lines as $line)@if(bccomp((string)($quantities[$line->id] ?? '0'), '0', 6) > 0)<article class="grid items-end gap-2 rounded-lg border border-zinc-200 p-3 md:grid-cols-[minmax(12rem,1fr)_12rem_12rem_minmax(14rem,1fr)] dark:border-zinc-800"><div><strong class="text-sm">{{ str_starts_with(app()->getLocale(), 'ar') ? $line->name_ar : $line->name_en }}</strong><p class="text-xs text-zinc-500">{{ __('Quantity') }}: {{ $quantities[$line->id] }}</p></div><label class="text-xs font-bold">{{ __('Item condition') }}<select wire:model="conditions.{{ $line->id }}" class="mt-1 h-9 w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="sellable">{{ __('Sellable') }}</option><option value="non_sellable">{{ __('Non-saleable') }}</option><option value="damaged">{{ __('Damaged') }}</option><option value="manager_review">{{ __('Manager review') }}</option></select></label><label class="text-xs font-bold">{{ __('Inventory disposition') }}<select wire:model="dispositions.{{ $line->id }}" class="mt-1 h-9 w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950"><option value="restock">{{ __('Restock') }}</option><option value="quarantine">{{ __('Quarantine') }}</option></select></label><label class="text-xs font-bold">{{ __('Return location') }}<select wire:model="returnStoreIds.{{ $line->id }}" class="mt-1 h-9 w-full rounded-lg border-zinc-300 text-sm dark:border-zinc-700 dark:bg-zinc-950">@foreach($stores as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->code }} · {{ str_starts_with(app()->getLocale(), 'ar') ? $candidate->name_ar : $candidate->name_en }}</option>@endforeach</select></label></article>@endif@endforeach</div></div>
            @elseif($step === 5 && $sale)
                <div class="space-y-4"><div><h3 class="font-extrabold">{{ __('Select refund method') }}</h3><p class="text-xs text-zinc-500">{{ __('The original payment allocation is selected by default.') }}</p></div>
                    <div class="grid gap-2 md:grid-cols-3"><button type="button" wire:click="chooseRefundMethod('original_tender')" class="rounded-xl border p-3 text-start {{ $refundMethod === 'original_tender' ? 'border-cyan-600 bg-cyan-50 ring-1 ring-cyan-600 dark:bg-cyan-950/25' : 'border-zinc-200 dark:border-zinc-700' }}"><span class="flex items-center gap-2 font-extrabold"><span class="size-3 rounded-full border-2 {{ $refundMethod === 'original_tender' ? 'border-cyan-700 bg-cyan-700' : 'border-zinc-400' }}"></span><flux:icon name="credit-card" class="size-5" />{{ __('Original payment methods') }}</span><span class="mt-1 block text-xs text-zinc-500">{{ __('Refund safely against each original payment line.') }}</span></button><button type="button" wire:click="chooseRefundMethod('cash_refund')" @disabled(!$cashAvailable) class="rounded-xl border p-3 text-start disabled:cursor-not-allowed disabled:opacity-45 {{ $refundMethod === 'cash_refund' ? 'border-cyan-600 bg-cyan-50 ring-1 ring-cyan-600 dark:bg-cyan-950/25' : 'border-zinc-200 dark:border-zinc-700' }}"><span class="flex items-center gap-2 font-extrabold"><span class="size-3 rounded-full border-2 {{ $refundMethod === 'cash_refund' ? 'border-cyan-700 bg-cyan-700' : 'border-zinc-400' }}"></span><flux:icon name="banknotes" class="size-5" />{{ __('Cash refund') }}</span><span class="mt-1 block text-xs text-zinc-500">{{ $cashAvailable ? __('Uses the active authorized drawer.') : __('Requires an open shift and drawer at this outlet.') }}</span></button>@can('gift_cards.issue')<button type="button" wire:click="chooseRefundMethod('gift_card')" class="rounded-xl border p-3 text-start {{ $refundMethod === 'gift_card' ? 'border-cyan-600 bg-cyan-50 ring-1 ring-cyan-600 dark:bg-cyan-950/25' : 'border-zinc-200 dark:border-zinc-700' }}"><span class="flex items-center gap-2 font-extrabold"><span class="size-3 rounded-full border-2 {{ $refundMethod === 'gift_card' ? 'border-cyan-700 bg-cyan-700' : 'border-zinc-400' }}"></span><flux:icon name="gift" class="size-5" />{{ __('Gift Card') }}</span><span class="mt-1 block text-xs text-zinc-500">{{ __('Issue an auditable store-value refund.') }}</span></button>@endcan</div>
                    @error('refundMethod')<p class="text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror
                    @if($refundMethod !== 'gift_card')<div class="overflow-hidden rounded-lg border border-zinc-200 dark:border-zinc-800"><table class="w-full text-sm"><thead class="bg-zinc-50 text-xs text-zinc-500 dark:bg-zinc-950"><tr><th class="p-2 text-start">{{ __('Method') }}</th><th class="p-2 text-start">{{ __('Refund amount') }}</th><th class="p-2 text-start">{{ __('Safe reference') }}</th></tr></thead><tbody>@foreach($allocations as $index => $allocation)@php($payment = $sale->payments->firstWhere('id', (int)($allocation['original_payment_id'] ?? 0)))@php($method = $payment?->paymentMethod ?? ($cashMethod && (int)($allocation['method_id'] ?? 0) === $cashMethod->id ? $cashMethod : null))<tr class="border-t border-zinc-100 dark:border-zinc-800"><td class="p-2">{{ str_starts_with(app()->getLocale(), 'ar') ? $method?->name_ar : $method?->name_en }}</td><td class="p-2"><input wire:model="allocations.{{ $index }}.amount" type="number" min="0.01" step="0.01" class="h-9 w-36 rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-950"></td><td class="p-2">@if($method?->requires_evidence)<input wire:model="allocations.{{ $index }}.safe_reference" maxlength="190" autocomplete="off" class="h-9 w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-950" placeholder="{{ __('Required transaction reference') }}">@else<span class="text-xs text-zinc-400">{{ __('Not required') }}</span>@endif</td></tr>@endforeach</tbody></table></div>@endif
                    @error('allocations')<p class="text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror
                    <label class="block text-sm font-bold">{{ __('Refund reason') }}<textarea wire:model="reason" rows="2" maxlength="2000" class="mt-1 block w-full rounded-lg border-zinc-300 dark:border-zinc-700 dark:bg-zinc-950" required></textarea></label>@error('reason')<p class="text-sm font-semibold text-rose-600">{{ $message }}</p>@enderror
                </div>
            @elseif($step === 6 && $sale)
                <div class="grid gap-4 md:grid-cols-[1.4fr_.8fr]"><section><h3 class="font-extrabold">{{ __('Review refund') }}</h3><div class="mt-2 overflow-hidden rounded-lg border border-zinc-200 dark:border-zinc-800">@foreach($sale->lines as $line)@if(bccomp((string)($quantities[$line->id] ?? '0'), '0', 6) > 0)<div class="flex items-center justify-between border-b border-zinc-100 px-3 py-2 text-sm last:border-b-0 dark:border-zinc-800"><span>{{ str_starts_with(app()->getLocale(), 'ar') ? $line->name_ar : $line->name_en }}</span><strong>× {{ $quantities[$line->id] }}</strong></div>@endif@endforeach</div><p class="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-900 dark:bg-amber-950/30 dark:text-amber-100">{{ __('Submitting creates an immutable linked refund. Independent approval remains required unless an authorized bypass applies.') }}</p></section><aside class="rounded-xl bg-zinc-950 p-4 text-white"><h3 class="text-sm font-extrabold">{{ __('Refund summary') }}</h3><dl class="mt-3 space-y-2 text-sm tabular-nums"><div class="flex justify-between"><dt class="text-zinc-400">{{ __('Subtotal') }}</dt><dd>{{ $totals['subtotal_refund'] ?? '0.00' }}</dd></div><div class="flex justify-between"><dt class="text-zinc-400">{{ __('Discounts') }}</dt><dd>− {{ $totals['discount_refund'] ?? '0.00' }}</dd></div><div class="flex justify-between"><dt class="text-zinc-400">{{ __('Tax') }}</dt><dd>{{ $totals['tax_refund'] ?? '0.00' }}</dd></div><div class="flex justify-between"><dt class="text-zinc-400">{{ __('Cash rounding') }}</dt><dd>{{ $totals['rounding_refund'] ?? '0.00' }}</dd></div><div class="flex justify-between border-t border-zinc-700 pt-2 text-lg font-black"><dt>{{ __('Final refund') }}</dt><dd>{{ $totals['settlement_value'] ?? '0.00' }} {{ $sale->currency_code }}</dd></div></dl><p class="mt-3 text-xs text-zinc-400">{{ __('Method') }}: {{ $refundMethod === 'original_tender' ? __('Original payment methods') : ($refundMethod === 'cash_refund' ? __('Cash refund') : __('Gift Card')) }}</p></aside></div>
            @elseif($step === 7 && $result)
                <div class="mx-auto max-w-2xl py-4 text-center"><div class="mx-auto flex size-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300"><flux:icon name="check-circle" class="size-8" /></div><h3 class="mt-3 text-lg font-black">{{ $result->status === 'completed' ? __('Refund completed successfully') : __('Refund submitted for independent approval') }}</h3><p class="mt-1 font-mono text-base font-bold" dir="ltr">{{ $result->return_number }}</p><p class="mt-2 text-sm text-zinc-500">{{ $result->status === 'completed' ? __('Inventory and payment reversals were posted atomically.') : __('The original sale remains unchanged. An authorized approver must approve before posting.') }}</p><div class="mt-5 flex flex-wrap justify-center gap-2">@if($result->status === 'completed')@can('returns.print')<a href="{{ route('pos.refund.receipt', $result) }}" target="_blank" class="inline-flex min-h-10 items-center gap-2 rounded-lg bg-cyan-700 px-4 text-sm font-extrabold text-white"><flux:icon name="printer" class="size-4" />{{ __('Print refund receipt') }}</a>@endcan @endif<a href="{{ route('returns.show', $result) }}" target="_blank" class="inline-flex min-h-10 items-center rounded-lg border border-zinc-300 px-4 text-sm font-bold dark:border-zinc-700">{{ __('View refund') }}</a><button type="button" wire:click="close" class="min-h-10 rounded-lg border border-zinc-300 px-4 text-sm font-bold dark:border-zinc-700">{{ __('Return to POS') }}</button></div></div>
            @endif
        </div>

        @if($step > 1 && $step < 7)
            <footer class="flex items-center justify-between gap-2 border-t border-zinc-200 px-4 py-3 dark:border-zinc-800"><button type="button" wire:click="back" class="min-h-10 rounded-lg px-4 text-sm font-bold hover:bg-zinc-100 dark:hover:bg-zinc-800">{{ __('Back') }}</button><div class="flex gap-2"><button type="button" wire:click="close" class="min-h-10 rounded-lg px-4 text-sm font-bold hover:bg-zinc-100 dark:hover:bg-zinc-800">{{ __('Cancel') }}</button>@if($step < 6)<button type="button" wire:click="next" class="min-h-10 rounded-lg bg-cyan-700 px-5 text-sm font-extrabold text-white disabled:opacity-50">{{ __('Continue') }}</button>@else<button type="button" wire:click="submit" wire:loading.attr="disabled" wire:target="submit" class="inline-flex min-h-10 items-center rounded-lg bg-rose-700 px-5 text-sm font-extrabold text-white disabled:cursor-wait disabled:opacity-60"><span wire:loading.remove wire:target="submit">{{ __('Confirm refund') }}</span><span wire:loading wire:target="submit">{{ __('Posting refund…') }}</span></button>@endif</div></footer>
        @endif
    </section>
</dialog>
@endif
</div>
