<x-layouts::app :title="__('Cities and localities')">
<div class="mx-auto w-full max-w-7xl space-y-6 p-4 sm:p-6">
<x-page-header :title="__('Cities and localities')" :description="__('Manage company-specific residence localities. Shared Egyptian reference localities remain read-only.')" />
@if(session('success'))<flux:callout variant="success">{{ session('success') }}</flux:callout>@endif
@if($errors->any())<flux:callout variant="danger">{{ $errors->first() }}</flux:callout>@endif
@can('company_settings.edit')<form method="POST" action="{{ route('admin.settings.cities.store') }}" class="grid gap-4 rounded-2xl border border-border bg-surface p-5 md:grid-cols-3">@csrf
<flux:select name="governorate_id" :label="__('Governorate')" required>@foreach($governorates as $g)<flux:select.option value="{{ $g->id }}">{{ str_starts_with(app()->getLocale(), 'ar')?$g->name_ar:$g->name_en }}</flux:select.option>@endforeach</flux:select>
<flux:input name="code" :label="__('Stable code')" required dir="ltr"/><flux:input name="sort_order" :label="__('Order')" type="number" min="0" value="0"/><flux:input name="name_ar" :label="__('Arabic name')" required dir="rtl"/><flux:input name="name_en" :label="__('English name')" required dir="ltr"/><input type="hidden" name="status" value="active"><div class="flex items-end justify-end"><flux:button type="submit" variant="primary">{{ __('Save') }}</flux:button></div></form>@endcan
<form method="GET" class="flex gap-3"><flux:input name="q" :label="__('Search')" :value="request('q')"/><flux:button type="submit" variant="primary">{{ __('Search') }}</flux:button></form>
<x-tables.data-panel :title="__('Residence reference data')"><table class="data-table responsive-resource-table w-full"><thead><tr><th>{{ __('City / locality') }}</th><th>{{ __('Governorate') }}</th><th>{{ __('Code') }}</th><th>{{ __('Status') }}</th><th>{{ __('Action') }}</th></tr></thead><tbody>@foreach($cities as $city)<tr><td data-primary><strong>{{ str_starts_with(app()->getLocale(), 'ar')?$city->name_ar:$city->name_en }}</strong><div class="text-xs text-text-muted">{{ str_starts_with(app()->getLocale(), 'ar')?$city->name_en:$city->name_ar }}</div></td><td>{{ str_starts_with(app()->getLocale(), 'ar')?$city->governorate->name_ar:$city->governorate->name_en }}</td><td dir="ltr">{{ $city->code }}</td><td><x-status.badge :status="$city->status"/></td><td>@if($city->company_id) @can('company_settings.edit')<details><summary class="cursor-pointer">{{ __('Edit') }}</summary><form method="POST" action="{{ route('admin.settings.cities.update',$city) }}" class="mt-2 grid gap-2">@csrf @method('PUT')<input type="hidden" name="governorate_id" value="{{ $city->governorate_id }}"><flux:input name="code" :value="$city->code"/><flux:input name="name_ar" :value="$city->name_ar"/><flux:input name="name_en" :value="$city->name_en"/><flux:input name="sort_order" :value="$city->sort_order" type="number"/><flux:select name="status"><flux:select.option value="active" :selected="$city->status==='active'">{{ __('Active') }}</flux:select.option><flux:select.option value="inactive" :selected="$city->status==='inactive'">{{ __('Inactive') }}</flux:select.option></flux:select><flux:button type="submit">{{ __('Save') }}</flux:button></form></details>@endcan @else <flux:badge>{{ __('Shared reference') }}</flux:badge>@endif</td></tr>@endforeach</tbody></table><x-slot:footer>{{ $cities->links() }}</x-slot:footer></x-tables.data-panel>
</div></x-layouts::app>
