@php
    $ar = str_starts_with(app()->getLocale(), 'ar');
    $setup = $dashboard['setup'];
    $attention = collect($setup['steps'])->where('required', true)->where('complete', false)->take(6);
    $links = [
        ['admin.settings','company_settings.view','cog-6-tooth',$ar ? 'إعدادات النظام' : 'System settings',app()->isLocale('ar-EG') ? 'هوية الشركة والمدفوعات والضرائب والترقيم والطباعة.' : ($ar ? 'هوية الشركة والمدفوعات والضرائب والترقيم والطباعة.' : 'Company identity, payments, tax, numbering, and printing.')],
        ['admin.authorization-baseline','users_roles_permissions.view','users',$ar ? 'المستخدمون والصلاحيات' : 'Users & permissions',$ar ? 'حسابات الدخول والأدوار ونطاق الوصول.' : 'Sign-in accounts, roles, and access scope.'],
        ['admin.branches','branches_stores.view','building-office',$ar ? 'الفروع والمواقع' : 'Branches & locations',$ar ? 'الفروع والمتاجر والمخازن ونقاط البيع.' : 'Branches, stores, warehouses, and selling locations.'],
        ['admin.approvals','company_settings.view','check-badge',$ar ? 'صندوق الاعتمادات' : 'Approval inbox',$ar ? 'طلبات الإجراء المعلقة ضمن نطاقك.' : 'Pending action requests within your scope.'],
        ['admin.audit','audit_logs.view','clock',$ar ? 'سجل النشاط' : 'Activity log',$ar ? 'الأحداث والتغييرات المدققة دون أسرار.' : 'Audited activity and changes without secrets.'],
        ['system.health','audit_logs.view','heart',$ar ? 'صحة النظام' : 'System health',$ar ? 'مؤشرات التشغيل المدعومة.' : 'Supported operational indicators.'],
    ];
@endphp
<x-layouts::app :title="$ar ? 'مركز الإدارة' : 'Administration center'">
<x-app.page :title="$ar ? 'مركز الإدارة' : 'Administration center'" :description="$ar ? 'الجاهزية والوصول والإعدادات والاستثناءات من مساحة آمنة واحدة.' : 'Readiness, access, configuration, and exceptions in one secure workspace.'" :eyebrow="$ar ? 'الإدارة والإعدادات' : 'Administration & settings'" max-width="7xl" class="space-y-6">
<x-slot:actions>@can('company_settings.view')<flux:button :href="route('admin.settings')" icon="cog-6-tooth" variant="primary" wire:navigate>{{ $ar ? 'فتح الإعدادات' : 'Open settings' }}</flux:button>@endcan</x-slot:actions>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="{{ $ar ? 'ملخص الإدارة' : 'Administration summary' }}">
<x-cards.stat-card :label="$ar ? 'جاهزية الإعداد' : 'Setup readiness'" :value="$setup['progress_percent'].'%'" :description="$setup['completed_count'].' / '.$setup['required_count']" icon="check-circle" :tone="$setup['complete'] ? 'success' : 'warning'" />
@if($dashboard['users'])<x-cards.stat-card :label="$ar ? 'المستخدمون النشطون' : 'Active users'" :value="$dashboard['users']['active']" :description="(app()->isLocale('ar-EG') ? 'مش نشط: ' : ($ar ? 'غير نشط: ' : 'Inactive: ')).$dashboard['users']['inactive']" icon="users" tone="primary" />@endif
@if($dashboard['locations'])<x-cards.stat-card :label="$ar ? 'المواقع النشطة' : 'Active locations'" :value="$dashboard['locations']['active_stores']" :description="($ar ? 'الفروع: ' : 'Branches: ').$dashboard['locations']['active_branches']" icon="building-storefront" tone="info" />@endif
<x-cards.stat-card :label="$ar ? 'اعتمادات معلقة' : 'Pending approvals'" :value="$dashboard['pending_approvals']" :description="$ar ? 'ضمن النطاق المرئي' : 'Visible scope only'" icon="check-badge" :tone="$dashboard['pending_approvals'] ? 'warning' : 'success'" />
</section>
<section><div class="mb-4"><p class="text-xs font-semibold uppercase tracking-[.14em] text-primary">{{ $ar ? 'مساحات العمل' : 'Workspaces' }}</p><h2 class="mt-1 text-lg font-semibold">{{ $ar ? 'الوصول السريع للإدارة' : 'Administration shortcuts' }}</h2></div><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($links as [$route,$permission,$icon,$title,$description]) @can($permission)<a href="{{ route($route) }}" wire:navigate class="flex min-h-32 gap-4 rounded-2xl border border-border bg-surface p-5 shadow-card transition hover:border-primary/40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary"><span class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary-soft text-primary"><flux:icon :name="$icon" class="size-5" /></span><span><strong class="block">{{ $title }}</strong><span class="mt-1 block text-sm leading-6 text-text-muted">{{ $description }}</span></span></a>@endcan @endforeach</div></section>
<div class="grid gap-5 xl:grid-cols-2">
<x-cards.section-card :title="$ar ? 'عناصر تتطلب الإعداد' : 'Setup requiring attention'" :description="$ar ? 'متطلبات فعلية من سجل الجاهزية.' : 'Authoritative readiness requirements.'"><div class="space-y-3">@forelse($attention as $step)<div class="flex flex-col gap-3 rounded-xl border border-border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{ $step['label'] }}</p><p class="mt-1 text-sm text-text-muted">{{ $step['reason'] }}</p></div>@if($step['can_access'] && $step['route'])<flux:button size="sm" variant="subtle" :href="$step['route']" wire:navigate>{{ $step['cta_label'] }}</flux:button>@else<x-status.badge status="restricted" :label="$ar ? 'وصول مقيد' : 'Restricted'" />@endif</div>@empty<x-state.empty :title="$ar ? 'اكتملت المتطلبات' : 'Required setup is complete'" :description="app()->isLocale('ar-EG') ? 'مفيش متطلبات إلزامية معلقة.' : ($ar ? 'لا توجد متطلبات إلزامية معلقة.' : 'No mandatory readiness steps require action.')" icon="check-circle" />@endforelse</div></x-cards.section-card>
<x-cards.section-card :title="$ar ? 'آخر نشاط مدقق' : 'Recent audited activity'" :description="$ar ? 'آخر الأحداث المرئية ضمن نطاقك.' : 'Latest events visible in your scope.'">@can('audit_logs.view')<div class="space-y-3">@forelse($dashboard['recent_audit'] as $event)<div class="border-s-2 border-primary/35 ps-3"><div class="flex justify-between gap-3"><p class="font-medium">{{ str($event->event)->replace('_',' ')->headline() }}</p><time class="text-xs text-text-muted">{{ $event->created_at?->diffForHumans() }}</time></div><p class="mt-1 text-xs text-text-muted">{{ $event->actor_name ?: ($ar ? 'النظام' : 'System') }} · {{ str($event->category)->headline() }}</p></div>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش نشاط' : ($ar ? 'لا يوجد نشاط' : 'No audited activity')" :description="$ar ? 'ستظهر الأحداث هنا عند تسجيلها.' : 'Authorized events will appear here.'" icon="clock" />@endforelse</div>@else<x-state.empty :title="$ar ? 'سجل النشاط مقيد' : 'Activity is restricted'" :description="app()->isLocale('ar-EG') ? 'لا تملك صلاحية عرض السجل.' : ($ar ? 'لا تملك صلاحية عرض السجل.' : 'You cannot view the audit log.')" icon="lock-closed" />@endcan</x-cards.section-card>
</div>
@if($dashboard['configuration'])<x-cards.section-card :title="$ar ? 'تغطية الإعدادات' : 'Configuration coverage'" :description="app()->isLocale('ar-EG') ? 'أعداد السجلات النشطة بس، دون قيم سرية.' : ($ar ? 'أعداد السجلات النشطة فقط، دون قيم سرية.' : 'Active record counts only; no sensitive values.')"><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['payment_methods'=>[$ar?'طرق الدفع':'Payment methods','credit-card','payments'],'tax_rules'=>[$ar?'قواعد الضرائب':'Tax rules','calculator','tax'],'numbering_rules'=>[$ar?'قواعد الترقيم':'Numbering rules','numbered-list','sequences'],'printer_profiles'=>[app()->isLocale('ar-EG') ? 'ملفات الطباعة' : ($ar ? 'ملفات الطباعة' : 'Printer profiles'),'printer','printers']] as $key=>[$label,$icon,$tab])<a href="{{ route('admin.settings',['tab'=>$tab]) }}" wire:navigate class="rounded-xl border border-border bg-surface-muted/30 p-4"><flux:icon :name="$icon" class="size-5 text-primary" /><p class="mt-3 text-2xl font-bold tabular-nums">{{ $dashboard['configuration'][$key] }}</p><p class="mt-1 text-sm text-text-muted">{{ $label }}</p></a>@endforeach</div></x-cards.section-card>@endif
</x-app.page></x-layouts::app>
