<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ str_starts_with(app()->getLocale(), 'ar') ? 'rtl' : 'ltr' }}">
@php($layout=$template->layout_settings??[])<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ __('Print template preview') }}</title>@vite(['resources/css/app.css'])<style>@page{size:{{ $layout['width_mm']??50 }}mm {{ $layout['height_mm']??30 }}mm;margin:{{ $layout['margin_mm']??1 }}mm}.sheet-58mm{width:58mm}.sheet-80mm{width:80mm}.sheet-a5{max-width:148mm}.sheet-a4{max-width:210mm}.sheet-label{width:{{ $layout['width_mm']??50 }}mm;min-height:{{ $layout['height_mm']??30 }}mm}.barcode-svg{width:100%;height:14mm}@media print{.no-print{display:none!important}body{margin:0;padding:0;background:white}main{border:0!important;box-shadow:none!important}}</style></head>
<body class="bg-zinc-100 p-4 text-zinc-900">
<div class="no-print mx-auto mb-4 flex max-w-3xl justify-end"><button onclick="window.print()" class="rounded bg-zinc-900 px-4 py-2 text-white">{{ __('Test print') }}</button></div>
<main class="mx-auto rounded-xl border bg-white p-6 shadow-sm {{ match($template->paper_size){'58mm'=>'sheet-58mm','80mm'=>'sheet-80mm','a5'=>'sheet-a5','a4'=>'sheet-a4',default=>'sheet-label'} }}">
<header class="border-b pb-3 text-center"><h1 class="font-bold">{{ str_starts_with(app()->getLocale(), 'ar') ? $template->name_ar : $template->name_en }}</h1><p class="text-xs">{{ $template->header_text }}</p></header>
<section class="space-y-2 py-4 text-sm"><div class="flex justify-between"><span>{{ __('Document type') }}</span><span>{{ __(Illuminate\Support\Str::headline($template->document_type)) }}</span></div><div class="flex justify-between"><span>{{ __('Paper size') }}</span><span>{{ __(strtoupper($template->paper_size)) }}</span></div><div class="flex justify-between"><span>{{ __('Language') }}</span><span>{{ __($template->language) }}</span></div><div class="border-y border-dashed py-4 text-center">{{ __('Sample document content — no customer, payment, or production data is used.') }}</div></section>
<footer class="border-t pt-3 text-center text-xs">{{ $template->footer_text }}</footer>
</main></body></html>
