import { chromium } from 'playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const base = 'http://127.0.0.1:8897';
const out = path.resolve('.ai/evidence/v0.1.22-hotfix7');
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: '/home/rajeh_ahmed/.cache/rajeh-v021-hotfix3/chrome', args: ['--no-sandbox'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'ar-EG' });
const page = await context.newPage();
const errors = [];
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('pageerror', error => errors.push(error.message));
await page.goto(base + '/login');
await page.locator('[name=username]').fill('admin');
await page.locator('[name=password]').fill('Disposable-Hotfix7-Only-937!');
await Promise.all([page.waitForURL(url => !url.pathname.endsWith('/login')), page.locator('[data-test="login-button"]').click()]);
const setLocale = async locale => {
  const token = await page.locator('meta[name=csrf-token]').getAttribute('content');
  await context.request.post(base + '/locale', { form: { _token: token, locale } });
};
const inspect = async (url, expected, screenshot) => {
  await page.goto(base + url, { waitUntil: 'networkidle' });
  const body = await page.locator('body').innerText();
  if (!expected.some(text => body.includes(text))) throw new Error(`expected content absent at ${url}`);
  const metrics = await page.evaluate(() => ({ width: innerWidth, overflow: document.documentElement.scrollWidth > innerWidth + 1, title: document.title }));
  if (metrics.overflow) throw new Error(`horizontal overflow at ${url}: ${JSON.stringify(metrics)}`);
  if (screenshot) await page.screenshot({ path: path.join(out, screenshot), fullPage: true });
  return metrics;
};
await setLocale('ar');
const ar = {};
ar.balances = await inspect('/inventory/balances', ['أرصدة المخزون', 'الأرصدة'], 'arabic-balances-desktop.png');
ar.stores = await inspect('/admin/stores', ['المخازن ومنافذ البيع', 'المخازن'], 'arabic-stores-desktop.png');
const nav = await page.evaluate(() => ({ count: [...document.querySelectorAll('a')].filter(a => a.textContent.includes('المخازن ومنافذ البيع')).length, active: [...document.querySelectorAll('a[aria-current="page"]')].some(a => a.textContent.includes('المخازن ومنافذ البيع')) }));
ar.countCreate = await inspect('/inventory/counts/create', ['جلسة', 'الجرد'], 'arabic-count-create-desktop.png');
ar.countEntry = await inspect('/inventory/counts/1/entry', ['الجرد', 'العد'], 'arabic-count-entry-desktop.png');
await setLocale('en');
const en = {};
en.balances = await inspect('/inventory/balances', ['Inventory balances', 'Balances']);
en.stores = await inspect('/admin/stores', ['Warehouses & Sales Outlets', 'Warehouses']);
en.countCreate = await inspect('/inventory/counts/create', ['count session', 'Count session', 'Stock count']);
await setLocale('ar');
await page.setViewportSize({ width: 390, height: 844 });
const mobile = {};
mobile.balances = await inspect('/inventory/balances', ['الأرصدة', 'المخزون'], 'arabic-balances-mobile.png');
mobile.countCreate = await inspect('/inventory/counts/create', ['جلسة', 'الجرد'], 'arabic-count-create-mobile.png');
if (errors.length) throw new Error(`browser errors: ${JSON.stringify(errors)}`);
const result = { database: 'toyjoy_hotfix7_verify', ar, en, mobile, nav, consoleErrors: errors, horizontalOverflow: false };
writeFileSync(path.join(out, 'runtime-verification.json'), JSON.stringify(result, null, 2) + '\n');
await browser.close();
console.log(JSON.stringify(result));
