import { chromium } from 'playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
const base='http://127.0.0.1:8788',out=path.resolve('.ai/evidence/v0.1.22-hotfix4');mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/home/rajeh_ahmed/.cache/rajeh-v021-hotfix3/chrome',args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ar-EG'}),page=await context.newPage(),errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/login');await page.locator('[name=username]').fill('admin');await page.locator('[name=password]').fill('Hotfix4!Verify#2026');await Promise.all([page.waitForURL(u=>!u.pathname.endsWith('/login')),page.locator('[data-test="login-button"]').click()]);
const token=async()=>page.locator('meta[name=csrf-token]').getAttribute('content');await context.request.post(base+'/locale',{form:{_token:await token(),locale:'ar'}});
const checks=[];async function check(name,url){let r=await page.goto(base+url,{waitUntil:'networkidle'});let x=await page.evaluate(()=>({text:document.body.innerText,overflow:document.documentElement.scrollWidth>innerWidth+1}));if(!r.ok()||x.overflow||/(Purchase_distribution|purchase_distribution|purchase_receipt_reversal|(?:^|\s)-?\d+\.0{3,6}(?:\s|$))/m.test(x.text))throw Error(name);await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});checks.push({name,status:r.status(),overflow:x.overflow});return x.text}
await check('dashboard-ar','/dashboard');await check('movements-ar','/inventory/movements');await check('balances-ar','/inventory/balances');await check('transfers-ar','/inventory/transfers');await check('counts-ar','/inventory/counts');
await page.goto(base+'/pricing/labels',{waitUntil:'networkidle'});if(await page.locator('[data-label-product]').count())throw Error('initial products loaded');await page.locator('#product-search').fill('H4-');await page.waitForTimeout(500);await page.locator('section button').filter({hasText:'H4-CODE128'}).click();await page.locator('section button').filter({hasText:'H4-EAN13'}).click();if(await page.locator('article').count()!==2)throw Error('multi selection');await page.locator('#product-search').fill('4006381333931');await page.locator('#product-search').press('Enter');await page.waitForTimeout(300);if(await page.locator('article').count()!==2)throw Error('duplicate scanner selection');await page.screenshot({path:path.join(out,'labels-multiselect-ar.png'),fullPage:true});
await page.locator('#product-search').fill('H4-NOBAR');await page.waitForTimeout(500);await page.locator('section button').filter({hasText:'H4-NOBAR'}).click();if(!await page.getByText('لا يمكن طباعة هذا المنتج حتى تتم إضافة باركود نشط.').isVisible())throw Error('barcode remediation');
let unpriced=await check('unpriced-ar','/pricing/unpriced');if(unpriced.includes('H4-CODE128')||unpriced.includes('H4-EAN13'))throw Error('positive base price remains unpriced');await check('pos-ar','/pos');await page.locator('#live-pos-product-search').fill('H4-CODE128');await page.waitForTimeout(600);let card=page.locator('[data-product-family]').filter({hasText:'H4-CODE128'}),pos=await card.innerText();if(!/(25[.,]00|٢٥[٫،]٠٠)/.test(pos))throw Error('POS did not use base 25.00: '+pos);if(await card.getByRole('button').isDisabled())throw Error('base price product was not sellable');await page.screenshot({path:path.join(out,'pos-base-price-25-ar.png'),fullPage:true});
await page.goto(base+'/inventory/balances',{waitUntil:'networkidle'});for(let s of await page.locator('.app-navigation__group summary').all())await s.click().catch(()=>{});let side=await page.evaluate(()=>{let e=document.querySelector('.app-sidebar'),n=document.querySelector('.app-navigation'),s=getComputedStyle(n);scrollTo(0,document.documentElement.scrollHeight);return{overflowY:s.overflowY,sticky:getComputedStyle(e).position,groups:document.body.innerText.includes('مجموعات العملاء')}});if(side.overflowY==='auto'||side.overflowY==='scroll'||side.sticky!=='sticky'||!side.groups)throw Error('sidebar '+JSON.stringify(side));await page.screenshot({path:path.join(out,'sidebar-long-expanded-ar.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});await page.goto(base+'/inventory/balances',{waitUntil:'networkidle'});await page.getByLabel('فتح قائمة التنقل').click({force:true});await page.waitForTimeout(250);let mobile=await page.evaluate(()=>({visible:document.querySelector('.app-sidebar').getBoundingClientRect().width>0,overflow:document.documentElement.scrollWidth>innerWidth+1}));if(!mobile.visible||mobile.overflow)throw Error('mobile drawer');await page.screenshot({path:path.join(out,'mobile-drawer-ar.png')});
const ids=await context.request.get(base+'/pricing/labels/search?q=H4-CODE128').then(r=>r.json());const ean=await context.request.get(base+'/pricing/labels/search?q=H4-EAN13').then(r=>r.json());const pdfs=[];for(const [name,p] of [['code128',ids.data[0]],['ean13',ean.data[0]]]){let b=p.barcodes[0];await context.request.post(base+'/pricing/labels/preview',{form:{_token:await token(),'products[0][selected]':'1','products[0][product_id]':String(p.id),'products[0][barcode_id]':String(b.id),'products[0][copies]':'1'}});let r=await context.request.get(base+'/pricing/labels/download'),bytes=await r.body();if(r.status()!==200||bytes.subarray(0,4).toString()!=='%PDF')throw Error(name+' pdf');writeFileSync(path.join(out,name+'.pdf'),bytes);pdfs.push({name,status:r.status(),bytes:bytes.length,signature:'%PDF',barcode:b.barcode})}
if(errors.length)throw Error('console '+JSON.stringify(errors));writeFileSync(path.join(out,'runtime-verification.json'),JSON.stringify({database:'rajeh_hotfix4_verify',checks,side,mobile,pdfs,errors},null,2)+'\n');await browser.close();console.log(JSON.stringify({checks:checks.length,pdfs:pdfs.length,errors:errors.length}));
