@props(['dashboard'])

@php
    $isArabic = str_starts_with(app()->getLocale(), 'ar');
    $exceptionTotal = array_sum($dashboard['pricing_exceptions']);
@endphp

<section class="dashboard-kpi-grid" aria-label="{{ $isArabic ? 'مؤشرات التسعير' : 'Pricing indicators' }}">
    <a href="{{ route('pricing.focus', ['mode' => 'versions']) }}" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'قوائم الأسعار النشطة' : 'Active price lists' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['active_lists']) }}</p><p class="dashboard-kpi__state">{{ $dashboard['visible_store_count'] === 1 ? ($isArabic ? 'منفذ البيع الرئيسي' : 'Main selling outlet') : ($isArabic ? $dashboard['visible_store_count'].' منافذ بيع' : $dashboard['visible_store_count'].' selling outlets') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.banknotes class="size-5" /></span></a>
    <a href="{{ route('pricing.focus', ['mode' => 'unpriced']) }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'منتجات بلا سعر بيع أساسي' : 'Products without a base selling price' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['unpriced_products']) }}</p><p class="dashboard-kpi__state">{{ $isArabic ? 'أضف سعر بيع أساسيًا موجبًا لتصبح قابلة للبيع فورًا' : 'Add a positive base selling price to sell immediately' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.exclamation-triangle class="size-5" /></span></a>
    <a href="{{ route('pricing.approvals') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'بانتظار الاعتماد' : 'Awaiting approval' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['pending_approvals']) }}</p><p class="dashboard-kpi__state">{{ $isArabic ? 'نسخ أسعار مقدمة' : 'Submitted price versions' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.check-badge class="size-5" /></span></a>
    <a href="#scheduled-prices" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $isArabic ? 'أسعار مجدولة' : 'Scheduled prices' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['scheduled_prices']) }}</p><p class="dashboard-kpi__state">{{ $dashboard['expiring_soon'] }} {{ $isArabic ? 'تنتهي خلال 7 أيام' : 'expire within 7 days' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.calendar-days class="size-5" /></span></a>
</section>

<div class="grid gap-4 lg:grid-cols-12">
    <section class="dashboard-panel lg:col-span-7"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $isArabic ? 'تغطية التسعير الحالية' : 'Current pricing coverage' }}</flux:heading><flux:text size="sm">{{ $dashboard['visible_store_count'] === 1 ? ($isArabic ? 'أسعار البيع المعتمدة والفعالة في منفذ البيع الرئيسي' : 'Approved effective prices for the main selling outlet') : ($isArabic ? 'أسعار البيع المعتمدة والفعالة لمنافذ البيع' : 'Approved effective prices for selling outlets') }}</flux:text></div><flux:icon.chart-bar class="size-5 text-primary" /></header><div class="grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-primary-soft p-4"><span class="text-sm text-text-muted">{{ $isArabic ? 'أسعار فعالة' : 'Effective prices' }}</span><strong class="mt-1 block text-2xl tabular-nums">{{ number_format($dashboard['effective_prices']) }}</strong></div><div class="rounded-xl bg-surface-muted p-4"><span class="text-sm text-text-muted">{{ $isArabic ? 'سعر مفتوح مضبوط' : 'Open-price enabled' }}</span><strong class="mt-1 block text-2xl tabular-nums">{{ number_format($dashboard['open_price_lines']) }}</strong></div><div class="rounded-xl bg-surface-muted p-4"><span class="text-sm text-text-muted">{{ $isArabic ? 'استثناءات حتمية' : 'Deterministic exceptions' }}</span><strong class="mt-1 block text-2xl tabular-nums">{{ number_format($exceptionTotal) }}</strong></div></div></section>
    <section class="dashboard-panel lg:col-span-5"><header class="dashboard-panel__header"><flux:heading size="lg">{{ $isArabic ? 'حدود الخصومات والعروض' : 'Discount & promotion boundary' }}</flux:heading><flux:icon.information-circle class="size-5 text-info" /></header><p class="text-sm leading-7 text-text-muted">{{ app()->isLocale('ar-EG') ? 'يدعم النظام حالياً نسخ الأسعار المجدولة، والسعر المفتوح بضوابطه، وخصومات سلة نقطة البيع بصلاحيات مستقلة. مفيش سجلات حملات ترويجية أو قواعد خصم تجارية مستقلة، لذلك لا يعرض القسم ده بيانات غير موجودة.' : ($isArabic ? 'يدعم النظام حالياً نسخ الأسعار المجدولة، والسعر المفتوح بضوابطه، وخصومات سلة نقطة البيع بصلاحيات مستقلة. لا توجد سجلات حملات ترويجية أو قواعد خصم تجارية مستقلة، لذلك لا يعرض هذا القسم بيانات غير موجودة.' : 'The current model supports scheduled price versions, governed open prices, and permission-controlled POS cart discounts. It has no standalone campaign or commercial discount-rule records, so this workspace does not fabricate them.') }}</p></section>
</div>

<div class="grid gap-4 xl:grid-cols-2">
    <section id="scheduled-prices" class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $isArabic ? 'التغييرات المجدولة' : 'Scheduled changes' }}</flux:heading><flux:text size="sm">{{ $isArabic ? 'نسخ معتمدة لم يبدأ سريانها بعد' : 'Approved versions not yet effective' }}</flux:text></div><flux:icon.clock class="size-5 text-primary" /></header><div class="dashboard-list">@forelse($dashboard['scheduled'] as $version)@php($line=$version->lines->first())<a href="{{ route('pricing.focus', ['mode' => 'versions']) }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate">{{ $line?->product?->item_code }} · {{ $isArabic ? $line?->product?->name_ar : $line?->product?->name_en }}</strong><small class="text-text-muted">{{ $line?->store?->code }} · {{ $version->effective_from?->format('Y-m-d H:i') }}</small></span><x-money :amount="$line?->amount" class="font-semibold" /></a>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش أسعار مجدولة' : ($isArabic ? 'لا توجد أسعار مجدولة' : 'No scheduled prices')" icon="calendar-days" />@endforelse</div></section>
    <section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $isArabic ? 'استثناءات التسعير' : 'Pricing exceptions' }}</flux:heading><flux:text size="sm">{{ $isArabic ? 'حالات يمكن اكتشافها من قواعد الأسعار الحالية' : 'Cases deterministically detected from current pricing rules' }}</flux:text></div><flux:icon.exclamation-triangle class="size-5 text-warning" /></header><div class="dashboard-list"><a href="{{ route('pricing.focus', ['mode' => 'history']) }}" class="dashboard-list__row"><span>{{ $isArabic ? 'نسخ معتمدة منتهية' : 'Expired approved versions' }}</span><strong>{{ $dashboard['pricing_exceptions']['expired_approved'] }}</strong></a><a href="{{ route('pricing.focus', ['mode' => 'versions']) }}" class="dashboard-list__row"><span>{{ $isArabic ? 'حدود سعر مفتوح غير مكتملة' : 'Incomplete open-price bounds' }}</span><strong>{{ $dashboard['pricing_exceptions']['invalid_open_bounds'] }}</strong></a></div></section>
</div>

<section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $isArabic ? 'آخر نشاط التسعير' : 'Recent pricing activity' }}</flux:heading><flux:text size="sm">{{ $isArabic ? 'آخر نسخ وتغييرات أسعار منفذ البيع الرئيسي' : 'Latest price versions and changes for the main selling outlet' }}</flux:text></div><flux:icon.clock class="size-5 text-primary" /></header><div class="dashboard-list">@forelse($dashboard['recent_versions'] as $version)@php($line=$version->lines->first())<a href="{{ route('pricing.focus', ['mode' => 'history']) }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate">{{ $version->priceList?->code }} · v{{ $version->version }} · {{ $line?->product?->item_code }}</strong><small class="block truncate text-text-muted">{{ $line?->store?->code }} · {{ $version->updated_at?->format('Y-m-d H:i') }}</small></span><span class="flex items-center gap-3"><x-money :amount="$line?->amount" class="font-semibold" /><x-status.badge :status="$version->state->value" /></span></a>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش نشاط تسعير بعد' : ($isArabic ? 'لا يوجد نشاط تسعير بعد' : 'No pricing activity yet')" icon="banknotes" />@endforelse</div></section>
