@php
    $isArabic = str_starts_with(app()->getLocale(), 'ar');
    $t = static fn (string $ar, string $en): string => $isArabic ? $ar : $en;
    $status = static fn (?string $value): string => \App\Modules\Platform\Support\UiLabel::status($value);
    $movementLabel = static fn (?string $value): string => \App\Modules\Inventory\Support\InventoryMovementLabel::label($value);
    $field = 'mt-1 min-h-11 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5 text-sm text-zinc-900 shadow-sm dark:border-zinc-600 dark:bg-zinc-900 dark:text-zinc-100';
    $button = 'rounded-xl px-3 py-2 text-xs font-bold transition focus:outline-none focus:ring-2 focus:ring-sky-500';
    $isBalancesFocus = $focus === 'balances';
    $isFocusedRegister = in_array($focus, ['balances', 'counts', 'transfers'], true);
    $pageTitle = match ($focus) {
        'balances' => $t('أرصدة المخزون الحالية', 'Current stock balances'),
        'counts' => $t('الجرد الفعلي ومراجعة الفروقات', 'Physical counts and variance review'),
        'transfers' => $t('نقل المخزون بين المواقع', 'Stock transfers between locations'),
        default => $t('المخزون', 'Inventory'),
    };
    $inventoryRoute = $isBalancesFocus ? 'inventory.balances' : ($focus === 'movements' ? 'inventory.movements' : 'inventory.index');
    $movementTypes = \App\Modules\Inventory\Support\InventoryMovementLabel::options();
    $qty = static fn ($value): string => \App\Support\ProductQuantity::format($value);
@endphp

<x-layouts.app :title="$pageTitle">
    <div class="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8" data-inventory-demo data-inventory-focus="{{ $focus ?: 'workspace' }}">
        @if($isBalancesFocus)
            <header class="border-b border-border pb-5" data-guide="inventory-hero"><h1 class="text-2xl font-bold tracking-tight text-text-primary sm:text-3xl">{{ $pageTitle }}</h1><p class="mt-1 max-w-3xl text-sm text-text-muted">{{ $t('اعرف الموجود والمتاح لكل صنف في كل مخزن أو منفذ بيع. هذه صفحة استعلام، وليست شاشة إدخال أو تعديل كميات.', 'See on-hand and available quantities by product and location. This is a lookup, not a quantity-entry or adjustment screen.') }}</p></header>
        @elseif($focus === 'transfers')
        <header class="flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-2xl font-bold">{{ $pageTitle }}</h1><p class="mt-1 max-w-3xl text-sm text-text-muted">{{ $t('انقل أصنافًا من مخزن أو منفذ إلى آخر، وتابع الإرسال والاستلام الفعلي وأي عجز أو تلف.', 'Move stock from one location to another and track dispatch, actual receipt, shortage or damage.') }}</p></div>@can('transfers.create')<flux:button :href="route('inventory.transfers.create')" variant="primary" icon="arrows-right-left">{{ $t('إنشاء تحويل بين موقعين', 'Create location transfer') }}</flux:button>@endcan</header>
        @elseif($focus === 'counts')
        <header class="flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-2xl font-bold">{{ $pageTitle }}</h1><p class="mt-1 max-w-3xl text-sm text-text-muted">{{ $t('عدّ الموجود على أرض الواقع، ثم راجع الفرق بين المعدود والمسجل قبل اعتماد المطابقة. الجرد لا ينقل أصنافًا بين المواقع.', 'Count what physically exists, then review differences against system quantities before reconciliation. Counting does not transfer stock between locations.') }}</p></div>@can('stock_counts.create')<flux:button :href="route('inventory.counts.create')" variant="primary" icon="clipboard-document-list">{{ $t('بدء جلسة جرد', 'Start stock count') }}</flux:button>@endcan</header>
        @else
        <header class="flex flex-col gap-3 border-b border-border pb-5 md:flex-row md:items-end md:justify-between" data-guide="inventory-hero">
            <div><h1 class="text-2xl font-bold tracking-tight text-text-primary sm:text-3xl">{{ $t('المخزون', 'Inventory') }}</h1><p class="mt-1 max-w-3xl text-sm text-text-muted">{{ $t('تابع الرصيد والحركة والتحويل والجرد ضمن نطاقك.', 'Track balances, movements, transfers, and counts within your scope.') }}</p></div>
            <div class="flex w-full flex-wrap gap-2 md:w-auto md:justify-end">
                @can('transfers.create')<a href="{{ route('inventory.transfers.create') }}" class="{{ $button }} bg-sky-700 text-white">{{ $t('تحويل جديد', 'New transfer') }}</a>@endcan
                @can('inventory_stock_card.create')<a href="{{ route('inventory.adjustments.create') }}" class="{{ $button }} border border-zinc-300 text-zinc-800 dark:border-zinc-700 dark:text-zinc-100">{{ $t('مستند حركة', 'New movement') }}</a>@endcan
                @can('stock_counts.create')<a href="{{ route('inventory.counts.create') }}" class="{{ $button }} border border-zinc-300 text-zinc-800 dark:border-zinc-700 dark:text-zinc-100">{{ $t('جرد جديد', 'New count') }}</a>@endcan
            </div>
        </header>
        @endif

        @if($isFocusedRegister)
            <nav class="flex flex-wrap gap-2 border-b border-border pb-3" aria-label="{{ $t('وظائف المخزون', 'Inventory tasks') }}">
                <a href="{{ route('inventory.balances') }}" @if($focus === 'balances') aria-current="page" @endif @class([$button, 'bg-primary-soft text-primary' => $focus === 'balances', 'text-text-muted hover:bg-surface-muted' => $focus !== 'balances'])>{{ $t('الأرصدة: ماذا يوجد؟', 'Balances: what is in stock?') }}</a>
                @can('inventory_stock_card.view')<a href="{{ route('inventory.counts') }}" @if($focus === 'counts') aria-current="page" @endif @class([$button, 'bg-primary-soft text-primary' => $focus === 'counts', 'text-text-muted hover:bg-surface-muted' => $focus !== 'counts'])>{{ $t('الجرد: هل الكمية صحيحة؟', 'Counts: is the quantity correct?') }}</a>@endcan
                @can('transfers.view')<a href="{{ route('inventory.transfers') }}" @if($focus === 'transfers') aria-current="page" @endif @class([$button, 'bg-primary-soft text-primary' => $focus === 'transfers', 'text-text-muted hover:bg-surface-muted' => $focus !== 'transfers'])>{{ $t('التحويلات: نقل بين المواقع', 'Transfers: move between locations') }}</a>@endcan
            </nav>
            @if($focus === 'counts')
                <div class="space-y-2 text-sm" role="note"><h2 class="font-bold">{{ $t('مسار الجرد', 'Count workflow') }}</h2><p class="text-text-muted">{{ $t('ابدأ جلسة وحدد النطاق والفريق، أدخل العد الفعلي، ثم أرسل للمراجعة والمطابقة.', 'Start a session and choose its scope and team, enter physical counts, then submit for review and reconciliation.') }}</p><p class="text-text-muted">{{ $t('البيع يستمر أثناء الجرد. الأصناف التي لم تُعدّ لا تُصفّر تلقائيًا، والفروقات لا تُرحّل إلا عبر المطابقة المعتمدة.', 'Sales continue during counting. Uncounted products are never automatically zeroed; differences are posted only through approved reconciliation.') }}</p></div>
            @elseif($focus === 'transfers')
                <div class="space-y-2 text-sm" role="note"><h2 class="font-bold">{{ $t('مسار نقل البضاعة', 'Stock movement workflow') }}</h2><p class="text-text-muted">{{ $t('حدد المصدر والوجهة والأصناف، أرسل للمراجعة والاعتماد، ثم سجّل الإرسال من المصدر والاستلام في الوجهة.', 'Choose source, destination and products, submit for approval, then dispatch from the source and record destination receipt.') }}</p><p class="text-text-muted">{{ $t('الاعتماد وحده لا يجعل البضاعة متاحة في الوجهة. تظل الكميات المرسلة قيد النقل حتى تأكيد الاستلام الفعلي.', 'Approval alone does not make stock available at the destination. Dispatched quantities remain in transit until actual receipt is recorded.') }}</p></div>
            @endif
        @endif

        @if($focus === null)
        <section class="space-y-3" aria-labelledby="inventory-overview-heading">
            <div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-semibold text-primary">{{ $t('لوحة الوحدة', 'Module dashboard') }}</p><h2 id="inventory-overview-heading" class="mt-1 text-xl font-bold">{{ $t('نظرة تشغيلية على المخزون', 'Inventory operational overview') }}</h2><p class="mt-1 text-sm text-text-muted">{{ $t('مؤشرات المخزون في المخزن الرئيسي ومنفذ البيع الرئيسي.', 'Inventory indicators for the main warehouse and main selling outlet.') }}</p></div><div class="module-quick-actions">
                <flux:button :href="route('inventory.balances')" size="sm" variant="subtle" icon="archive-box" wire:navigate>{{ $t('الأرصدة', 'Balances') }}</flux:button>
                <flux:button :href="route('inventory.movements')" size="sm" variant="subtle" icon="queue-list" wire:navigate>{{ $t('الحركات', 'Movements') }}</flux:button>
                @can('transfers.view')<flux:button :href="route('inventory.transfers')" size="sm" variant="subtle" icon="arrows-right-left" wire:navigate>{{ $t('التحويلات', 'Transfers') }}</flux:button>@endcan
                <flux:button :href="route('inventory.counts')" size="sm" variant="subtle" icon="clipboard-document-list" wire:navigate>{{ $t('الجرد', 'Counts') }}</flux:button>
                <flux:button :href="route('inventory.adjustments')" size="sm" variant="subtle" icon="adjustments-horizontal" wire:navigate>{{ $t('التسويات', 'Adjustments') }}</flux:button>
                @can('pricing_labels.view')<flux:button :href="route('pricing.labels')" size="sm" variant="subtle" icon="qr-code" wire:navigate>{{ $t('الباركود', 'Barcodes') }}</flux:button>@endcan
            </div></div>
            <div class="module-overview-grid" tabindex="0" aria-label="{{ $t('مؤشرات المخزون، مرر أفقياً على الشاشات الصغيرة', 'Inventory indicators; scroll horizontally on small screens') }}">
                <a href="{{ route('catalog.products') }}" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $t('المنتجات والمتغيرات النشطة', 'Active products & variants') }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $inventoryOverview['active_products'] + $inventoryOverview['active_variants'] }}</p><p class="dashboard-kpi__state">{{ $inventoryOverview['active_products'] }} {{ $t('منتج', 'products') }} · {{ $inventoryOverview['active_variants'] }} {{ $t('متغير', 'variants') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.cube-transparent class="size-5" /></span></a>
                <a href="{{ route('inventory.balances') }}" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $t('المنتجات المرئية', 'Visible products') }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $inventoryOverview['visible_products'] }}</p><p class="dashboard-kpi__state">{{ $t('لها رصيد ضمن النطاق', 'with balances in scope') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.cube class="size-5" /></span></a>
                <a href="{{ route('inventory.balances') }}" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $t('إجمالي الرصيد الفعلي', 'Total stock on hand') }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $qty($inventoryOverview['stock_on_hand']) }}</p><p class="dashboard-kpi__state">{{ $t('عبر المتاجر المرئية', 'across visible stores') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.archive-box class="size-5" /></span></a>
                @if($inventoryOverview['inventory_value'] !== null)<a href="{{ route('inventory.balances') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('قيمة المخزون', 'Inventory value') }}</p><p class="dashboard-kpi__value" dir="ltr"><x-money :amount="$inventoryOverview['inventory_value']" currency="EGP" /></p><p class="dashboard-kpi__state">{{ $t('من قيمة الأرصدة المعتمدة', 'authoritative balance value') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.banknotes class="size-5" /></span></a>@endif
                <a href="{{ route('inventory.balances') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('منخفض المخزون', 'Low stock') }}</p><p class="dashboard-kpi__value text-amber-700" dir="ltr">{{ $inventoryOverview['low_stock'] }}</p><p class="dashboard-kpi__state">{{ $t('من وحدة إلى خمس', 'one to five available') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.exclamation-triangle class="size-5" /></span></a>
                <a href="{{ route('inventory.balances') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('نافد المخزون', 'Out of stock') }}</p><p class="dashboard-kpi__value text-rose-700" dir="ltr">{{ $inventoryOverview['out_of_stock'] }}</p><p class="dashboard-kpi__state">{{ $t('المتاح صفر أو أقل', 'zero or less available') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.archive-box-x-mark class="size-5" /></span></a>
                <a href="{{ route('inventory.balances', ['stock_state' => 'negative']) }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('رصيد سالب', 'Negative stock') }}</p><p class="dashboard-kpi__value text-rose-700" dir="ltr">{{ $inventoryOverview['negative_stock'] }}</p><p class="dashboard-kpi__state">{{ $t('استثناء يتطلب المراجعة', 'exception requiring review') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.exclamation-circle class="size-5" /></span></a>
                <a href="{{ route('inventory.movements') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('حركات اليوم', "Today's movements") }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $inventoryOverview['today_movements'] }}</p><p class="dashboard-kpi__state">{{ $t('حركات مخزون مرحلة', 'posted stock movements') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.queue-list class="size-5" /></span></a>
                <a href="{{ route('catalog.products') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('بيانات كتالوج ناقصة', 'Catalog exceptions') }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $inventoryOverview['missing_barcodes'] + $inventoryOverview['missing_catalog_data'] }}</p><p class="dashboard-kpi__state">{{ $inventoryOverview['missing_barcodes'] }} {{ $t('دون باركود', 'without barcode') }} · {{ $inventoryOverview['missing_catalog_data'] }} {{ $t('بيانات ناقصة', 'missing data') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.qr-code class="size-5" /></span></a>
                @can('transfers.view')<a href="{{ route('inventory.transfers') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('تحويلات معلقة', 'Pending transfers') }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $inventoryOverview['pending_transfers'] }}</p><p class="dashboard-kpi__state">{{ $t('قبل الإغلاق النهائي', 'before final completion') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.arrows-right-left class="size-5" /></span></a>@endcan
                <a href="{{ route('inventory.counts') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('جرد نشط', 'Active counts') }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $inventoryOverview['active_counts'] }}</p><p class="dashboard-kpi__state">{{ $t('مسودة أو قيد التنفيذ', 'draft, active, or submitted') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.clipboard-document-list class="size-5" /></span></a>
                <a href="{{ route('inventory.adjustments') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $t('تسويات معلقة', 'Pending adjustments') }}</p><p class="dashboard-kpi__value" dir="ltr">{{ $inventoryOverview['pending_adjustments'] }}</p><p class="dashboard-kpi__state">{{ $t('مسودة أو مقدمة', 'draft or submitted') }}</p></div><span class="dashboard-kpi__icon"><flux:icon.adjustments-horizontal class="size-5" /></span></a>
            </div>
            <div class="grid gap-4 lg:grid-cols-2">
                <section class="dashboard-panel"><header class="dashboard-panel__header"><flux:heading size="lg">{{ $t('توزيع المخزون حسب الموقع', 'Stock distribution by location') }}</flux:heading><flux:icon.building-storefront class="size-5 text-primary" /></header><div class="dashboard-list">@forelse($inventoryOverview['stock_distribution'] as $store)<a href="{{ route('inventory.balances', ['store_id' => $store->id]) }}" class="dashboard-list__row"><span><strong class="block">{{ $store->code }}</strong><small class="text-text-muted">{{ $isArabic ? $store->name_ar : ($store->name_en ?: $store->name_ar) }}</small></span><strong class="tabular-nums">{{ $qty($store->on_hand) }}</strong></a>@empty<x-state.empty :title="$t('لا توجد أرصدة موزعة', 'No distributed balances')" icon="archive-box" />@endforelse</div></section>
                <section class="dashboard-panel"><header class="dashboard-panel__header"><flux:heading size="lg">{{ $t('المنتجات الأعلى حركة خلال 7 أيام', 'Top-moving products · 7 days') }}</flux:heading><flux:icon.arrow-trending-up class="size-5 text-primary" /></header><div class="dashboard-list">@forelse($inventoryOverview['top_moving_products'] as $product)<a href="{{ route('inventory.stock-card', $product->id) }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate">{{ $isArabic ? $product->name_ar : ($product->name_en ?: $product->name_ar) }}</strong><small class="font-mono text-text-muted">{{ $product->item_code }}</small></span><strong class="tabular-nums">{{ $qty($product->moved_quantity) }}</strong></a>@empty<x-state.empty :title="$t('لا توجد حركات خلال الفترة', 'No movements in this period')" icon="queue-list" />@endforelse</div></section>
            </div>
        </section>
        @endif

        @if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{{ session('success') }}</div>@endif
        @if(session('error'))<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert">{{ session('error') }}</div>@endif
        @if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert"><p class="font-bold">{{ $t('تعذر حفظ الجرد. راجع البيانات التالية:', 'The count could not be saved. Review the following:') }}</p><ul class="mt-2 list-disc space-y-1 ps-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @if($errors->any())<div class="rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        @if(in_array($focus, [null, 'balances', 'movements', 'stock-card'], true))
        <section class="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-900" aria-labelledby="inventory-filters-heading">
            <div class="mb-4 flex flex-col gap-3 border-b border-zinc-200 pb-3 dark:border-zinc-800 md:flex-row md:items-center md:justify-between"><div><h2 id="inventory-filters-heading" class="text-base font-bold text-text-primary">{{ $t('تصفية العرض', 'Filter inventory') }}</h2><p class="mt-1 text-sm text-text-muted">{{ $t('حدّد المنتج أو موقع المخزون أو نوع الحركة.', 'Narrow results by product, stock location, or movement type.') }}</p></div></div>
            <form method="GET" action="{{ route($inventoryRoute) }}" class="grid min-w-0 items-end gap-4 md:grid-cols-2 xl:grid-cols-3" data-inventory-filter>
                <div><label for="inventory-q" class="text-xs font-semibold">{{ $t('بحث عن منتج', 'Product search') }}</label><input id="inventory-q" name="q" value="{{ $search }}" placeholder="{{ $t('اسم أو كود أو باركود', 'Name, item code, or barcode') }}" class="{{ $field }}"></div>
                <label class="flex min-h-10 items-center gap-2 rounded-xl border border-zinc-200 px-3 text-sm dark:border-zinc-700"><input type="checkbox" name="include_zero" value="1" @checked($includeZero)><span>{{ $t('إظهار المواقع ذات الرصيد الصفري', 'Include zero-balance locations') }}</span></label>
                <div><label for="inventory-store" class="text-xs font-semibold">{{ $t('موقع المخزون', 'Stock location') }}</label><select id="inventory-store" name="store_id" class="{{ $field }}"><option value="">{{ $t('كل مواقع المخزون', 'All stock locations') }}</option>@foreach($visibleStores as $store)<option value="{{ $store->id }}" @selected($filterStoreId === $store->id)>{{ $store->code }} · {{ $isArabic ? $store->name_ar : $store->name_en }}</option>@endforeach</select></div>
                <div><label for="inventory-stock-state" class="text-xs font-semibold">{{ $t('حالة المخزون', 'Stock state') }}</label><select id="inventory-stock-state" name="stock_state" class="{{ $field }}"><option value="">{{ $t('كل الحالات', 'All states') }}</option><option value="available" @selected($stockState === 'available')>{{ $t('متاح', 'Available') }}</option><option value="low" @selected($stockState === 'low')>{{ $t('منخفض', 'Low stock') }}</option><option value="out" @selected($stockState === 'out')>{{ $t('نافد', 'Out of stock') }}</option><option value="negative" @selected($stockState === 'negative')>{{ $t('سالب', 'Negative') }}</option></select></div>
                @unless($isBalancesFocus)
                <div><label for="inventory-movement-type" class="text-xs font-semibold">{{ $t('نوع الحركة', 'Movement type') }}</label><select id="inventory-movement-type" name="movement_type" class="{{ $field }}"><option value="">{{ $t('كل أنواع الحركة', 'All movement types') }}</option>@foreach($movementTypes as $type)<option value="{{ $type }}" @selected($movementType === $type)>{{ $movementLabel($type) }}</option>@endforeach</select></div>
                @endunless
                <div class="flex flex-wrap justify-end gap-2 border-t border-border pt-3 md:col-span-2 xl:col-span-3"><button type="submit" class="{{ $button }} min-h-11 min-w-24 bg-primary text-white">{{ $t('تطبيق الفلاتر', 'Apply filters') }}</button><a href="{{ route($inventoryRoute) }}" class="{{ $button }} inline-flex min-h-11 items-center justify-center border border-zinc-300 text-center dark:border-zinc-700">{{ __('Reset filters') }}</a></div>
            </form>
        </section>
        @endif

        @if($focus === null)
        <dl class="grid divide-y divide-zinc-200 rounded-2xl border border-zinc-200 bg-white dark:divide-zinc-800 dark:border-zinc-800 dark:bg-zinc-900 sm:grid-cols-2 sm:divide-y-0 xl:grid-cols-5" data-guide="inventory-summary">
            @foreach([[$t('الأرصدة', 'Balances'), $inventorySummary['balances']], [$t('الحركات', 'Movements'), $inventorySummary['movements']], [$t('التحويلات', 'Transfers'), $inventorySummary['transfers']], [$t('التسويات', 'Adjustments'), $inventorySummary['adjustments']], [$t('خطط الجرد', 'Stock counts'), $inventorySummary['counts']]] as [$label, $value])<div @class(['flex items-baseline justify-between gap-3 px-4 py-3', 'xl:border-s xl:border-zinc-200 xl:dark:border-zinc-800' => ! $loop->first])><dt class="text-sm text-text-muted">{{ $label }}</dt><dd class="font-mono text-lg font-bold text-text-primary">{{ $value }}</dd></div>@endforeach
        </dl>
        @endif

        @if(in_array($focus, [null, 'balances', 'stock-card'], true))
        <section class="rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900" aria-labelledby="balances-heading" data-guide="inventory-balances">
            <div class="border-b border-zinc-200 px-5 py-4 dark:border-zinc-800"><h2 id="balances-heading" class="text-lg font-bold">{{ $t('الأرصدة المتاحة وإعادة الطلب', 'Available balances and reorder') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ $t('التوفر = الرصيد الفعلي ناقص المحجوز. الكميات قيد النقل منفصلة حتى الاستلام.', 'Available = on-hand minus reserved. In-transit remains separate until receipt.') }}</p><p class="mt-2 text-xs font-semibold text-sky-700">{{ $t('الاستعلام عبر الفروع للمعلومة فقط ولا يغير متجر البيع أو السلة.', 'Cross-branch lookup is informational only and never changes the selling store or cart.') }}</p></div>
            <x-tables.table-shell :label="$t('أرصدة المخزون', 'Inventory balances')"><div class="overflow-x-auto"><table class="data-table responsive-resource-table w-full text-start text-sm" data-stock-balance-table><thead><tr><th>{{ $t('المنتج', 'Product') }}</th><th>{{ $t('موقع المخزون', 'Stock location') }}</th><th>{{ $t('الرصيد المسجل', 'Recorded on-hand') }}</th><th>{{ $t('محجوز', 'Reserved') }}</th><th>{{ $t('متاح', 'Available') }}</th><th>{{ $t('قيد النقل', 'In transit') }}</th>@if($canViewCost)<th>{{ $t('التكلفة', 'Cost') }}</th>@endif<th>{{ $t('إعادة الطلب', 'Reorder') }}</th></tr></thead><tbody>
                @forelse($balances as $balance)
                    @php $available = (float) $balance->on_hand - (float) $balance->reserved; $reorder = (float) ($balance->product?->reorder_threshold ?? 0); $branch = $balance->store?->branch; @endphp
                    <tr data-stock-balance-row><td data-primary><strong>{{ \App\Support\HumanName::name($balance->product) }}</strong><div class="text-xs text-zinc-500" dir="ltr">{{ $balance->product?->item_code }} @if($balance->product?->model_number)· {{ $balance->product->model_number }}@endif @if($balance->product?->barcodes->first())· {{ $balance->product->barcodes->first()->barcode }}@endif</div></td><td data-label="{{ $t('الموقع والفرع', 'Location and branch') }}">@can('branches_stores.view')<a class="font-bold text-primary" href="{{ route('admin.stores',['search'=>$balance->store?->code]) }}">{{ \App\Support\HumanName::name($balance->store) }}</a>@else<span class="font-bold">{{ \App\Support\HumanName::name($balance->store) }}</span>@endcan<div class="text-xs text-zinc-500" dir="ltr">{{ $balance->store?->code }}</div><div class="text-xs">{{ $balance->store?->type==='selling'?$t('منفذ بيع','Sales outlet'):$t('مخزن','Warehouse') }} · {{ $t('الفرع','Branch') }}: {{ \App\Support\HumanName::name($branch) }} <small dir="ltr">{{ $branch?->code }}</small></div></td><td data-label="{{ $t('الرصيد المسجل', 'Recorded on-hand') }}" class="font-mono" dir="ltr">{{ $qty($balance->on_hand) }}</td><td data-label="{{ $t('محجوز', 'Reserved') }}" class="font-mono" dir="ltr">{{ $qty($balance->reserved) }}</td><td data-label="{{ $t('متاح', 'Available') }}" class="font-mono font-bold {{ $available <= $reorder ? 'text-rose-700' : 'text-emerald-700' }}" dir="ltr">{{ $qty($available) }}</td><td data-label="{{ $t('قيد النقل', 'In transit') }}" class="font-mono" dir="ltr">{{ $qty($balance->in_transit) }}</td>@if($canViewCost)<td data-label="{{ $t('التكلفة', 'Cost') }}"><x-money :amount="$balance->average_cost" currency="EGP" /></td>@endif<td data-label="{{ $t('إعادة الطلب', 'Reorder') }}" class="font-mono" dir="ltr">{{ $available <= $reorder ? $t('مطلوب','Required') : $t('سليم','Healthy') }} · {{ $qty($reorder) }}</td></tr>
                @empty<tr><td colspan="{{ $canViewCost ? 8 : 7 }}" class="px-5 py-10 text-center text-zinc-500">{{ $t('لا توجد أرصدة ضمن النطاق.', 'No balances in this scope.') }}</td></tr>@endforelse
            </tbody></table></div><div class="border-t border-zinc-200 px-5 py-3"><x-tables.pagination :paginator="$balances" :page-sizes="[25]" /></div></x-tables.table-shell>
        </section>

        @endif
        @unless($isBalancesFocus)
        @if($focus === 'transfer-create' || $transfer?->status === 'draft')
            <section class="rounded-3xl border border-sky-200 bg-gradient-to-br from-sky-50 via-white to-indigo-50/70 p-5 shadow-sm dark:border-sky-800 dark:from-sky-950/30 dark:via-zinc-900 dark:to-indigo-950/20 sm:p-6" aria-labelledby="transfer-editor-heading">
                <div class="flex flex-col gap-2 border-b border-sky-200/80 pb-4 dark:border-sky-800/70 sm:flex-row sm:items-start sm:justify-between">
                    <div>
                        <h2 id="transfer-editor-heading" class="text-xl font-bold text-sky-950 dark:text-sky-100">{{ $transfer ? $t('تعديل تحويل مسودة', 'Edit draft transfer') : $t('إنشاء تحويل مخزون', 'Create stock transfer') }}</h2>
                        <p class="mt-1 text-sm leading-6 text-sky-800/80 dark:text-sky-200/80">{{ $t('حدد المتجر المصدر والوجهة، ثم اختر المنتج والكمية لإنشاء مسودة التحويل.', 'Choose the source and destination stores, then select the product and quantity to create the transfer draft.') }}</p>
                    </div>
                    <span class="inline-flex w-fit items-center rounded-full bg-sky-100 px-3 py-1 text-xs font-bold text-sky-800 dark:bg-sky-900/60 dark:text-sky-200">{{ $transfer ? $t('مسودة قيد التعديل', 'Draft in progress') : $t('مسودة جديدة', 'New draft') }}</span>
                </div>
                <form
                    class="mt-4 space-y-4"
                    method="POST"
                    action="{{ $transfer ? route('inventory.transfers.update', $transfer) : route('inventory.transfers.store') }}"
                    x-data="{ attempted: false, source: @js((string) old('source_store_id', $transfer?->source_store_id ?? '')), destination: @js((string) old('destination_store_id', $transfer?->destination_store_id ?? '')) }"
                    x-on:submit="attempted = true; if (!source || !destination || source === destination) { $event.preventDefault(); $refs.destination?.focus(); } else { $el.querySelector('button[type=submit]').disabled = true; }"
                    data-product-line-editor data-autofocus="true" data-next-index="{{ max(1, $transfer?->lines?->count() ?? 1) }}"
                >
                    @csrf
                    <div class="grid gap-4 sm:grid-cols-2">
                        <div class="rounded-2xl border border-sky-200/80 bg-white/75 p-4 shadow-sm dark:border-sky-800/70 dark:bg-zinc-900/60">
                            <label for="transfer-source" class="text-xs font-semibold">{{ $t('موقع المخزون المصدر', 'Source stock location') }}</label>
                            <select id="transfer-source" name="source_store_id" class="{{ $field }}" x-model="source" x-on:invalid="attempted = true" :aria-invalid="attempted && !source ? 'true' : 'false'" aria-describedby="transfer-source-error" required>
                                <option value="" disabled>{{ __('Select source store') }}</option>
                                @foreach($visibleStores as $store)
                                    <option value="{{ $store->id }}">{{ $store->code }}</option>
                                @endforeach
                            </select>
                            <p id="transfer-source-error" class="mt-1 text-xs text-red-700" x-cloak x-show="attempted && !source">{{ __('Select source store') }}</p>
                            @error('source_store_id')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror
                        </div>
                        <div class="rounded-2xl border border-indigo-200/80 bg-white/75 p-4 shadow-sm dark:border-indigo-800/70 dark:bg-zinc-900/60">
                            <label for="transfer-destination" class="text-xs font-semibold">{{ $t('موقع المخزون الوجهة', 'Destination stock location') }}</label>
                            <select id="transfer-destination" name="destination_store_id" class="{{ $field }}" x-ref="destination" x-model="destination" x-on:invalid="attempted = true" :aria-invalid="attempted && (!destination || source === destination) ? 'true' : 'false'" aria-describedby="transfer-destination-error" required>
                                <option value="" disabled>{{ __('Select destination store') }}</option>
                                @foreach($visibleStores as $store)
                                    <option value="{{ $store->id }}">{{ $store->code }}</option>
                                @endforeach
                            </select>
                            <p id="transfer-destination-error" class="mt-1 text-xs text-red-700" x-cloak x-show="attempted && (!destination || source === destination)" x-text="!destination ? @js(__('Select destination store')) : @js(__('Source and destination stores must be different.'))"></p>
                            @error('destination_store_id')<p class="mt-1 text-xs text-red-700">{{ $message }}</p>@enderror
                        </div>
                    </div>
                    <div class="space-y-3">
                        @foreach(($transfer?->lines?->all() ?: [null]) as $lineIndex => $transferLine)
                            <div class="grid gap-3 rounded-2xl border border-zinc-200/80 bg-white/55 p-4 shadow-sm sm:grid-cols-12" data-product-line>
                                <div class="sm:col-span-5"><x-product-line-lookup :name="'lines['.$lineIndex.'][product_id]'" :value="old('lines.'.$lineIndex.'.product_id', $transferLine?->product_id)" :display="$transferLine?->product ? ((str_starts_with(app()->getLocale(), 'ar') ? $transferLine->product->name_ar : $transferLine->product->name_en).' · '.$transferLine->product->item_code) : ''" :label="$t('المنتج', 'Product')" :required="true" /></div>
                                <div class="sm:col-span-3"><label class="text-xs font-semibold">{{ $t('الكمية المطلوبة', 'Requested quantity') }}</label><input data-line-quantity name="lines[{{ $lineIndex }}][quantity_requested]" value="{{ old('lines.'.$lineIndex.'.quantity_requested', $transferLine?->quantity_requested) }}" class="{{ $field }}" inputmode="decimal" min="0.000001" step="0.000001" required></div>
                                <div class="sm:col-span-2"><span class="block text-xs font-semibold">{{ $t('تكلفة الوحدة', 'Unit cost') }}</span><span class="mt-1 flex h-10 items-center rounded-lg bg-zinc-50 px-3">—</span></div>
                                <div class="sm:col-span-2"><span class="block text-xs font-semibold">{{ $t('إجمالي البند', 'Line total') }}</span><span class="mt-1 flex h-10 items-center rounded-lg bg-zinc-50 px-3">—</span></div>
                                @if($lineIndex > 0)<button type="button" data-remove-line class="text-sm text-rose-700 underline">{{ $t('حذف', 'Remove') }}</button>@endif
                            </div>
                        @endforeach
                        <template data-line-template><div class="grid gap-3 rounded-2xl border border-zinc-200/80 bg-white/55 p-4 shadow-sm sm:grid-cols-12" data-product-line><div class="sm:col-span-5"><x-product-line-lookup name="lines[__INDEX__][product_id]" :label="$t('المنتج', 'Product')" :required="true" /></div><div class="sm:col-span-3"><label class="text-xs font-semibold">{{ $t('الكمية المطلوبة', 'Requested quantity') }}</label><input data-line-quantity name="lines[__INDEX__][quantity_requested]" value="1" class="{{ $field }}" inputmode="decimal" min="0.000001" step="0.000001" required></div><div class="sm:col-span-2"><span class="block text-xs font-semibold">{{ $t('تكلفة الوحدة', 'Unit cost') }}</span><span class="mt-1 flex h-10 items-center rounded-lg bg-zinc-50 px-3">—</span></div><div class="sm:col-span-2"><span class="block text-xs font-semibold">{{ $t('إجمالي البند', 'Line total') }}</span><span class="mt-1 flex h-10 items-center rounded-lg bg-zinc-50 px-3">—</span></div><button type="button" data-remove-line class="text-sm text-rose-700 underline">{{ $t('حذف', 'Remove') }}</button></div></template>
                        <button type="button" data-add-line class="text-sm font-semibold text-sky-700 underline">{{ $t('إضافة بند', 'Add item') }}</button>
                    </div>
                    <div><label for="transfer-reason" class="text-xs font-semibold">{{ $t('السبب', 'Reason') }}</label><input id="transfer-reason" name="reason_code" value="{{ old('reason_code', $transfer?->reason_code) }}" class="{{ $field }}" required></div>
                    <button type="submit" x-on:click="attempted = true" class="{{ $button }} min-h-11 px-5 text-sm shadow-sm bg-sky-700 text-white">{{ $t('حفظ المسودة', 'Save draft') }}</button>
                </form>
            </section>
        @endif

        @if($focus === null || str_starts_with((string) $focus, 'transfer'))
        <section class="rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900" aria-labelledby="transfers-heading" data-guide="inventory-transfers"><div class="border-b border-zinc-200 px-5 py-4"><h2 id="transfers-heading" class="text-lg font-bold">{{ $t('التحويلات وفروق الاستلام', 'Transfers and receipt differences') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ $t('أحدث 20 مستند تحويل ضمن صلاحياتك. الكميات بوحدة المخزون الأساسية لكل صنف.', 'Latest 20 transfer documents in your authorized scope. Quantities use each product’s base stock unit.') }}</p></div><div class="space-y-4 p-5">
            @forelse($transfers as $item)<div class="rounded-2xl border border-zinc-200 p-4" data-transfer-row><div class="flex flex-col gap-3 lg:flex-row lg:justify-between"><div><strong>{{ $item->transfer_number }}</strong><span class="ms-2 rounded-full bg-amber-100 px-2 py-1 text-xs">{{ $status($item->status) }}</span><p class="mt-2 text-sm text-zinc-600">{{ $t('من', 'From') }}: {{ \App\Support\HumanName::name($item->sourceStore) }} <small dir="ltr">{{ $item->sourceStore?->code }}</small> · {{ $t('إلى', 'To') }}: {{ \App\Support\HumanName::name($item->destinationStore) }} <small dir="ltr">{{ $item->destinationStore?->code }}</small></p></div><div class="flex flex-wrap gap-2">@if($item->status === 'draft') @can('transfers.edit')<x-actions.button semantic="edit" :label="__('Edit')" :href="route('inventory.transfers.edit', $item)">{{ $t('تعديل', 'Edit') }}</x-actions.button>@endcan @can('transfers.submit')<form method="POST" action="{{ route('inventory.transfers.submit', $item) }}">@csrf<x-actions.button type="submit" semantic="confirm" :label="__('Submit')">{{ $t('إرسال', 'Submit') }}</x-actions.button></form>@endcan @elseif($item->status === 'submitted') @can('transfers.approve')<form method="POST" action="{{ route('inventory.transfers.approve', $item) }}">@csrf<x-actions.button type="submit" semantic="approve" :label="__('Approve')">{{ $t('اعتماد', 'Approve') }}</x-actions.button></form>@endcan @elseif($item->status === 'approved') @can('transfers.dispatch')<form method="POST" action="{{ route('inventory.transfers.dispatch', $item) }}">@csrf<x-actions.button type="submit" semantic="complete" :label="__('Dispatch')">{{ $t('إرسال من المصدر', 'Dispatch from source') }}</x-actions.button></form>@endcan @elseif($item->status === 'in_transit') @can('transfers.receive')<x-actions.button semantic="receive" :label="__('Receive')" :href="route('inventory.transfers.receive-page', $item)">{{ $t('استلام', 'Receive') }}</x-actions.button>@endcan @elseif($item->status === 'difference_review') @can('transfers.difference')<x-actions.button semantic="view" :label="__('Review difference')" :href="route('inventory.transfers.differences', $item)">{{ $t('مراجعة الفرق', 'Review difference') }}</x-actions.button>@endcan @endif</div></div>
                <div class="mt-3 overflow-x-auto"><table class="w-full text-sm"><caption class="sr-only">{{ $t('أصناف وكميات التحويل', 'Transfer products and quantities') }}</caption><thead><tr><th class="py-2 text-start">{{ $t('الصنف', 'Product') }}</th><th class="text-end">{{ $t('المطلوب', 'Requested') }}</th><th class="text-end">{{ $t('المرسل', 'Dispatched') }}</th><th class="text-end">{{ $t('المستلم', 'Received') }}</th></tr></thead><tbody>@foreach($item->lines as $line)<tr class="border-t border-border"><td class="py-2">{{ \App\Support\HumanName::name($line->product) }} <small dir="ltr">{{ $line->product?->item_code }}</small></td><td class="text-end">{{ $qty($line->quantity_requested) }}</td><td class="text-end">{{ $qty($line->quantity_dispatched) }}</td><td class="text-end">{{ $qty($line->quantity_received) }}</td></tr>@endforeach</tbody></table></div>
                @if($focus !== 'transfers')
                @if($item->status === 'in_transit')<form class="mt-4 grid gap-3 rounded-xl bg-zinc-50 p-3 sm:grid-cols-4" method="POST" action="{{ route('inventory.transfers.receive', $item) }}">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) str()->uuid() }}"> @foreach($item->lines as $line)<div><label for="received-{{ $item->id }}-{{ $line->id }}" class="text-xs font-semibold">{{ $t('المستلم', 'Received') }} · {{ $line->product?->item_code }}</label><input id="received-{{ $item->id }}-{{ $line->id }}" name="received_quantities[{{ $line->id }}]" value="{{ $qty(bcsub((string) $line->quantity_dispatched, bcadd((string) $line->quantity_received, (string) $line->difference_quantity, 6), 6)) }}" class="{{ $field }}" inputmode="decimal" min="0" step="0.000001" required></div>@endforeach<div><label for="difference-{{ $item->id }}" class="text-xs font-semibold">{{ $t('نوع الفرق', 'Difference type') }}</label><select id="difference-{{ $item->id }}" name="difference_type" class="{{ $field }}"><option value="">{{ $t('بدون فرق', 'No difference') }}</option><option value="shortage">{{ $t('عجز', 'Shortage') }}</option><option value="damage">{{ $t('تالف', 'Damage') }}</option><option value="refusal">{{ $t('رفض', 'Refusal') }}</option></select></div><div><label for="reason-{{ $item->id }}" class="text-xs font-semibold">{{ $t('سبب الفرق', 'Difference reason') }}</label><input id="reason-{{ $item->id }}" name="difference_reason" class="{{ $field }}"></div><div class="flex items-end"><x-actions.button type="submit" semantic="receive" :label="__('Record receipt')" class="w-full">{{ $t('تسجيل الاستلام', 'Record receipt') }}</x-actions.button></div></form>@endif
                @if($item->status === 'difference_review')<form class="mt-4 grid gap-3 rounded-xl border border-rose-200 bg-rose-50 p-3 sm:grid-cols-3" method="POST" action="{{ route('inventory.transfers.differences.resolve', $item) }}">@csrf<div><label for="resolve-difference-{{ $item->id }}" class="text-xs font-semibold">{{ $t('نوع الفرق', 'Difference type') }}</label><select id="resolve-difference-{{ $item->id }}" name="difference_type" class="{{ $field }}" required><option value="shortage">{{ $t('عجز', 'Shortage') }}</option><option value="damage">{{ $t('تالف', 'Damage') }}</option><option value="refusal">{{ $t('رفض', 'Refusal') }}</option></select></div><div><label for="resolve-reason-{{ $item->id }}" class="text-xs font-semibold">{{ $t('سبب الإغلاق', 'Resolution reason') }}</label><input id="resolve-reason-{{ $item->id }}" name="difference_reason" class="{{ $field }}" required></div><div class="flex items-end"><x-actions.button type="submit" semantic="confirm" :label="__('Resolve difference')" class="w-full">{{ $t('إغلاق الفرق', 'Resolve difference') }}</x-actions.button></div></form>@endif
                @endif
            </div>@empty<div class="py-4 text-sm text-zinc-500">{{ $t('لا توجد تحويلات في النطاق.', 'No transfers in this scope.') }}</div>@endforelse
        </div></section>
        @endif

        @if($focus === 'adjustment-create' || $adjustment?->status === 'draft')
            <section class="rounded-3xl border border-violet-200 bg-violet-50/50 p-5" aria-labelledby="adjustment-editor-heading" data-inventory-intent="opening-inventory"><h2 id="adjustment-editor-heading" class="text-xl font-bold">{{ $adjustment ? $t('تعديل مستند مسودة', 'Edit draft movement') : $t('إدخال مخزون افتتاحي', 'Opening inventory entry') }}</h2>@if (! $adjustment)<p class="mt-1 text-sm text-zinc-600">{{ $t('اختر نوع إدخال ورمز سبب افتتاحي معتمد فقط. لا تعدل الأرصدة مباشرة ولا ترحل الحركة من هذه الصفحة.', 'Choose an entry type and an approved opening reason only. Do not edit balances directly or post the movement from this page.') }}</p>@endif
                <form class="mt-4 space-y-4" method="POST" action="{{ $adjustment ? route('inventory.adjustments.update', $adjustment) : route('inventory.adjustments.store') }}" data-product-line-editor data-autofocus="true" data-next-index="{{ max(1, $adjustment?->lines?->count() ?? 1) }}">@csrf
                    <div class="grid gap-3 sm:grid-cols-3"><div><label for="adjustment-store" class="text-xs font-semibold">{{ $t('موقع المخزون', 'Stock location') }}</label><select id="adjustment-store" name="store_id" class="{{ $field }}" required>@foreach($visibleStores as $store)<option value="{{ $store->id }}" @selected($adjustment?->store_id === $store->id)>{{ $store->code }}</option>@endforeach</select></div><div><label for="adjustment-type" class="text-xs font-semibold">{{ $t('نوع الحركة', 'Movement type') }}</label><select id="adjustment-type" name="adjustment_type" class="{{ $field }}" required>@foreach(['entry','exit','exchange','adjustment'] as $type)<option value="{{ $type }}" @selected(($adjustment?->adjustment_type ?? '') === $type)>{{ __($type) }}</option>@endforeach</select></div><div><label for="adjustment-reason" class="text-xs font-semibold">{{ $t('السبب', 'Reason') }}</label><select id="adjustment-reason" name="reason_code" class="{{ $field }}" required>@foreach(["opening_stock","opening_inventory","count_variance","reversal","opened_bag","weight_loss","damage","moisture","scale_variance","entry_error"] as $reason)<option value="{{ $reason }}" @selected(($adjustment?->reason_code ?? "") === $reason)>{{ __($reason) }}</option>@endforeach</select></div></div>
                    <div class="space-y-3">@foreach(($adjustment?->lines?->all() ?: [null]) as $lineIndex => $adjustmentLine)<div class="grid gap-3 rounded-xl border bg-white/70 p-3 sm:grid-cols-12" data-product-line><div class="sm:col-span-4"><x-product-line-lookup :name="'lines['.$lineIndex.'][product_id]'" :value="old('lines.'.$lineIndex.'.product_id', $adjustmentLine?->product_id)" :display="$adjustmentLine?->product ? ((str_starts_with(app()->getLocale(), 'ar') ? $adjustmentLine->product->name_ar : $adjustmentLine->product->name_en).' · '.$adjustmentLine->product->item_code) : ''" :label="$t('المنتج', 'Product')" :required="true" /></div><div class="sm:col-span-2"><label class="text-xs font-semibold">{{ $t('الكمية', 'Quantity') }}</label><input data-line-quantity name="lines[{{ $lineIndex }}][quantity_delta]" value="{{ filled($adjustmentLine?->quantity_delta) ? $qty($adjustmentLine?->quantity_delta) : '1' }}" class="{{ $field }}" inputmode="decimal" step="0.000001" required></div><div class="sm:col-span-2"><label class="text-xs font-semibold">{{ $t('تكلفة الوحدة', 'Unit cost') }}</label><input data-line-price data-price-kind="cost" name="lines[{{ $lineIndex }}][unit_cost]" value="{{ $adjustmentLine?->unit_cost }}" class="{{ $field }}" inputmode="decimal" min="0" step="0.0001"></div><div class="sm:col-span-2"><span class="block text-xs font-semibold">{{ $t('إجمالي البند', 'Line total') }}</span><output class="mt-1 flex h-10 items-center justify-end rounded-lg bg-zinc-50 px-3 font-mono" data-line-total>0.00</output></div>@if($lineIndex > 0)<button type="button" data-remove-line class="text-sm text-rose-700 underline">{{ $t('حذف', 'Remove') }}</button>@endif</div>@endforeach
                        <template data-line-template><div class="grid gap-3 rounded-xl border bg-white/70 p-3 sm:grid-cols-12" data-product-line><div class="sm:col-span-4"><x-product-line-lookup name="lines[__INDEX__][product_id]" :label="$t('المنتج', 'Product')" :required="true" /></div><div class="sm:col-span-2"><label class="text-xs font-semibold">{{ $t('الكمية', 'Quantity') }}</label><input data-line-quantity name="lines[__INDEX__][quantity_delta]" value="1" class="{{ $field }}" inputmode="decimal" step="0.000001" required></div><div class="sm:col-span-2"><label class="text-xs font-semibold">{{ $t('تكلفة الوحدة', 'Unit cost') }}</label><input data-line-price data-price-kind="cost" name="lines[__INDEX__][unit_cost]" class="{{ $field }}" inputmode="decimal" min="0" step="0.0001"></div><div class="sm:col-span-2"><span class="block text-xs font-semibold">{{ $t('إجمالي البند', 'Line total') }}</span><output class="mt-1 flex h-10 items-center justify-end rounded-lg bg-zinc-50 px-3 font-mono" data-line-total>0.00</output></div><button type="button" data-remove-line class="text-sm text-rose-700 underline">{{ $t('حذف', 'Remove') }}</button></div></template>
                        <button type="button" data-add-line class="text-sm font-semibold text-violet-700 underline">{{ $t('إضافة بند', 'Add item') }}</button></div>
                    <label class="flex gap-2 text-sm"><input type="checkbox" name="allow_negative" value="1" @checked($adjustment?->allow_negative)> <span>{{ $t('السماح بالرصيد السالب مع الصلاحية والسبب', 'Allow negative stock with permission and reason') }}</span></label><textarea name="reason_notes" class="{{ $field }}" rows="2" placeholder="{{ $t('سبب التجاوز عند الحاجة', 'Override reason when required') }}">{{ $adjustment?->reason_notes }}</textarea><button type="submit" class="{{ $button }} bg-violet-700 text-white">{{ $t('حفظ المسودة', 'Save draft') }}</button></form></section>
        @endif

        @if($focus === null || str_starts_with((string) $focus, 'count') || str_starts_with((string) $focus, 'adjustment'))
        <div @class(['grid gap-6', 'xl:grid-cols-2' => $focus === null])>
            @if($focus === null || str_starts_with((string) $focus, 'adjustment'))
            <section class="rounded-3xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900" aria-labelledby="adjustments-heading" data-guide="inventory-adjustments"><div class="border-b border-zinc-200 px-5 py-4"><h2 id="adjustments-heading" class="text-xl font-bold">{{ $t('الإدخال والإخراج والتسويات', 'Entries, exits, and adjustments') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ $t('الرصيد السالب محظور افتراضيا، والتجاوز يتطلب صلاحية وسببا وتدقيقا.', 'Negative stock is blocked by default; overrides require permission, reason, and audit.') }}</p></div><div class="space-y-3 p-5">@forelse($adjustments as $item)<div class="rounded-2xl border border-zinc-200 p-4"><div class="flex items-center justify-between gap-3"><div><strong>{{ $item->adjustment_number }}</strong><div class="mt-1 text-xs text-zinc-500">{{ $item->store?->code }} · {{ $item->adjustment_type }} · {{ $item->reason_code }}</div></div><span class="rounded-full bg-zinc-100 px-2 py-1 text-xs">{{ $status($item->status) }}</span></div><div class="mt-3 flex flex-wrap gap-2">@if($item->status === 'draft') @can('inventory_stock_card.edit')<x-actions.button semantic="edit" :label="__('Edit')" :href="route('inventory.adjustments.edit', $item)">{{ $t('تعديل', 'Edit') }}</x-actions.button>@endcan @can('inventory_stock_card.submit')<form method="POST" action="{{ route('inventory.adjustments.submit', $item) }}">@csrf<x-actions.button type="submit" semantic="confirm" :label="__('Submit')">{{ $t('إرسال', 'Submit') }}</x-actions.button></form>@endcan @elseif($item->status === 'submitted') @can('inventory_stock_card.approve')<form method="POST" action="{{ route('inventory.adjustments.approve', $item) }}">@csrf<x-actions.button type="submit" semantic="approve" :label="__('Approve and post')">{{ $t('اعتماد وترحيل', 'Approve and post') }}</x-actions.button></form>@endcan @elseif($item->status === 'approved' && ! $item->reversal_of_id) @can('inventory_stock_card.reverse')<form method="POST" action="{{ route('inventory.adjustments.reverse', $item) }}">@csrf<input type="hidden" name="reason" value="{{ $t('تصحيح مستند معتمد', 'Corrective reversal') }}"><x-actions.button type="submit" semantic="cancel" :label="__('Reverse')">{{ $t('عكس', 'Reverse') }}</x-actions.button></form>@endcan @endif</div></div>@empty<p class="text-sm text-zinc-500">{{ $t('لا توجد مستندات حركة.', 'No inventory documents.') }}</p>@endforelse</div></section>
            @endif

            @if($focus === null || str_starts_with((string) $focus, 'count'))
            <section class="rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900" aria-labelledby="counts-heading" data-guide="inventory-counts"><div class="border-b border-zinc-200 px-5 py-4"><h2 id="counts-heading" class="text-lg font-bold">{{ $t('جلسات العد ومراجعة الفروقات', 'Count sessions and variance review') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ $t('أحدث 20 جلسة جرد ضمن صلاحياتك. افتح إدخال العد للجلسات الجارية أو مراجعة الفروقات للجلسات المرسلة.', 'Latest 20 count sessions in your authorized scope. Enter counts for active sessions or review variances for submitted sessions.') }}</p></div><div class="space-y-3 p-5">
                @if($focus === 'count-create')
                    <form class="space-y-6 rounded-2xl border border-emerald-200 bg-emerald-50/40 p-4 sm:p-6" method="POST" action="{{ route('inventory.counts.store') }}" x-data="{ scope: @js(old('scope_type', 'partial')) }">@csrf
                        <div><h3 class="text-lg font-bold">{{ $t('ابدأ جردًا فعليًا', 'Start a physical count') }}</h3><p class="mt-1 max-w-3xl text-sm text-zinc-600">{{ $t('أنشئ الجلسة أولًا، ثم افتحها وابدأ إدخال الكميات التي تراها فعلًا. لن يتغير المخزون قبل المراجعة والاعتماد.', 'Create the session first, then open it and enter the quantities physically found. Stock does not change before review and approval.') }}</p></div>
                        <section class="space-y-3" aria-labelledby="count-step-location"><div><p class="text-xs font-bold text-emerald-800">{{ $t('الخطوة 1', 'Step 1') }}</p><h4 id="count-step-location" class="font-bold">{{ $t('أين سيتم الجرد؟', 'Where will you count?') }}</h4></div>
                            @php($countBranches = $visibleStores->pluck('branch')->filter()->unique('id')->values())
                            @if($countBranches->count() === 1)<input type="hidden" name="branch_id" value="{{ $countBranches->first()->id }}">@else<div><label class="text-sm font-semibold">{{ $t('الفرع', 'Branch') }}</label><select name="branch_id" class="{{ $field }}" required><option value="">{{ $t('اختر الفرع', 'Select branch') }}</option>@foreach($countBranches as $branch)<option value="{{ $branch->id }}" @selected((int) old('branch_id', $visibleStores->first()?->branch_id) === (int) $branch->id)>{{ \App\Support\HumanName::name($branch) }} — {{ $branch->code }}</option>@endforeach</select></div>@endif
                            <fieldset><legend class="text-sm font-semibold">{{ $t('اختر مخزنًا أو منفذ بيع واحدًا على الأقل', 'Choose at least one warehouse or sales outlet') }}</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($visibleStores->whereIn('type',['warehouse','selling']) as $store)<label class="flex cursor-pointer gap-3 rounded-xl border border-zinc-200 bg-white p-3 transition hover:border-emerald-400"><input class="mt-1" type="checkbox" name="location_ids[]" value="{{ $store->id }}" @checked(in_array((string) $store->id, array_map('strval', old('location_ids', [$visibleStores->whereIn('type',['warehouse','selling'])->first()?->id])), true))><span><strong class="block">{{ \App\Support\HumanName::name($store) }}</strong><small class="text-zinc-500" dir="ltr">{{ $store->code }} · {{ $store->type==='selling'?$t('منفذ بيع','Sales outlet'):$t('مخزن','Warehouse') }}</small></span></label>@endforeach</div></fieldset>
                        </section>
                        <section class="space-y-3 border-t border-emerald-200 pt-5" aria-labelledby="count-step-scope"><div><p class="text-xs font-bold text-emerald-800">{{ $t('الخطوة 2', 'Step 2') }}</p><h4 id="count-step-scope" class="font-bold">{{ $t('ما الذي ستعدّه؟', 'What will you count?') }}</h4><p class="text-sm text-zinc-600">{{ $t('ابدأ بجرد جزئي لو هذه أول مرة. الجرد الكامل يتطلب إنهاء كل الأصناف أو تأكيدها بصفر.', 'Choose a partial count for a first run. A full count requires every product to be counted or explicitly confirmed as zero.') }}</p></div>
                            <input type="hidden" name="count_type" x-bind:value="scope === 'full' ? 'full' : 'partial'">
                            <select name="scope_type" x-model="scope" class="{{ $field }}"><option value="partial">{{ $t('أصناف أحددها أثناء العد (الأسهل)', 'Products chosen while counting (easiest)') }}</option><option value="full">{{ $t('كل الأصناف في المواقع المختارة', 'All products in selected locations') }}</option><option value="category">{{ $t('كل أصناف تصنيف محدد', 'All products in one category') }}</option><option value="supplier">{{ $t('كل أصناف مورد محدد', 'All products from one supplier') }}</option></select>
                            <div x-show="scope === 'category'" x-cloak><label class="text-sm font-semibold">{{ $t('التصنيف المطلوب', 'Category to count') }}</label><select name="category_id" class="{{ $field }}"><option value="">{{ $t('اختر التصنيف', 'Choose category') }}</option>@foreach($countCategories as $category)<option value="{{ $category->id }}" @selected((int) old('category_id') === (int) $category->id)>{{ \App\Support\HumanName::name($category) }}</option>@endforeach</select></div>
                            <div x-show="scope === 'supplier'" x-cloak><label class="text-sm font-semibold">{{ $t('المورد المطلوب', 'Supplier to count') }}</label><select name="supplier_id" class="{{ $field }}"><option value="">{{ $t('اختر المورد', 'Choose supplier') }}</option>@foreach($countSuppliers as $supplier)<option value="{{ $supplier->id }}" @selected((int) old('supplier_id') === (int) $supplier->id)>{{ \App\Support\HumanName::name($supplier) }}</option>@endforeach</select></div>
                        </section>
                        <section class="space-y-3 border-t border-emerald-200 pt-5" aria-labelledby="count-step-team"><div><p class="text-xs font-bold text-emerald-800">{{ $t('الخطوة 3', 'Step 3') }}</p><h4 id="count-step-team" class="font-bold">{{ $t('من سيعدّ ومن سيراجع؟', 'Who will count and review?') }}</h4></div>
                            <fieldset><legend class="text-sm font-semibold">{{ $t('فريق العد', 'Counting team') }}</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($countAssignees as $assignee)<label class="flex gap-2 rounded-xl border border-zinc-200 bg-white p-3"><input class="mt-1" type="checkbox" name="member_ids[]" value="{{ $assignee->id }}" @checked(in_array((string) $assignee->id, array_map('strval', old('member_ids', [auth()->id()])), true))><span>{{ $assignee->name }} <small class="block text-zinc-500" dir="ltr">{{ $assignee->email }}</small></span></label>@endforeach</div></fieldset>
                            <div><label class="text-sm font-semibold">{{ $t('مسؤول إغلاق الجلسة والمراجعة', 'Session reviewer') }}</label><select name="manager_id" class="{{ $field }}" required>@foreach($countManagers as $manager)<option value="{{ $manager->id }}" @selected((int) old('manager_id', auth()->id()) === (int) $manager->id)>{{ $manager->name }}</option>@endforeach</select></div>
                            <div><label class="text-sm font-semibold">{{ $t('تعليمات للفريق (اختياري)', 'Team instructions (optional)') }}</label><textarea name="notes" class="{{ $field }}" rows="3" placeholder="{{ $t('مثال: ابدأوا من صف الأعلاف الجافة', 'Example: start with the dry-feed aisle') }}">{{ old('notes') }}</textarea></div>
                        </section>
                        <div class="flex flex-wrap items-center justify-between gap-3 border-t border-emerald-200 pt-5"><p class="text-sm text-zinc-600">{{ $t('بعد الإنشاء ستراجع النطاق، ثم تضغط «فتح الجلسة وبدء العد».', 'After creation, review the scope, then choose “Open session and start counting”.') }}</p><button type="submit" class="{{ $button }} bg-emerald-700 px-5 py-3 text-white">{{ $t('إنشاء الجلسة والمتابعة', 'Create session and continue') }}</button></div>
                    </form>
                @endif
                @forelse($counts as $item)<div class="rounded-2xl border border-zinc-200 p-4"><div class="flex items-center justify-between gap-3"><div><strong>{{ $item->count_number }}</strong><div class="mt-1 text-xs text-zinc-500">{{ $t('موقع الجرد', 'Count location') }}: {{ \App\Support\HumanName::name($item->store) }} <small dir="ltr">{{ $item->store?->code }}</small> · {{ $item->count_type === 'full' ? $t('جرد كامل', 'Full count') : $t('جرد جزئي', 'Partial count') }} · {{ $item->lines->where('is_counted', false)->count() }} {{ $t('غير معدود', 'uncounted') }}</div></div><span class="rounded-full bg-zinc-100 px-2 py-1 text-xs">{{ $status($item->status) }}</span></div><div class="mt-3 flex flex-wrap gap-2">@if($item->status === 'draft') @can('stock_counts.edit')<x-actions.button semantic="edit" :label="$t('راجع النطاق وابدأ الجرد', 'Review scope and start count')" :href="route('inventory.counts.entry', $item)">{{ $t('راجع النطاق وابدأ الجرد', 'Review scope and start count') }}</x-actions.button>@endcan @elseif($item->status === 'in_progress') @can('stock_counts.edit')<x-actions.button semantic="edit" :label="$t('استكمال إدخال الجرد', 'Continue count entry')" :href="route('inventory.counts.entry', $item)">{{ $t('استكمال إدخال الجرد', 'Continue count entry') }}</x-actions.button>@endcan @can('stock_counts.submit')<form method="POST" action="{{ route('inventory.counts.submit', $item) }}">@csrf<x-actions.button type="submit" semantic="confirm" :label="__('Submit')">{{ $t('إنهاء العد وإرساله للمراجعة', 'Finish counting and submit for review') }}</x-actions.button></form>@endcan @elseif($item->status === 'submitted') @can('stock_counts.reconcile')<x-actions.button semantic="view" :label="__('Review')" :href="route('inventory.counts.reconcile-page', $item)">{{ $t('مراجعة العد والفروقات', 'Review count and variances') }}</x-actions.button>@if($focus !== 'counts')<form method="POST" action="{{ route('inventory.counts.reconcile', $item) }}">@csrf<x-actions.button type="submit" semantic="approve" :label="__('Reconcile and approve')">{{ $t('مطابقة واعتماد', 'Reconcile and approve') }}</x-actions.button></form>@endif @endcan @endif</div></div>@empty@if($focus !== 'count-create')<div class="py-4 text-sm text-zinc-500">{{ $t('لا توجد جلسات جرد بعد. ابدأ جلسة وحدد موقع العد.', 'No count sessions yet. Start one and choose the count location.') }}</div>@endif @endforelse
                @if($count && $focus === 'count-entry')
                    <div class="space-y-5 rounded-2xl border border-emerald-200 bg-emerald-50/40 p-4 sm:p-6">
                        <div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-bold text-emerald-800">{{ $t('جلسة الجرد', 'Count session') }}</p><h3 class="text-lg font-bold" dir="ltr">{{ $count->count_number }}</h3><p class="mt-1 text-sm text-zinc-600">{{ $count->count_type === 'full' ? $t('جرد كامل: يجب إنهاء كل صنف في النطاق.', 'Full count: every scoped product must be completed.') : $t('جرد جزئي: أضف فقط الأصناف التي تريد عدّها.', 'Partial count: add only the products you want to count.') }}</p></div><x-status.badge :status="$count->status" :label="$status($count->status)" /></div>
                        <div class="grid gap-2 sm:grid-cols-2">@foreach($count->locations as $location)<div class="rounded-xl border border-emerald-200 bg-white px-4 py-3"><span class="block font-semibold">{{ \App\Support\HumanName::name($location->store) }}</span><small class="text-zinc-500" dir="ltr">{{ $location->store?->code }}</small></div>@endforeach</div>
                        @if($count->status === 'draft')
                            <div class="rounded-xl border border-amber-200 bg-amber-50 p-4"><p class="font-bold text-amber-900">{{ $t('راجع النطاق قبل البدء', 'Review the scope before starting') }}</p><p class="mt-1 text-sm text-amber-800">{{ $t('فتح الجلسة يثبت رصيد المقارنة في هذه اللحظة. بعد الفتح ابدأ عدّ الكميات الموجودة فعليًا.', 'Opening freezes the comparison balance at this moment. Then start counting the quantities physically present.') }}</p></div>
                            @can('stock_counts.open')<form method="POST" action="{{ route('inventory.counts.open',$count) }}">@csrf<button class="{{ $button }} bg-emerald-700 px-5 py-3 text-white">{{ $t('فتح الجلسة وبدء العد', 'Open session and start counting') }}</button></form>@endcan
                        @elseif($count->status === 'in_progress')
                            <section class="border-t border-emerald-200 pt-5" aria-labelledby="count-entry-heading"><h4 id="count-entry-heading" class="font-bold">{{ $t('سجّل الكمية الفعلية', 'Record the physical quantity') }}</h4><p class="mt-1 text-sm text-zinc-600">{{ $t('ابحث بالاسم أو الكود أو امسح الباركود. عند تكرار الصنف تُضاف الكمية إلى إجماليه.', 'Search by name or code, or scan the barcode. Repeating a product adds to its counted total.') }}</p>
                                <form class="mt-4 grid gap-4 lg:grid-cols-[1fr_2fr_1fr_auto] lg:items-end" method="POST" action="{{ route('inventory.counts.contribute',$count) }}" data-product-line-editor data-autofocus="true">@csrf<input type="hidden" name="request_id" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><input type="hidden" name="device_id" value="browser-{{ auth()->id() }}"><div><label class="text-sm font-semibold">{{ $t('الموقع', 'Location') }}</label><select name="store_id" class="{{ $field }}">@foreach($count->locations as $location)<option value="{{ $location->store_id }}">{{ \App\Support\HumanName::name($location->store) }} — {{ $location->store?->code }}</option>@endforeach</select></div><div data-product-line><x-product-line-lookup name="lookup" value-field="item_code" :label="$t('الصنف أو الباركود', 'Product or barcode')" :required="true" /></div><div><label class="text-sm font-semibold">{{ $t('الكمية التي عددتها', 'Counted quantity') }}</label><input type="number" data-line-quantity name="quantity" value="1" min="0.000001" step="any" inputmode="decimal" class="{{ $field }}" required></div><input type="hidden" name="input_method" value="manual"><button type="submit" data-add-line class="{{ $button }} min-h-11 bg-emerald-700 px-5 text-white">{{ $t('إضافة للعد', 'Add to count') }}</button></form>
                            </section>
                            <section class="border-t border-emerald-200 pt-5"><div class="flex flex-wrap items-end justify-between gap-2"><div><h4 class="font-bold">{{ $t('ما تم عدّه', 'Counted products') }}</h4><p class="text-sm text-zinc-600">{{ $count->lines->where('is_counted', true)->count() }} {{ $t('صنفًا مسجلًا', 'products recorded') }}</p></div></div><div class="mt-3 grid gap-2">@forelse($count->lines->where('is_counted',true) as $line)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-zinc-200 bg-white p-3"><div><strong>{{ \App\Support\HumanName::name($line->product) }}</strong><small class="block text-zinc-500" dir="ltr">{{ $line->product?->item_code }}</small></div><div class="flex items-center gap-3"><span class="font-mono font-bold" dir="ltr">{{ $qty($line->counted_quantity) }} {{ $line->product?->unit_of_measure }}</span>@if(!$line->completed_at)<form method="POST" action="{{ route('inventory.counts.complete-line',$line) }}">@csrf<button class="{{ $button }} border border-emerald-300 bg-emerald-50 text-emerald-800">{{ $t('تأكيد هذا الصنف', 'Confirm product') }}</button></form>@else<span class="text-sm font-semibold text-emerald-700">{{ $t('تم التأكيد', 'Confirmed') }}</span>@endif</div></div>@empty<p class="rounded-xl border border-dashed border-zinc-300 bg-white p-5 text-center text-sm text-zinc-600">{{ $t('لم تُسجّل أي كمية بعد. ابدأ من الحقل بالأعلى.', 'No quantities recorded yet. Start with the field above.') }}</p>@endforelse</div></section>
                            @if($count->lines->where('is_counted', false)->isNotEmpty())<details class="border-t border-emerald-200 pt-5"><summary class="cursor-pointer font-bold">{{ $t('أصناف لم تُعد بعد', 'Products not counted yet') }} ({{ $count->lines->where('is_counted', false)->count() }})</summary><p class="mt-1 text-sm text-zinc-600">{{ $t('إذا تحققت أن الصنف غير موجود فعليًا، أكّده بصفر. لا تستخدم الصفر لمجرد أنك لم تبحث عنه.', 'If you verified the product is physically absent, confirm zero. Do not use zero merely because it was not checked.') }}</p><div class="mt-3 grid gap-2">@foreach($count->lines->where('is_counted', false) as $line)<div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-zinc-200 bg-white p-3"><div><strong>{{ \App\Support\HumanName::name($line->product) }}</strong><small class="block text-zinc-500" dir="ltr">{{ $line->product?->item_code }}</small></div><form method="POST" action="{{ route('inventory.counts.complete-line',$line) }}">@csrf<input type="hidden" name="explicit_zero" value="1"><button class="{{ $button }} border border-zinc-300 bg-white text-zinc-800">{{ $t('تأكيد غير موجود (صفر)', 'Confirm absent (zero)') }}</button></form></div>@endforeach</div></details>@endif
                        @endif
                    </div>
                @endif
                @if($count && $focus === 'count-reconcile')<div class="rounded-2xl border border-sky-200 bg-sky-50/50 p-4"><h3 class="font-bold">{{ $t('مراجعة المطابقة', 'Reconciliation review') }} · {{ $count->count_number }}</h3><div class="mt-3 overflow-x-auto"><table class="min-w-[520px] w-full text-sm"><thead><tr><th class="text-start">{{ $t('المنتج', 'Product') }}</th><th class="text-end">{{ $t('المتوقع', 'Expected') }}</th><th class="text-end">{{ $t('المعدود', 'Counted') }}</th><th class="text-end">{{ $t('الفرق', 'Variance') }}</th></tr></thead><tbody>@foreach($count->lines as $line)<tr class="border-t border-zinc-200"><td>{{ $line->product?->item_code }}</td><td class="text-end">{{ $qty($line->expected_quantity) }}</td><td class="text-end">{{ $line->is_counted ? $qty($line->counted_quantity) : $t('غير معدود', 'Uncounted') }}</td><td class="text-end">{{ $line->variance_quantity === null ? '—' : $qty($line->variance_quantity) }}</td></tr>@endforeach</tbody></table></div><p class="mt-3 text-xs text-zinc-600">{{ $t('راجع العناصر غير المعدودة قبل الاعتماد. لا يتم تحويلها إلى صفر تلقائيا.', 'Review uncounted items before approval. They are never silently converted to zero.') }}</p></div>@endif
            </div></section>
            @endif
        </div>
        @endif

        @if(in_array($focus, [null, 'movements', 'stock-card'], true) || str_starts_with((string) $focus, 'adjustment'))
        <section class="rounded-3xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900" aria-labelledby="movements-heading" data-guide="inventory-movements">
            <div class="border-b border-border px-5 py-4"><h2 id="movements-heading" class="text-xl font-bold">{{ $t('دفتر حركات المخزون', 'Inventory movement ledger') }}</h2><p class="mt-1 text-sm text-text-muted">{{ $t('الوارد يزيد المخزون والصادر يقلله. الكميات بوحدة الصنف الأساسية، وليست بالضرورة عدد الشكاير. كل حركة مرحلة مرتبطة بمصدرها ولا تُعدّل.', 'Incoming stock increases inventory; outgoing stock reduces it. Quantities use the product base unit, not necessarily bags. Posted movements are source-linked and immutable.') }}</p></div>
            <x-tables.table-shell :label="$t('حركات المخزون', 'Inventory movements')">
                <div class="overflow-x-auto"><table class="data-table responsive-resource-table w-full text-start text-sm">
                    <thead><tr><th scope="col">{{ $t('تاريخ الترحيل', 'Posted at') }}</th><th scope="col">{{ $t('الصنف', 'Product') }}</th><th scope="col">{{ $t('المخزن / المنفذ', 'Location') }}</th><th scope="col">{{ $t('نوع الحركة', 'Movement type') }}</th><th scope="col">{{ $t('تأثير الحركة', 'Stock change') }}</th><th scope="col">{{ $t('المستند المصدر', 'Source document') }}</th><th scope="col">{{ $t('سجّلها', 'Recorded by') }}</th></tr></thead>
                    <tbody>
                    @forelse($movements as $movement)
                        @php
                            $sourceName = match (class_basename((string) $movement->source_type)) {
                                'Sale', 'sales' => $t('فاتورة بيع', 'Sales invoice'),
                                'PurchaseInvoice', 'purchase_invoices' => $t('فاتورة شراء', 'Purchase invoice'),
                                'RetailReturn', 'retail_returns' => $t('مرتجع بيع', 'Sales return'),
                                'PurchaseReturn', 'purchase_returns' => $t('مرتجع مورد', 'Supplier return'),
                                'StockTransfer', 'stock_transfers' => $t('تحويل مخزون', 'Stock transfer'),
                                'InventoryAdjustment', 'inventory_adjustments' => $t('تسوية مخزون', 'Stock adjustment'),
                                'StockCount', 'stock_counts' => $t('جلسة جرد', 'Stock count'),
                                'OpeningInventoryDocument', 'opening_inventory_documents' => $t('مستند مخزون افتتاحي', 'Opening inventory document'),
                                default => $movement->source_type ? app(\App\Modules\Platform\Support\AuditLogPresentation::class)->source($movement->source_type) : $t('مصدر غير مسجل', 'Source not recorded'),
                            };
                            $direction = bccomp((string) $movement->quantity, '0', 6);
                        @endphp
                        <tr data-movement-row>
                            <td data-label="{{ $t('تاريخ الترحيل', 'Posted at') }}"><span class="block whitespace-nowrap font-mono text-xs" dir="ltr">{{ $movement->posted_at?->format('Y-m-d') ?? '—' }}</span><span class="text-xs text-text-muted" dir="ltr">{{ $movement->posted_at?->format('H:i') }}</span></td>
                            <td data-primary><a class="font-semibold text-primary underline-offset-4 hover:underline" href="{{ route('inventory.stock-card', $movement->product_id) }}">{{ \App\Support\HumanName::name($movement->product) }}</a><span class="block font-mono text-xs text-text-muted" dir="ltr">{{ $movement->product?->item_code }}</span></td>
                            <td data-label="{{ $t('المخزن / المنفذ', 'Location') }}"><span class="block font-medium">{{ \App\Support\HumanName::name($movement->store) }}</span><span class="font-mono text-xs text-text-muted" dir="ltr">{{ $movement->store?->code }}</span></td>
                            <td data-label="{{ $t('نوع الحركة', 'Movement type') }}"><x-status.badge :status="$movement->movement_type" :label="$movementLabel($movement->movement_type)" /></td>
                            <td data-label="{{ $t('تأثير الحركة', 'Stock change') }}"><span class="block whitespace-nowrap font-mono font-semibold {{ $direction < 0 ? 'text-rose-700 dark:text-rose-400' : ($direction > 0 ? 'text-emerald-700 dark:text-emerald-400' : '') }}" dir="ltr">{{ $direction > 0 ? '+' : '' }}{{ $qty($movement->quantity) }} {{ $movement->product?->unit_of_measure ?? '—' }}</span><span class="text-xs text-text-muted">{{ $direction < 0 ? $t('صادر من المخزون', 'Outgoing stock') : ($direction > 0 ? $t('وارد إلى المخزون', 'Incoming stock') : $t('بدون تغيير كمية', 'No quantity change')) }}</span></td>
                            <td data-label="{{ $t('المستند المصدر', 'Source document') }}"><span class="block">{{ $sourceName }}</span>@if($movement->source_id)<span class="block text-xs text-text-muted">{{ $t('معرّف المستند', 'Document ID') }}: <span dir="ltr">#{{ $movement->source_id }}</span></span>@endif<span class="block text-xs text-text-muted">{{ $t('معرّف الحركة', 'Movement ID') }}: <span dir="ltr">#{{ $movement->id }}</span></span>@if($movement->reversal_of_id)<span class="block text-xs">{{ $t('عكس الحركة', 'Reversal of movement') }} #{{ $movement->reversal_of_id }}</span>@endif</td>
                            <td data-label="{{ $t('سجّلها', 'Recorded by') }}">{{ $movement->creator?->name ?? '—' }}</td>
                        </tr>
                    @empty
                        <tr><td colspan="7" class="px-5 py-8 text-center text-text-muted">{{ $t('لا توجد حركات ضمن النطاق والفلاتر الحالية.', 'No movements within the current scope and filters.') }}</td></tr>
                    @endforelse
                    </tbody>
                </table></div>
                <div class="border-t border-border px-5 py-3"><x-tables.pagination :paginator="$movements" :page-sizes="[50]" /></div>
            </x-tables.table-shell>
        </section>
        @endif
        @endunless
    </div>
</x-layouts.app>
