@php($ar = str_starts_with(app()->getLocale(), 'ar'))
<x-layouts.app :title="app()->isLocale('ar-EG') ? 'ضيف رصيد افتتاحي للمخزون' : ($ar ? 'إضافة رصيد افتتاحي للمخزون' : 'Add Opening Inventory')">
<x-app.page :title="app()->isLocale('ar-EG') ? 'ضيف رصيد افتتاحي للمخزون' : ($ar ? 'إضافة رصيد افتتاحي للمخزون' : 'Add Opening Inventory')" :description="$ar ? 'مسودة مدمجة تُراجع ثم تُرحّل مرة واحدة إلى سجل المخزون.' : 'A compact draft reviewed before it posts once to the immutable inventory ledger.'" max-width="7xl">
    <x-slot:actions><flux:button :href="route('inventory.opening.template')" icon="arrow-down-tray" variant="subtle">{{ $ar ? 'تنزيل نموذج XLSX' : 'Download XLSX template' }}</flux:button></x-slot:actions>
    @if(session('success'))<flux:callout variant="success" icon="check-circle">{{ session('success') }}</flux:callout>@endif
    @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle"><ul class="list-disc ps-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></flux:callout>@endif
    <details class="rounded-xl border border-border bg-surface p-4"><summary class="cursor-pointer font-semibold">{{ $ar ? 'استيراد Excel' : 'Excel import' }}</summary><form method="POST" enctype="multipart/form-data" action="{{ route('inventory.opening.import') }}" class="mt-3 flex flex-wrap items-end gap-3">@csrf<flux:input type="date" name="document_date" :label="$ar ? 'تاريخ المستند' : 'Document date'" :value="now()->toDateString()"/><flux:input type="file" name="workbook" accept=".xlsx" :label="$ar ? 'رفع ملف الرصيد الافتتاحي' : 'Upload Opening Inventory workbook'" required/><x-actions.button type="submit" semantic="create" :label="$ar ? 'فحص وحفظ المسودة' : 'Validate and save draft'">{{ $ar ? 'فحص وحفظ المسودة' : 'Validate and save draft' }}</x-actions.button>@if(session('opening_inventory_rejections'))<flux:button :href="route('inventory.opening.rejections')" icon="arrow-down-tray">{{ $ar ? 'تنزيل الصفوف المرفوضة' : 'Download rejected rows' }}</flux:button>@endif</form></details>
    @if($documentManualEditable)
        <livewire:inventory::opening-workflow :document-id="$document?->id" />
    @elseif($document?->status === 'draft')
        <flux:callout variant="info" icon="document-check">{{ app()->isLocale('ar-EG') ? 'المسودة دي كبيرة أو موزعة على عدة مواقع؛ راجع الصفوف المرقمة ثم اعتمدها دون تحويلها إلى شبكة الإدخال اليدوي المحدودة.' : ($ar ? 'هذه المسودة كبيرة أو موزعة على عدة مواقع؛ راجع الصفوف المرقمة ثم اعتمدها دون تحويلها إلى شبكة الإدخال اليدوي المحدودة.' : 'This draft is large or spans multiple locations. Review its paginated lines, then approve it without converting it into the bounded manual-entry grid.') }}</flux:callout>
    @endif
    @if($document)
        <flux:card class="space-y-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><flux:heading>{{ $document->document_number }}</flux:heading><p class="text-sm text-text-muted">{{ __($document->status) }} · {{ $document->document_date?->format('Y-m-d') ?? $document->created_at->format('Y-m-d') }}</p></div><strong>{{ number_format((float) $documentTotal, 2) }} EGP</strong></div>
        <div class="grid gap-3 md:grid-cols-2">@foreach($documentLines as $line)<div class="rounded-xl border border-border p-3"><strong>{{ $line->product->item_code }} · {{ $ar ? $line->product->name_ar : ($line->product->name_en ?: $line->product->name_ar) }}</strong><p class="mt-1 text-sm text-text-muted">{{ $line->store->code }} · <x-product-quantity :value="$line->quantity" /> × {{ $line->unit_cost }} = {{ $line->total_value }} EGP</p></div>@endforeach</div>{{ $documentLines->links() }}
        @if($document->status==='draft')@can('inventory_stock_card.approve')<form method="POST" action="{{ route('inventory.opening.approve',$document) }}">@csrf<x-actions.button type="submit" semantic="approve" :label="$ar ? 'اعتماد وترحيل' : 'Approve and post'">{{ $ar ? 'اعتماد وترحيل' : 'Approve and post' }}</x-actions.button></form>@endcan @elseif($document->status==='approved')@can('inventory_stock_card.reverse')<form method="POST" action="{{ route('inventory.opening.reverse',$document) }}" class="flex gap-2">@csrf<flux:input name="reason" :label="$ar ? 'سبب التصحيح' : 'Correction reason'" required/><x-actions.button type="submit" semantic="cancel" :label="$ar ? 'عكس وتصحيح' : 'Reverse and correct'">{{ $ar ? 'عكس وتصحيح' : 'Reverse and correct' }}</x-actions.button></form>@endcan @endif</flux:card>
    @endif
    @can('inventory_stock_card.approve')<flux:card><form method="POST" action="{{ route('inventory.opening.zero') }}" class="flex flex-wrap items-end gap-3">@csrf<flux:input name="reason" :label="$ar ? 'سبب القرار (اختياري)' : 'Decision reason (optional)'"/><x-actions.button type="submit" semantic="confirm" :label="$ar ? 'بدء التشغيل دون مخزون افتتاحي' : 'Start without opening inventory'">{{ $ar ? 'بدء التشغيل دون مخزون افتتاحي' : 'Start without opening inventory' }}</x-actions.button></form></flux:card>@endcan
    <flux:card><flux:heading>{{ $ar ? 'المستندات السابقة' : 'Previous documents' }}</flux:heading><div class="mt-3 space-y-2">@forelse($documents as $item)<a class="flex min-h-11 items-center justify-between rounded-xl border border-border px-3" href="{{ route('inventory.opening.show',$item) }}"><span>{{ $item->document_number }}</span><span>{{ $item->status==='draft' ? __('Resume Draft') : __($item->status) }}</span></a>@empty<p class="text-sm text-text-muted">{{ app()->isLocale('ar-EG') ? 'مفيش مستندات بعد.' : ($ar ? 'لا توجد مستندات بعد.' : 'No documents yet.') }}</p>@endforelse</div></flux:card>
</x-app.page>
</x-layouts.app>
