<x-layouts::app :title="$asset->code">
    @php($ar = str_starts_with(app()->getLocale(), 'ar'))
    <x-app.page :title="($ar ? $asset->name_ar : $asset->name_en)" :description="app()->isLocale('ar-EG') ? 'سجل الهوية والعهدة والحالة والحجوزات المرتبط بالأصل ده.' : ($ar ? 'سجل الهوية والعهدة والحالة والحجوزات المرتبط بهذا الأصل.' : 'Identity, custody, condition, and reservation history for this asset.')" max-width="7xl">
        <x-slot:actions><flux:button href="{{ route('party.assets.index', ['mode' => 'catalog']) }}" variant="subtle" icon="arrow-left">{{ $ar ? 'سجل الأصول' : 'Asset catalog' }}</flux:button>@can('rental_assets.print')<flux:button href="{{ route('party.assets.print', $asset) }}" icon="printer">{{ __('Print') }}</flux:button>@endcan</x-slot:actions>
        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="{{ $ar ? 'ملخص الأصل' : 'Asset summary' }}">
            <x-cards.stat-card :label="$ar ? 'كود الأصل' : 'Asset code'" :value="$asset->code" icon="qr-code" tone="primary" />
            <x-cards.stat-card :label="__('Status')" :value="__((string) str($asset->status)->replace('_', ' ')->headline())" icon="check-badge" tone="info" />
            <x-cards.stat-card :label="__('Condition')" :value="__(ucfirst($asset->condition))" icon="wrench-screwdriver" tone="warning" />
            <x-cards.stat-card :label="__('Location')" :value="$asset->store?->code.' · '.($asset->location ?: '—')" icon="map-pin" tone="success" />
        </section>

        <div class="grid gap-4 xl:grid-cols-12">
            <section class="dashboard-panel xl:col-span-7"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'الحجوزات والعهدة' : 'Reservations and custody' }}</flux:heading><flux:text size="sm">{{ $ar ? 'سجل زمني محدود لأحدث العمليات' : 'Bounded timeline of recent operations' }}</flux:text></div><x-status.badge :status="$asset->status" /></header><div class="space-y-3">@forelse($asset->reservations as $reservation)<article class="rounded-xl border border-border p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><strong class="block">{{ $reservation->source_reference ?: ($ar ? 'حجز دون مرجع' : 'Reservation without reference') }}</strong><span class="text-sm text-text-muted" dir="ltr">{{ $reservation->starts_at?->format('Y-m-d H:i') }} → {{ $reservation->ends_at?->format('Y-m-d H:i') }}</span></div><x-status.badge :status="$reservation->status" /></div></article>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش حجوزات للأصل ده' : ($ar ? 'لا توجد حجوزات لهذا الأصل' : 'No reservations for this asset')" icon="calendar-days" />@endforelse</div></section>
            <aside class="dashboard-panel xl:col-span-5"><header class="dashboard-panel__header"><flux:heading size="lg">{{ $ar ? 'الإجراء المتاح' : 'Available action' }}</flux:heading><flux:icon.bolt class="size-5 text-primary" /></header><x-assets.actions :asset="$asset" :reservation="$asset->reservations->firstWhere('status', 'reserved')" :checkout="$asset->checkouts->first()" :asset-return="$asset->returns->first()" /></aside>
        </div>

        <section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ app()->isLocale('ar-EG') ? 'سجل الحالة غير القابل للحذف' : ($ar ? 'سجل الحالة غير القابل للحذف' : 'Immutable condition history') }}</flux:heading><flux:text size="sm">{{ $ar ? 'الفحص والضرر والفقد والصيانة والاستهلاك التشغيلي' : 'Inspection, damage, loss, maintenance, and operational depreciation' }}</flux:text></div></header><div class="dashboard-list">@forelse($asset->events as $event)<div class="dashboard-list__row"><span class="min-w-0"><strong class="block">{{ __((string) str($event->event_type)->headline()) }}</strong><small class="block text-text-muted">{{ $event->assessment }}</small></span><span class="text-end"><x-status.badge :status="$event->status" />@can('rental_assets.cost_view')<small class="mt-1 block tabular-nums">{{ $event->cost_value === null ? '—' : number_format((float) $event->cost_value, 2).' '.$event->cost_currency }}</small>@endcan</span></div>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش أحداث حالة بعد' : ($ar ? 'لا توجد أحداث حالة بعد' : 'No condition events yet')" icon="clock" />@endforelse</div></section>
    </x-app.page>
</x-layouts::app>
