<x-layouts::app :title="$mode === 'supplier' ? (str_starts_with(app()->getLocale(), 'ar') ? 'سجل فواتير الموردين' : __('Supplier invoice history')) : (str_starts_with(app()->getLocale(), 'ar') ? 'سجل تكاليف الشراء' : __('Purchase cost history'))">
    <x-app.page
        :title="$mode === 'supplier' ? (str_starts_with(app()->getLocale(), 'ar') ? 'سجل فواتير الموردين' : __('Supplier invoice history')) : (str_starts_with(app()->getLocale(), 'ar') ? 'سجل تكاليف الشراء' : __('Purchase cost history'))"
        :description="$mode === 'supplier' ? (str_starts_with(app()->getLocale(), 'ar') ? 'راجع فواتير الموردين المعتمدة داخل المخازن المسموح لك بها.' : __('Review approved supplier invoices in your authorized store scope.')) : (str_starts_with(app()->getLocale(), 'ar') ? 'تتبّع تكلفة كل منتج حسب المورد والفاتورة المعتمدة.' : __('Trace approved source invoice costs by product and supplier.'))"
        max-width="7xl"
    >
        <x-slot:actions><flux:button href="{{ route('purchasing.invoices') }}" variant="subtle" icon="arrow-left" wire:navigate>{{ __('Back to purchase invoices') }}</flux:button></x-slot:actions>
        <flux:card class="space-y-4">
            <form method="GET" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5 lg:items-end">
                <flux:select name="supplier_id" :label="str_starts_with(app()->getLocale(), 'ar') ? 'المورد' : __('Supplier')"><option value="">{{ str_starts_with(app()->getLocale(), 'ar') ? 'كل الموردين' : __('All suppliers') }}</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected($supplierId === $supplier->id)>{{ $supplier->code }} · {{ str_starts_with(app()->getLocale(), 'ar') ? $supplier->name_ar : $supplier->name_en }}</option>@endforeach</flux:select>
                <flux:select name="product_id" :label="str_starts_with(app()->getLocale(), 'ar') ? 'المنتج' : __('Product')"><option value="">{{ str_starts_with(app()->getLocale(), 'ar') ? 'كل المنتجات' : __('All products') }}</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($productId === $product->id)>{{ $product->item_code }} · {{ str_starts_with(app()->getLocale(), 'ar') ? $product->name_ar : $product->name_en }}</option>@endforeach</flux:select>
                <flux:input name="date_from" type="date" :value="$dateFrom" :label="str_starts_with(app()->getLocale(), 'ar') ? 'من تاريخ' : __('From date')" />
                <flux:input name="date_to" type="date" :value="$dateTo" :label="str_starts_with(app()->getLocale(), 'ar') ? 'إلى تاريخ' : __('To date')" />
                <flux:button type="submit" variant="primary" icon="funnel" class="inline-flex w-full min-h-11 items-center justify-center rounded-lg px-5 font-semibold shadow-sm sm:w-auto" aria-label="{{ str_starts_with(app()->getLocale(), 'ar') ? 'تطبيق الفلاتر' : __('Apply filters') }}">{{ str_starts_with(app()->getLocale(), 'ar') ? 'تطبيق الفلاتر' : __('Apply filters') }}</flux:button>
            </form>
        </flux:card>

        <x-tables.data-panel :title="$mode === 'supplier' ? (str_starts_with(app()->getLocale(), 'ar') ? 'فواتير الموردين المعتمدة' : __('Approved supplier invoices')) : (str_starts_with(app()->getLocale(), 'ar') ? 'تكاليف بنود الشراء المعتمدة' : __('Approved source-line costs'))" :description="str_starts_with(app()->getLocale(), 'ar') ? 'يعرض السجل المرتبط بفواتير شراء معتمدة فقط.' : __('Only approved, source-linked purchasing history is included.')">
            <div class="overflow-x-auto">
                @if($mode === 'supplier')
                    <table class="data-table min-w-[760px] w-full"><thead><tr><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'الفاتورة' : __('Invoice') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المورد' : __('Supplier') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المخزن' : __('Store') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'التاريخ' : __('Date') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المرجع' : __('Reference') }}</th><th class="text-end">{{ str_starts_with(app()->getLocale(), 'ar') ? 'الإجمالي' : __('Total') }}</th></tr></thead><tbody>
                    @forelse($invoices as $invoice)<tr><td class="font-mono">{{ $invoice->invoice_number }}</td><td>{{ $invoice->supplier?->code }}</td><td>{{ $invoice->store?->code }}</td><td>{{ $invoice->invoice_date?->format('Y-m-d') }}</td><td>{{ $invoice->supplier_reference }}</td><td class="text-end tabular-nums">{{ number_format((float) $invoice->total_amount, 2) }} {{ $invoice->currency_code }}</td></tr>@empty<tr><td colspan="6" class="p-0"><div class="rounded-lg border border-dashed border-zinc-300/70 bg-zinc-50/5 px-4 py-2"><x-state.empty :title="str_starts_with(app()->getLocale(), 'ar') ? 'لا توجد فواتير موردين معتمدة' : __('No approved supplier invoices found.')" :description="str_starts_with(app()->getLocale(), 'ar') ? 'طبّق فلاتر مختلفة أو اعتمد فاتورة أولاً.' : __('Adjust the filters or approve an invoice first.')" /></div></td></tr>@endforelse
                    </tbody></table>
                @else
                    <table class="data-table min-w-[880px] w-full"><thead><tr><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'الفاتورة' : __('Invoice') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المنتج' : __('Product') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المورد' : __('Supplier') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المخزن' : __('Store') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'التاريخ' : __('Date') }}</th><th class="text-end">{{ str_starts_with(app()->getLocale(), 'ar') ? 'الكمية' : __('Quantity') }}</th><th class="text-end">{{ str_starts_with(app()->getLocale(), 'ar') ? 'تكلفة الوحدة' : __('Unit cost') }}</th><th class="text-end">{{ str_starts_with(app()->getLocale(), 'ar') ? 'إجمالي البند' : __('Line total') }}</th></tr></thead><tbody>
                    @forelse($costLines as $line)<tr><td class="font-mono">{{ $line->invoice?->invoice_number }}</td><td><span class="font-mono">{{ $line->product?->item_code }}</span> · {{ str_starts_with(app()->getLocale(), 'ar') ? $line->product?->name_ar : $line->product?->name_en }}</td><td>{{ $line->invoice?->supplier?->code }}</td><td>{{ $line->invoice?->store?->code }}</td><td>{{ $line->invoice?->invoice_date?->format('Y-m-d') }}</td><td class="text-end tabular-nums">{{ $line->quantity }}</td><td class="text-end tabular-nums">{{ number_format((float) $line->unit_cost, 4) }}</td><td class="text-end tabular-nums">{{ number_format((float) $line->line_total, 4) }}</td></tr>@empty<tr><td colspan="8" class="p-0"><div class="rounded-lg border border-dashed border-zinc-300/70 bg-zinc-50/5 px-4 py-2"><x-state.empty :title="str_starts_with(app()->getLocale(), 'ar') ? 'لا توجد تكاليف شراء معتمدة' : __('No approved purchase costs found.')" :description="str_starts_with(app()->getLocale(), 'ar') ? 'طبّق فلاتر مختلفة أو اعتمد فاتورة مصدر أولاً.' : __('Adjust the filters or approve a source invoice first.')" /></div></td></tr>@endforelse
                    </tbody></table>
                @endif
            </div>
            <x-slot:footer>{{ $mode === 'supplier' ? $invoices->links() : $costLines->links() }}</x-slot:footer>
        </x-tables.data-panel>
        @if($mode === 'supplier')
            <div class="grid gap-5 xl:grid-cols-2">
                <x-tables.data-panel :title="str_starts_with(app()->getLocale(), 'ar') ? 'مرتجعات الموردين المعتمدة' : __('Approved supplier returns')" :description="str_starts_with(app()->getLocale(), 'ar') ? 'أحدث المرتجعات المرتبطة بالفواتير في النطاق المحدد.' : __('Latest referenced returns in the selected scope.')">
                    <div class="overflow-x-auto"><table class="data-table min-w-[560px] w-full"><thead><tr><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المرتجع' : __('Return') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المورد' : __('Supplier') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'فاتورة المصدر' : __('Source invoice') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'التاريخ' : __('Date') }}</th><th class="text-end">{{ str_starts_with(app()->getLocale(), 'ar') ? 'الإجمالي' : __('Total') }}</th></tr></thead><tbody>@forelse($supplierReturns as $return)<tr><td class="font-mono">{{ $return->return_number }}</td><td>{{ $return->supplier?->code }}</td><td class="font-mono">{{ $return->purchaseInvoice?->invoice_number }}</td><td>{{ $return->return_date?->format('Y-m-d') }}</td><td class="text-end tabular-nums">{{ number_format((float) $return->total_amount, 2) }}</td></tr>@empty<tr><td colspan="5"><x-state.empty :title="str_starts_with(app()->getLocale(), 'ar') ? 'لا توجد مرتجعات موردين معتمدة' : __('No approved supplier returns found.')" /></td></tr>@endforelse</tbody></table></div>
                </x-tables.data-panel>
                <x-tables.data-panel :title="str_starts_with(app()->getLocale(), 'ar') ? 'آخر أسعار الموردين' : __('Supplier last prices')" :description="str_starts_with(app()->getLocale(), 'ar') ? 'آخر أسعار الشراء المسجلة لكل منتج ومورد.' : __('Current supplier-product references derived from purchasing history.')">
                    <div class="overflow-x-auto"><table class="data-table min-w-[520px] w-full"><thead><tr><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'المنتج' : __('Product') }}</th><th>{{ str_starts_with(app()->getLocale(), 'ar') ? 'تاريخ آخر شراء' : __('Last purchase date') }}</th><th class="text-end">{{ str_starts_with(app()->getLocale(), 'ar') ? 'آخر سعر' : __('Last price') }}</th></tr></thead><tbody>@forelse($lastPrices as $link)<tr><td><span class="font-mono">{{ $link->product?->item_code }}</span> · {{ str_starts_with(app()->getLocale(), 'ar') ? $link->product?->name_ar : $link->product?->name_en }}</td><td>{{ $link->last_purchase_date?->format('Y-m-d') }}</td><td class="text-end tabular-nums">{{ number_format((float) $link->last_purchase_price, 4) }}</td></tr>@empty<tr><td colspan="3"><x-state.empty :title="str_starts_with(app()->getLocale(), 'ar') ? 'اختر مورداً لديه أسعار شراء مسجلة' : __('Select a supplier with recorded last prices.')" /></td></tr>@endforelse</tbody></table></div>
                </x-tables.data-panel>
            </div>
        @endif
    </x-app.page>
</x-layouts::app>
