<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ str_starts_with(app()->getLocale(), 'ar') ? 'rtl' : 'ltr' }}">
<head><meta charset="utf-8"><style>
@include('pages.exports.partials.cairo-pdf-styles')
body{font-family:{{ str_starts_with(app()->getLocale(),'ar') ? "'Cairo PDF Arabic'" : "'Cairo PDF Latin'" }};font-size:10px;color:#111827;direction:{{ str_starts_with(app()->getLocale(),'ar') ? 'rtl' : 'ltr' }}}
h1{font-size:19px;margin:0}.muted{color:#6b7280}.header,.summary{display:table;width:100%;table-layout:fixed}.cell{display:table-cell;width:50%;vertical-align:top;padding:7px;border:1px solid #d1d5db}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #d1d5db;padding:6px;text-align:start}.num{text-align:end;direction:ltr}.status{font-weight:700}.approval{margin-top:5px;padding:5px;border-bottom:1px solid #e5e7eb}
</style></head><body>
<div class="header"><div class="cell"><h1>{{ __('Purchase Order') }}</h1><div class="muted">{{ $order->branch?->company?->legal_name ?: $order->branch?->company?->name_en }}</div></div><div class="cell"><strong>{{ $order->po_number }}</strong><br>{{ __('Status') }}: <span class="status">{{ __($order->workflowStatusLabel()) }}</span><br>{{ __('Next action') }}: {{ __($order->nextAction()) }}<br>{{ __('Receiving status') }}: {{ __($order->receivingState()) }}</div></div>
<div class="summary"><div class="cell"><strong>{{ __('Branch') }}:</strong> {{ str_starts_with(app()->getLocale(),'ar') ? $order->branch?->name_ar : $order->branch?->name_en }}<br><strong>{{ __('Supplier') }}:</strong> {{ str_starts_with(app()->getLocale(),'ar') ? $order->supplier?->name_ar : $order->supplier?->name_en }}<br><strong>{{ __('Supplier code') }}:</strong> {{ $order->supplier?->code }}</div><div class="cell"><strong>{{ __('Receiving Store / Warehouse') }}:</strong> {{ str_starts_with(app()->getLocale(),'ar') ? $order->store?->name_ar : $order->store?->name_en }}<br><strong>{{ __('Order Date') }}:</strong> {{ $order->order_date?->format('Y-m-d') }}<br><strong>{{ __('Expected Delivery') }}:</strong> {{ $order->expected_delivery_date?->format('Y-m-d') ?: '—' }}</div></div>
<table><thead><tr><th>#</th><th>{{ __('Product') }}</th><th>{{ __('Internal code') }}</th><th class="num">{{ __('Quantity') }}</th><th class="num">{{ __('Unit cost') }}</th><th class="num">{{ __('Line total') }}</th></tr></thead><tbody>@foreach($order->lines as $line)<tr><td>{{ $line->line_number }}</td><td>{{ str_starts_with(app()->getLocale(),'ar') ? $line->product?->name_ar : $line->product?->name_en }}</td><td>{{ $line->product?->item_code }}</td><td class="num">{{ $line->quantity_ordered }}</td><td class="num">{{ number_format((float)$line->unit_cost,4) }}</td><td class="num">{{ number_format((float)$line->subtotal,4) }}</td></tr>@endforeach</tbody></table>
<p class="num"><strong>{{ __('Total') }}: {{ number_format((float)$order->total_amount,4) }}</strong></p>
@if($order->notes)<p><strong>{{ __('Notes') }}:</strong> {{ $order->notes }}</p>@endif
<h2>{{ __('Approval history') }}</h2>@forelse($approvals as $approval)<div class="approval">{{ __($approval->approval_state->value) }} · {{ $approval->created_at?->format('Y-m-d H:i') }} · {{ $approval->decision_note ?: '—' }}</div>@empty<p class="muted">{{ __('No approval history yet.') }}</p>@endforelse
</body></html>
