<!doctype html>
@php($receiptProfile = $receiptProfile ?? ['paper_size' => 'A4', 'printer' => null, 'fallback_message' => ''])
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ str_starts_with(app()->getLocale(), 'ar') ? 'rtl' : 'ltr' }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ __('Invoice') }} {{ $sale->document_number }}</title>@vite(['resources/css/app.css'])<style>@page{size:A4;margin:14mm}@media print{.no-print{display:none!important}}</style></head>
<body class="bg-white text-zinc-900"><main class="mx-auto max-w-4xl p-6">
    @if ($receiptPreview ?? false)<aside class="no-print mb-6 rounded-xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-cyan-950" role="status"><p class="font-bold">{{ __('Receipt preview') }}</p><p class="mt-1">{{ $receiptProfile['fallback_message'] }}</p><p class="mt-1 text-xs">{{ __('Printer') }}: {{ $receiptProfile['printer']?->name ?? __('Browser print') }} · {{ __('Paper size') }}: {{ $receiptProfile['paper_size'] }} · {{ __('Language') }}: {{ __($receiptProfile['language']) }}</p><div class="mt-3 flex flex-wrap gap-2"><button type="button" onclick="window.print()" class="min-h-10 rounded-lg bg-cyan-700 px-4 font-bold text-white">{{ __('Print') }}</button><form method="POST" action="{{ route('pos.orders.store') }}">@csrf<input type="hidden" name="creation_token" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><button type="submit" class="min-h-10 rounded-lg border border-cyan-300 bg-white px-4 font-bold">{{ __('New order') }}</button></form><a href="{{ route('sales.show', $sale) }}" class="inline-flex min-h-10 items-center rounded-lg border border-cyan-300 bg-white px-4 font-bold">{{ __('View current order') }}</a></div></aside>@endif
    <header class="flex items-start justify-between gap-6 border-b border-zinc-300 pb-5"><div><h1 class="text-2xl font-bold">{{ str_starts_with(app()->getLocale(), 'ar') ? ($sale->store->company->name_ar ?: $sale->store->company->name_en) : $sale->store->company->name_en }}</h1>@if(filled($receiptProfile['printer']?->printTemplate?->header_text))<p class="mt-1 text-sm">{{ $receiptProfile['printer']->printTemplate->header_text }}</p>@endif<p class="mt-1 text-sm">{{ str_starts_with(app()->getLocale(), 'ar') ? $sale->branch->name_ar : $sale->branch->name_en }} · {{ str_starts_with(app()->getLocale(), 'ar') ? $sale->store->name_ar : $sale->store->name_en }}</p><p class="mt-1 text-sm">{{ __('Customer') }}: {{ $sale->customer ? (str_starts_with(app()->getLocale(), 'ar') ? $sale->customer->name_ar : $sale->customer->name_en) : __('Walk-in customer') }}</p></div><div class="text-end"><div class="text-sm text-zinc-500">{{ __('Sales invoice') }}</div><div class="font-mono text-lg font-bold">{{ $sale->document_number }}</div><div class="text-sm">{{ $sale->approved_at?->format('Y-m-d H:i') }}</div></div></header>
    <table class="mt-6 w-full text-sm">
        <thead><tr class="border-b border-zinc-300"><th class="py-2 text-start">{{ __('Product') }}</th><th class="py-2 text-end">{{ __('Quantity') }}</th><th class="py-2 text-end">{{ __('Original price') }}</th><th class="py-2 text-end">{{ __('Selling price') }}</th><th class="py-2 text-end">{{ __('Discount') }}</th><th class="py-2 text-end">{{ __('Line total') }}</th></tr></thead>
        <tbody>
            @foreach ($sale->lines as $line)
                <tr class="border-b border-zinc-100">
                    <td class="py-3">{{ str_starts_with(app()->getLocale(), 'ar') ? $line->name_ar : $line->name_en }}<div class="text-xs text-zinc-500">{{ $line->item_code }}@if ($line->is_open_price)<span class="ms-2">· {{ __('Open price') }}: {{ $line->open_price_reason }}</span>@endif</div><x-variant-snapshot :snapshot="$line->variant_snapshot" class="mt-1 block" /></td>
                    <td class="py-3 text-end tabular-nums">{{ $line->quantity }}</td><td class="py-3 text-end tabular-nums">{{ number_format((float) \App\Modules\Retail\Support\DecimalMoney::round((string) ($line->reference_price ?? $line->unit_price)), 2) }} {{ $sale->currency_code }}</td><td class="py-3 text-end tabular-nums">{{ number_format((float) \App\Modules\Retail\Support\DecimalMoney::round((string) $line->unit_price), 2) }} {{ $sale->currency_code }}</td><td class="py-3 text-end tabular-nums">{{ number_format((float) $line->discount_amount, 2) }} {{ $sale->currency_code }}</td><td class="py-3 text-end font-semibold tabular-nums">{{ number_format((float) $line->net_amount, 2) }} {{ $sale->currency_code }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="ms-auto mt-6 w-full max-w-sm space-y-2 text-sm"><div class="flex justify-between"><span>{{ __('Invoice subtotal') }}</span><span>{{ $sale->subtotal }}</span></div><div class="flex justify-between"><span>{{ __('Discount') }}</span><span>{{ $sale->discount_total }}</span></div><div class="flex justify-between"><span>{{ __('Tax') }}@if ($sale->tax_applicable) ({{ $sale->tax_rate_snapshot }}%)@endif</span><span>{{ $sale->tax_total }}</span></div><div class="flex justify-between border-t border-zinc-300 pt-2 font-semibold"><span>{{ __('Invoice total') }}</span><span>{{ $sale->total }} {{ $sale->currency_code }}</span></div><div class="flex justify-between"><span>{{ __('Cash rounding') }}</span><span>{{ $sale->cash_rounding_amount }}</span></div><div class="flex justify-between border-t border-zinc-300 pt-2 text-base font-bold"><span>{{ __('Payable total') }}</span><span>{{ $sale->payable_total }} {{ $sale->currency_code }}</span></div><div class="flex justify-between"><span>{{ __('Applied total') }}</span><span>{{ $sale->paid_total }}</span></div><div class="flex justify-between"><span>{{ __('Change total') }}</span><span>{{ $sale->change_total }}</span></div></div>
    <section class="mt-8 border-t border-zinc-300 pt-4"><h2 class="font-semibold">{{ __('Payments') }}</h2><div class="mt-2 overflow-hidden rounded-lg border border-zinc-200"><table class="w-full text-sm"><thead class="bg-zinc-50"><tr><th class="p-2 text-start">{{ __('Method') }}</th><th class="p-2 text-end">{{ __('Applied amount') }}</th><th class="p-2 text-end">{{ __('Tendered amount') }}</th><th class="p-2 text-end">{{ __('Change') }}</th></tr></thead><tbody>@foreach ($sale->payments as $payment)<tr class="border-t border-zinc-200"><td class="p-2">{{ str_starts_with(app()->getLocale(), 'ar') ? $payment->paymentMethod?->name_ar : $payment->paymentMethod?->name_en }}</td><td class="p-2 text-end">{{ $payment->amount }} {{ $sale->currency_code }}</td><td class="p-2 text-end">{{ $payment->tendered_amount ?? '—' }}</td><td class="p-2 text-end">{{ $payment->change_amount }}</td></tr>@endforeach</tbody></table></div></section>
@if(filled($receiptProfile['printer']?->printTemplate?->footer_text))<footer class="mt-8 border-t border-zinc-300 pt-4 text-center text-sm">{{ $receiptProfile['printer']->printTemplate->footer_text }}</footer>@endif</main>@unless($receiptPreview ?? false)<script>window.addEventListener('load', () => window.print());</script>@endunless</body></html>
