<!doctype html>
@php($receiptProfile = $receiptProfile ?? ['paper_size' => '80mm', 'printer' => null, 'fallback_message' => ''])
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ str_starts_with(app()->getLocale(), 'ar') ? 'rtl' : 'ltr' }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ __('Receipt') }} {{ $sale->document_number }}</title><style>@page{size:{{ ($receiptProfile['paper_size'] ?? '80mm') === '58mm' ? '58mm' : '80mm' }} auto;margin:4mm}*{box-sizing:border-box}body{width:{{ ($receiptProfile['paper_size'] ?? '80mm') === '58mm' ? '50mm' : '72mm' }};margin:0 auto;font-family:Arial,sans-serif;color:#111;font-size:11px}h1,p{margin:0}.center{text-align:center}.row{display:flex;justify-content:space-between;gap:8px}.rule{border-top:1px dashed #333;margin:8px 0}.line{margin:7px 0}.bold{font-weight:700}.small{font-size:9px;color:#444}.toolbar{width:min(94vw,720px);margin:12px auto;padding:12px;border:1px solid #ddd;border-radius:10px;background:#fff;font-size:13px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}.actions button,.actions a{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 12px;border:1px solid #aaa;border-radius:8px;background:#fff;color:#111;text-decoration:none;font-weight:700;cursor:pointer}.actions button:first-child{background:#0e7490;color:#fff;border-color:#0e7490}@media print{body{width:auto}.no-print{display:none!important}}</style></head>
<body>
    @if ($receiptPreview ?? false)<aside class="toolbar no-print" role="status"><strong>{{ __('Receipt preview') }}</strong><p>{{ $receiptProfile['fallback_message'] }}</p><p class="small">{{ __('Printer') }}: {{ $receiptProfile['printer']?->name ?? __('Browser print') }} · {{ __('Paper size') }}: {{ $receiptProfile['paper_size'] }} · {{ __('Language') }}: {{ __($receiptProfile['language']) }}</p><div class="actions"><button type="button" onclick="window.print()">{{ __('Print') }}</button><form method="POST" action="{{ route('pos.orders.store') }}">@csrf<input type="hidden" name="creation_token" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><button type="submit">{{ __('New order') }}</button></form><a href="{{ route('sales.show', $sale) }}">{{ __('View current order') }}</a></div></aside>@endif
    <header class="center"><h1>{{ str_starts_with(app()->getLocale(), 'ar') ? ($sale->store->company->name_ar ?: $sale->store->company->name_en) : $sale->store->company->name_en }}</h1>@if(filled($receiptProfile['printer']?->printTemplate?->header_text))<p>{{ $receiptProfile['printer']->printTemplate->header_text }}</p>@endif<p>{{ str_starts_with(app()->getLocale(), 'ar') ? $sale->branch->name_ar : $sale->branch->name_en }} · {{ str_starts_with(app()->getLocale(), 'ar') ? $sale->store->name_ar : $sale->store->name_en }}</p><p class="small">{{ __('Customer') }}: {{ $sale->customer ? (str_starts_with(app()->getLocale(), 'ar') ? $sale->customer->name_ar : $sale->customer->name_en) : __('Walk-in customer') }}</p><p class="small">{{ $sale->document_number }} · {{ $sale->approved_at?->format('Y-m-d H:i') }}</p></header>
    <div class="rule"></div>
    @foreach ($sale->lines as $line)
        <div class="line">
            <div class="bold">{{ str_starts_with(app()->getLocale(), 'ar') ? $line->name_ar : $line->name_en }}</div>
            <div class="small">{{ $line->item_code }}</div>
            <x-variant-snapshot :snapshot="$line->variant_snapshot" class="small" />
            <div class="row"><span>{{ $line->quantity }} × {{ __('Selling price') }} {{ \App\Modules\Retail\Support\DecimalMoney::round((string) $line->unit_price) }}</span><span>{{ $line->gross_amount }}</span></div>
            @if ($line->is_open_price)<div class="small">{{ __('Reference') }} {{ \App\Modules\Retail\Support\DecimalMoney::round((string) ($line->reference_price ?? $line->unit_price)) }} · {{ __('Open price') }} · {{ $line->open_price_reason }}</div>@endif
            @if (bccomp((string) $line->discount_amount, '0', 2) > 0)<div class="row small"><span>{{ __('Discount') }}</span><span>-{{ $line->discount_amount }}</span></div>@endif
            <div class="row"><span>{{ __('Line total') }}</span><span class="bold">{{ $line->net_amount }}</span></div>
        </div>
    @endforeach
    <div class="rule"></div>
    <div class="row"><span>{{ __('Invoice subtotal') }}</span><span>{{ $sale->subtotal }}</span></div><div class="row"><span>{{ __('Discount') }}</span><span>{{ $sale->discount_total }}</span></div><div class="row"><span>{{ __('Tax') }}</span><span>{{ $sale->tax_total }}</span></div><div class="row bold"><span>{{ __('Invoice total') }}</span><span>{{ $sale->total }} {{ $sale->currency_code }}</span></div><div class="row"><span>{{ __('Cash rounding') }}</span><span>{{ $sale->cash_rounding_amount }}</span></div><div class="row bold"><span>{{ __('Payable total') }}</span><span>{{ $sale->payable_total }} {{ $sale->currency_code }}</span></div><div class="row"><span>{{ __('Applied total') }}</span><span>{{ $sale->paid_total }}</span></div><div class="row"><span>{{ __('Change total') }}</span><span>{{ $sale->change_total }}</span></div>
    <div class="rule"></div><p class="bold">{{ __('Payments') }}</p>
    @foreach ($sale->payments as $payment)<div class="line"><div class="row"><span class="bold">{{ str_starts_with(app()->getLocale(), 'ar') ? $payment->paymentMethod?->name_ar : $payment->paymentMethod?->name_en }}</span><span>{{ __('Applied') }} {{ $payment->amount }}</span></div>@if ($payment->tendered_amount !== null)<div class="row small"><span>{{ __('Tendered') }}</span><span>{{ $payment->tendered_amount }}</span></div>@endif@if (bccomp((string) $payment->change_amount, '0', 2) > 0)<div class="row small"><span>{{ __('Change') }}</span><span>{{ $payment->change_amount }}</span></div>@endif</div>@endforeach
    <div class="rule"></div><p class="center small">{{ $receiptProfile['printer']?->printTemplate?->footer_text ?: __('Thank you') }}</p>@unless($receiptPreview ?? false)<script>window.addEventListener('load',()=>window.print())</script>@endunless
</body></html>
