<?php

return [
    'sales' => ['landing_route' => 'sales.index', 'permission' => 'pos_sales.view', 'kpis' => ['today_sales', 'invoice_count', 'open_shifts', 'suspended_sales'], 'alerts' => ['offline_conflicts', 'shift_variances'], 'quick_actions' => ['pos', 'sales.invoices', 'pos.shift'], 'activity' => ['recent_sales'], 'primary_views' => ['sales.invoices', 'reports.sales']],
    'purchasing' => ['landing_route' => 'purchasing.orders', 'permission' => 'purchase_orders.view', 'kpis' => ['pending_orders', 'today_purchases', 'pending_returns', 'pending_approvals'], 'alerts' => ['overdue_receiving', 'supplier_returns'], 'quick_actions' => ['purchasing.orders', 'purchasing.invoices', 'purchasing.returns'], 'activity' => ['recent_orders', 'recent_invoices'], 'primary_views' => ['purchasing.orders', 'purchasing.invoices']],
    'inventory' => ['landing_route' => 'inventory.index', 'permission' => 'inventory_stock_card.view', 'kpis' => ['visible_products', 'stock_on_hand', 'low_stock', 'out_of_stock', 'pending_transfers', 'active_counts', 'pending_adjustments'], 'alerts' => ['low_stock', 'out_of_stock', 'transfer_differences'], 'quick_actions' => ['inventory.balances', 'inventory.movements', 'inventory.transfers', 'inventory.counts', 'inventory.adjustments', 'pricing.labels'], 'activity' => ['recent_stock_movements'], 'primary_views' => ['inventory.balances', 'inventory.movements']],
    'catalog_pricing' => ['landing_route' => 'catalog.products', 'permission' => 'products_categories_brands.view', 'kpis' => ['active_products', 'inactive_products', 'barcode_coverage', 'price_coverage'], 'alerts' => ['missing_barcodes', 'missing_prices'], 'quick_actions' => ['catalog.products', 'catalog.categories', 'pricing.index', 'pricing.labels'], 'activity' => ['recent_products', 'recent_price_changes'], 'primary_views' => ['catalog.products', 'pricing.index']],
    'customers' => ['landing_route' => 'customers.index', 'permission' => 'customers.view', 'kpis' => ['active_customers', 'new_customers', 'loyalty_activity', 'wallet_exceptions'], 'alerts' => ['consent_review', 'duplicate_review'], 'quick_actions' => ['customers.index', 'customers.create', 'customers.groups.index'], 'activity' => ['recent_customers'], 'primary_views' => ['customers.index', 'reports.customers']],
    'suppliers' => ['landing_route' => 'catalog.suppliers', 'permission' => 'suppliers.view', 'kpis' => ['active_suppliers', 'open_orders', 'pending_returns', 'contact_readiness'], 'alerts' => ['missing_contacts', 'supplier_exceptions'], 'quick_actions' => ['catalog.suppliers', 'purchasing.orders', 'purchasing.returns'], 'activity' => ['recent_suppliers', 'recent_orders'], 'primary_views' => ['catalog.suppliers', 'purchasing.history.suppliers']],
    'parties' => ['landing_route' => 'parties.bookings.index', 'permission' => 'party_bookings_invoices.view', 'kpis' => ['upcoming_bookings', 'open_orders', 'unsettled_invoices', 'schedule_conflicts'], 'alerts' => ['booking_conflicts', 'settlement_exceptions'], 'quick_actions' => ['parties.bookings.index', 'parties.orders.index', 'parties.calendar'], 'activity' => ['recent_bookings'], 'primary_views' => ['parties.bookings.index', 'parties.orders.index']],
    'assets' => ['landing_route' => 'party.assets.index', 'landing_parameters' => ['mode' => 'dashboard'], 'permission' => 'rental_assets.view', 'kpis' => ['active_assets', 'available_assets', 'reserved_assets', 'checked_out_assets', 'inspection_queue', 'maintenance_assets'], 'alerts' => ['overdue_returns', 'pending_asset_events', 'condition_exceptions'], 'quick_actions' => ['party.assets.index', 'parties.calendar', 'parties.orders.index'], 'activity' => ['upcoming_reservations', 'recent_returns', 'recent_asset_events'], 'primary_views' => ['asset_catalog', 'availability_calendar', 'rental_operations', 'condition_history']],
    'reports' => ['landing_route' => 'reports.index', 'permission' => 'dashboard_reports.view', 'kpis' => ['available_reports', 'queued_exports', 'completed_exports', 'failed_exports'], 'alerts' => ['failed_exports'], 'quick_actions' => ['reports.sales', 'reports.purchasing', 'reports.inventory', 'exports.index'], 'activity' => ['recent_exports'], 'primary_views' => ['reports.index', 'exports.index']],
    'administration' => ['landing_route' => 'admin.settings', 'permission' => 'company_settings.view', 'kpis' => ['setup_readiness', 'active_locations', 'active_users', 'pending_approvals'], 'alerts' => ['system_health', 'configuration_gaps'], 'quick_actions' => ['admin.settings', 'admin.branches', 'admin.authorization-baseline', 'admin.audit'], 'activity' => ['recent_audit_events'], 'primary_views' => ['admin.settings', 'admin.audit']],
];
