@php
    $isArabic = str_starts_with(app()->getLocale(), 'ar');
    $money = fn($value) => number_format((float)$value, 2).' '.$currencyCode;
    $metrics = $salesAnalysis['metrics'];
    $base = ['store_id'=>request('store_id'),'product_id'=>request('product_id'),'category_id'=>request('category_id'),'payment_method_id'=>request('payment_method_id')];
    $today = now('Africa/Cairo');
@endphp
<section class="rounded-2xl border border-teal-200 bg-white shadow-sm dark:border-teal-900 dark:bg-zinc-900" aria-labelledby="customer-sales-analysis-heading">
    <header class="border-b border-teal-100 px-5 py-4 dark:border-teal-900"><flux:heading id="customer-sales-analysis-heading" size="lg">{{ __('Sales Analysis') }}</flux:heading><flux:text class="mt-1 text-sm">{{ __('Period sales use historical transaction values. Current balance is shown separately and includes later receipts and approved account activity.') }}</flux:text></header>
    <div class="border-b border-teal-100 p-5 dark:border-teal-900">
        <div class="mb-3 flex flex-wrap gap-2">
            <flux:button size="sm" href="{{ route('customers.show',[$customer,...array_filter([...$base,'date_from'=>$today->toDateString(),'date_to'=>$today->toDateString()])]) }}">{{ __('Today') }}</flux:button>
            <flux:button size="sm" href="{{ route('customers.show',[$customer,...array_filter([...$base,'date_from'=>$today->startOfWeek()->toDateString(),'date_to'=>$today->toDateString()])]) }}">{{ __('This Week') }}</flux:button>
            <flux:button size="sm" href="{{ route('customers.show',[$customer,...array_filter([...$base,'date_from'=>$today->startOfMonth()->toDateString(),'date_to'=>$today->toDateString()])]) }}">{{ __('This Month') }}</flux:button>
            <flux:button size="sm" href="{{ route('customers.show',[$customer,...array_filter([...$base,'date_from'=>$today->subDays(29)->toDateString(),'date_to'=>$today->toDateString()])]) }}">{{ __('Last 30 Days') }}</flux:button>
        </div>
        <form method="GET" action="{{ route('customers.show',$customer) }}" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <flux:input type="date" name="date_from" :label="__('From Date')" :value="$salesAnalysis['filters']['date_from']" required />
            <flux:input type="date" name="date_to" :label="__('To Date')" :value="$salesAnalysis['filters']['date_to']" required />
            @if($salesStores->count() > 1)<flux:select name="store_id" :label="__('Store')"><option value="">{{ __('All stores') }}</option>@foreach($salesStores as $option)<option value="{{ $option->id }}" @selected((string)$salesAnalysis['filters']['store_id']===(string)$option->id)>{{ $isArabic?$option->name_ar:$option->name_en }}</option>@endforeach</flux:select>@endif
            <flux:select name="product_id" :label="__('Product')"><option value="">{{ __('All products') }}</option>@foreach($salesProducts as $option)<option value="{{ $option->id }}" @selected((string)$salesAnalysis['filters']['product_id']===(string)$option->id)>{{ $option->item_code }} · {{ $isArabic?$option->name_ar:$option->name_en }}</option>@endforeach</flux:select>
            <flux:select name="category_id" :label="__('Category')"><option value="">{{ __('All categories') }}</option>@foreach($salesCategories as $option)<option value="{{ $option->id }}" @selected((string)$salesAnalysis['filters']['category_id']===(string)$option->id)>{{ $isArabic?$option->name_ar:$option->name_en }}</option>@endforeach</flux:select>
            @if($salesPaymentMethods->isNotEmpty())<flux:select name="payment_method_id" :label="__('Payment Type')"><option value="">{{ __('All payment types') }}</option>@foreach($salesPaymentMethods as $option)<option value="{{ $option->id }}" @selected((string)$salesAnalysis['filters']['payment_method_id']===(string)$option->id)>{{ $option->code }} · {{ $isArabic?$option->name_ar:$option->name_en }}</option>@endforeach</flux:select>@endif
            <div class="flex items-end gap-2"><flux:button type="submit" variant="primary">{{ __('Apply') }}</flux:button><flux:button href="{{ route('customers.show',$customer) }}" variant="subtle">{{ __('Reset') }}</flux:button></div>
        </form>
    </div>
    <div class="p-5"><div class="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p class="text-xs font-semibold uppercase tracking-wide text-primary">{{ __('Period Metrics') }}</p><p class="text-sm text-text-muted">{{ $salesAnalysis['filters']['date_from'] }} — {{ $salesAnalysis['filters']['date_to'] }}</p></div><flux:badge color="emerald">{{ __('Approved sales only') }}</flux:badge></div><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
        @foreach([['Gross Sales',$metrics['gross_sales']],['Returns',$metrics['returns']],['Net Sales',$metrics['net_sales']],['Discounts',$metrics['discounts']],['Collected at Sale',$metrics['collected_at_sale']],['Credit Created',$metrics['credit_created']],['Invoice Count',$metrics['invoice_count']],['Average Invoice',$metrics['average_invoice']]] as [$label,$value])<div class="rounded-xl bg-surface-muted p-3"><p class="text-xs text-text-muted">{{ __($label) }}</p><p class="mt-1 font-bold tabular-nums" dir="ltr">{{ $label==='Invoice Count'?number_format((int)$value):$money($value) }}</p></div>@endforeach
        <div class="rounded-xl bg-sky-50 p-3 ring-1 ring-sky-200 dark:bg-sky-950/30 dark:ring-sky-800"><p class="text-xs font-semibold text-sky-700 dark:text-sky-300">{{ __('Current Customer Balance') }}</p><p class="mt-1 font-bold tabular-nums" dir="ltr">{{ $money($currentBalance) }}</p><p class="mt-1 text-[11px] text-text-muted">{{ __('Not a period-ending balance') }}</p></div>
        <div class="rounded-xl bg-surface-muted p-3"><p class="text-xs text-text-muted">{{ __('Last Purchase') }}</p><p class="mt-1 font-semibold" dir="ltr">{{ $salesAnalysis['last_purchase_at'] ? \Carbon\CarbonImmutable::parse($salesAnalysis['last_purchase_at'],'UTC')->setTimezone('Africa/Cairo')->format('Y-m-d H:i') : '—' }}</p></div>
    </div></div>
    <div class="border-t border-teal-100 dark:border-teal-900"><div class="px-5 py-4"><flux:heading size="base">{{ __('Customer Invoices for Selected Period') }}</flux:heading></div><div class="responsive-resource-table"><table class="data-table w-full"><thead><tr><th>{{ __('Invoice') }}</th><th>{{ __('Date') }}</th><th>{{ __('Store') }}</th><th>{{ __('Cashier') }}</th><th>{{ __('Gross') }}</th><th>{{ __('Discount') }}</th><th>{{ __('Net') }}</th><th>{{ __('Paid') }}</th><th>{{ __('Outstanding') }}</th><th>{{ __('Payment Status') }}</th><th>{{ __('Sale Status') }}</th><th>{{ __('View') }}</th></tr></thead><tbody>@forelse($salesAnalysis['invoices'] as $sale)<tr><td>{{ $sale->document_number }}</td><td>{{ \Carbon\CarbonImmutable::parse($sale->approved_at,'UTC')->setTimezone('Africa/Cairo')->format('Y-m-d H:i') }}</td><td>{{ $isArabic?$sale->store_name_ar:$sale->store_name_en }}</td><td>{{ $sale->cashier }}</td><td dir="ltr">{{ $money($sale->subtotal) }}</td><td dir="ltr">{{ $money($sale->discount_total) }}</td><td dir="ltr">{{ $money(bcsub((string)$sale->subtotal,(string)$sale->discount_total,2)) }}</td><td dir="ltr">{{ $money($sale->paid) }}</td><td dir="ltr">{{ $money($sale->outstanding) }}</td><td><x-status.badge :status="$sale->payment_status" /></td><td><x-status.badge :status="$sale->status" /></td><td><flux:button size="sm" href="{{ route('sales.show',$sale->id) }}">{{ __('View') }}</flux:button></td></tr>@empty<tr><td colspan="12"><x-state.empty :title="__('No customer sales in the selected period')" /></td></tr>@endforelse</tbody></table></div>@if($salesAnalysis['invoices']->hasPages())<div class="border-t border-teal-100 px-5 py-4 dark:border-teal-900">{{ $salesAnalysis['invoices']->links() }}</div>@endif</div>
    <div class="border-t border-teal-100 dark:border-teal-900"><div class="px-5 py-4"><flux:heading size="base">{{ __('Most Purchased Products') }}</flux:heading></div><div class="responsive-resource-table"><table class="data-table w-full"><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Unit') }}</th><th>{{ __('Quantity') }}</th><th>{{ __('Returns') }}</th><th>{{ __('Net Quantity') }}</th><th>{{ __('Net Sales') }}</th><th>{{ __('Average Selling Price') }}</th></tr></thead><tbody>@forelse($salesAnalysis['products'] as $row)<tr><td>{{ $isArabic?$row['name_ar']:$row['name_en'] }}</td><td>{{ $row['unit_code'] }}</td><td dir="ltr">{{ $row['sold_quantity'] }}</td><td dir="ltr">{{ $row['returned_quantity'] }}</td><td dir="ltr">{{ $row['net_quantity'] }}</td><td dir="ltr">{{ $money($row['net_sales']) }}</td><td dir="ltr">{{ $money($row['average_price']) }}</td></tr>@empty<tr><td colspan="7"><x-state.empty :title="__('No customer product sales in the selected period')" /></td></tr>@endforelse</tbody></table></div></div>
</section>
