<x-layouts::pos :title="__('POS Checkout')" :store="$store" :shift="$shift">
    <div class="mx-auto flex w-full max-w-[118rem] flex-col gap-2" data-pos-workstation>
        <header class="flex min-h-10 flex-wrap items-center justify-between gap-2 border-b border-zinc-200 pb-2 dark:border-zinc-800" data-guide="pos-header"><div class="flex min-w-0 items-center gap-2"><span class="flex size-8 shrink-0 items-center justify-center rounded-lg bg-cyan-700 text-white"><flux:icon name="shopping-cart" class="size-4" /></span><h1 class="text-base font-black">{{ __('Point of sale') }}</h1></div><nav class="flex flex-wrap items-center gap-1" aria-label="{{ __('POS tools') }}">@can('suspended_sales.view')<flux:button href="{{ route('pos.suspended') }}" size="sm" variant="ghost" icon="pause-circle" wire:navigate>{{ __('Held sales') }}</flux:button>@endcan @can('shifts_cash_movements.view')<flux:button href="{{ route('pos.shift') }}" size="sm" variant="ghost" icon="banknotes" wire:navigate>{{ __('Shifts & collections') }}</flux:button>@endcan <flux:button href="{{ route('sales.index') }}" size="sm" variant="ghost" icon="receipt-percent" wire:navigate>{{ __('Sales') }}</flux:button></nav></header>
        @if(!$context->isReady())<flux:callout variant="warning" icon="exclamation-triangle"><div class="flex items-center justify-between gap-3"><span>{{ $context->disabledReason }}</span>@can('shifts_cash_movements.view')<flux:button href="{{ route('pos.shift') }}" size="sm" variant="primary" wire:navigate>{{ __('Open shift') }}</flux:button>@endcan</div></flux:callout>@endif
        @if(session('success'))<div role="status" aria-live="polite" class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"><flux:icon name="check-circle" class="me-1 inline size-4" />{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-800 dark:bg-rose-950/30 dark:text-rose-200">{{ $errors->first() }}</div>@elseif($previewError)<div class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-800">{{ $previewError }}</div>@endif

        <main class="grid min-w-0 items-start gap-2 lg:grid-cols-[minmax(0,1.45fr)_minmax(19rem,.75fr)] xl:grid-cols-[minmax(31rem,1.55fr)_minmax(18rem,.78fr)_minmax(19rem,.72fr)]" aria-label="{{ __('Point of sale workspace') }}">
            <livewire:pos.product-browser :key="'products-'.($activeOrder?->uuid ?? 'disabled')" />
            <livewire:pos.cart :key="'cart-'.($activeOrder?->uuid ?? 'disabled')" />
            <aside class="min-w-0 space-y-2 lg:col-span-2 xl:col-span-1 xl:sticky xl:top-2 xl:max-h-[calc(100vh-5.5rem)] xl:overflow-y-auto" aria-label="{{ __('Customer, payment and order summary') }}">
                @can('customers.view')<section class="rounded-xl bg-white p-3 shadow-xs ring-1 ring-zinc-200 dark:bg-zinc-900 dark:ring-zinc-800" aria-labelledby="pos-customer-heading"><div class="flex items-center justify-between"><h2 id="pos-customer-heading" class="text-sm font-extrabold">{{ __('Customer') }}</h2>@if($selectedCustomer)<form method="POST" action="{{ route('pos.customer.clear') }}">@csrf<button type="submit" class="rounded px-2 py-1 text-xs font-bold text-rose-600 hover:bg-rose-50">{{ __('Remove') }}</button></form>@endif</div>
                    @if($customerPolicyError)<p class="mt-2 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-900">{{ $customerPolicyError }}</p>@endif
                    @if($selectedCustomer)<div class="mt-2 rounded-lg bg-cyan-50 px-3 py-2 dark:bg-cyan-950/25" data-selected-customer><strong class="block truncate text-xs">{{ str_starts_with(app()->getLocale(), 'ar')?$selectedCustomer->name_ar:$selectedCustomer->name_en }}</strong><span class="text-[11px] text-zinc-500" dir="ltr">{{ $selectedCustomer->phone_display }}</span></div>@endif
                    <form method="GET" action="{{ route('pos') }}" class="mt-2" x-data="{timer:null}" x-on:input.debounce.300ms="$el.requestSubmit()"><label for="pos-customer-search" class="sr-only">{{ __('Search customer by name, phone, code, or email') }}</label><div class="relative"><flux:icon name="magnifying-glass" class="pointer-events-none absolute start-3 top-1/2 z-10 size-4 -translate-y-1/2 text-zinc-400" /><input id="pos-customer-search" name="customer_q" value="{{ $customerQuery }}" autocomplete="off" dir="auto" class="block h-10 w-full rounded-lg border-zinc-300 bg-zinc-50 ps-9 pe-3 text-sm focus:border-cyan-600 focus:ring-cyan-600 dark:border-zinc-700 dark:bg-zinc-950" placeholder="{{ __('Name, phone, email, or customer code') }}"></div></form>
                    @can('customers.create')@if($customerPurposes!==[])<button type="button" onclick="document.getElementById('pos-new-customer').showModal()" class="mt-2 inline-flex h-9 w-full items-center justify-center gap-1 rounded-lg border border-cyan-200 text-xs font-bold text-cyan-700 hover:bg-cyan-50 dark:border-cyan-900 dark:text-cyan-300"><flux:icon name="plus" class="size-3.5" />{{ __('Add New Customer') }}</button>@endif@endcan
                    @if($customerSearchResults->isNotEmpty())<div class="mt-2 max-h-44 divide-y divide-zinc-100 overflow-y-auto rounded-lg border border-zinc-200 dark:divide-zinc-800 dark:border-zinc-800" data-customer-search-results>@foreach($customerSearchResults as $candidate)<form method="POST" action="{{ route('pos.customer.select') }}" class="flex items-center justify-between gap-2 p-2">@csrf<input type="hidden" name="customer_id" value="{{ $candidate->id }}"><div class="min-w-0"><strong class="block truncate text-xs">{{ str_starts_with(app()->getLocale(), 'ar')?$candidate->name_ar:$candidate->name_en }}</strong><span class="block truncate text-[10px] text-zinc-500"><span dir="ltr">{{ $candidate->phone_display }}</span> · <span dir="ltr">{{ $candidate->public_id }}</span> · {{ $candidate->email }}</span></div><button type="submit" class="shrink-0 rounded-md bg-cyan-50 px-2 py-1 text-[11px] font-bold text-cyan-700">{{ __('Select') }}</button></form>@endforeach</div>@elseif($customerQuery!=='')<p class="mt-2 text-[11px] text-zinc-500">{{ __('No customer matched this search.') }}</p>@elseif(!$selectedCustomer)<p class="mt-2 text-[11px] text-zinc-500">{{ __('Walk-in customer') }}</p>@endif
                </section>@endcan
                <livewire:pos.checkout-panel :key="'checkout-'.($activeOrder?->uuid ?? 'disabled')" />
            </aside>
        </main>
    </div>

    @can('customers.create')@if($customerPurposes!==[])<dialog id="pos-new-customer" @if($errors->hasAny(['phone','name_ar','name_en','consent_purpose','customer'])) x-data x-init="$nextTick(()=>$el.showModal())" @endif class="m-auto w-[min(94vw,35rem)] rounded-xl bg-white p-0 text-start shadow-2xl backdrop:bg-zinc-950/70 dark:bg-zinc-900 dark:text-zinc-100"><form method="POST" action="{{ route('pos.customer.create') }}" class="p-4">@csrf<input type="hidden" name="idempotency_key" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><div class="flex items-center justify-between border-b border-zinc-200 pb-3 dark:border-zinc-800"><h2 class="font-extrabold">{{ __('Add New Customer') }}</h2><button type="button" onclick="this.closest('dialog').close()" class="flex size-8 items-center justify-center rounded-lg hover:bg-zinc-100" aria-label="{{ __('Close') }}"><flux:icon name="x-mark" class="size-4" /></button></div><div class="mt-3 grid gap-2 sm:grid-cols-2"><flux:input name="phone" :label="__('Phone')" :value="old('phone')" required autofocus autocomplete="tel" dir="ltr" /><flux:select name="consent_purpose" :label="__('Consent purpose')" required>@foreach($customerPurposes as $purpose)<flux:select.option value="{{ $purpose }}">{{ __($purpose) }}</flux:select.option>@endforeach</flux:select><flux:input name="name_ar" :label="__('Arabic name')" :value="old('name_ar')" required dir="rtl" /><flux:input name="name_en" :label="__('English name')" :value="old('name_en')" required dir="ltr" /></div><div class="mt-4 flex justify-end gap-2"><button type="button" onclick="this.closest('dialog').close()" class="h-10 rounded-lg px-4 text-sm font-bold">{{ __('Cancel') }}</button><button class="h-10 rounded-lg bg-cyan-700 px-4 text-sm font-bold text-white">{{ __('Create and select') }}</button></div></form></dialog>@endif@endcan

    @can('returns.create')
        @can('returns.submit')
            <livewire:pos.refund-wizard />
        @endcan
    @endcan
    @if($completedSale)<dialog open id="pos-sale-success" class="m-auto w-[min(94vw,31rem)] rounded-xl bg-white p-0 text-start shadow-2xl backdrop:bg-zinc-950/75 dark:bg-zinc-900 dark:text-zinc-100" aria-labelledby="pos-success-heading"><div class="p-4 text-center"><div class="mx-auto flex size-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300"><flux:icon name="check-circle" class="size-7" /></div><h2 id="pos-success-heading" class="mt-2 font-black">{{ __('Sale completed successfully') }}</h2><span class="sr-only">{{ __('Invoice / order number') }}</span><p class="mt-1 font-mono text-base font-black" dir="ltr">{{ $completedSale->document_number }}</p><div class="mt-4 grid gap-2 sm:grid-cols-3">@can('pos_sales.print')<a href="{{ route('pos.receipt.preview',$completedSale) }}" target="_blank" class="inline-flex h-10 items-center justify-center gap-1 rounded-lg bg-cyan-700 px-3 text-xs font-extrabold text-white"><flux:icon name="printer" class="size-4" />{{ __('Print receipt') }}</a>@endcan<form method="POST" action="{{ route('pos.orders.store') }}">@csrf<input type="hidden" name="creation_token" value="{{ (string)\Illuminate\Support\Str::uuid() }}"><button class="h-10 w-full rounded-lg border border-zinc-300 px-3 text-xs font-bold dark:border-zinc-700">{{ __('New order') }}</button></form><a href="{{ route('sales.show',$completedSale) }}" class="inline-flex h-10 items-center justify-center rounded-lg border border-zinc-300 px-3 text-xs font-bold dark:border-zinc-700">{{ __('View current order') }}</a></div></div></dialog>@endif
</x-layouts::pos>
