<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ str_starts_with(app()->getLocale(), 'ar') ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ __('Refund receipt') }} {{ $return->return_number }}</title>
    @php($thermal = ($receiptProfile['format'] ?? 'thermal') === 'thermal')
    <style>
        *{box-sizing:border-box}body{margin:0;background:#eef2f4;color:#111827;font-family:Arial,"Noto Sans Arabic",sans-serif}.toolbar{position:sticky;top:0;display:flex;flex-wrap:wrap;align-items:center;justify-content:center;gap:.5rem;padding:.75rem;background:#111827;color:#fff}.toolbar button,.toolbar a{border:1px solid #475569;border-radius:.5rem;background:#fff;color:#111827;padding:.55rem .8rem;text-decoration:none;font-weight:700;cursor:pointer}.toolbar .primary{background:#0e7490;color:#fff;border-color:#0e7490}.notice{max-width:60rem;margin:.75rem auto;padding:.65rem .8rem;border-radius:.5rem;background:#fff7ed;color:#9a3412;font-size:.82rem}.sheet{width:{{ $thermal ? ($receiptProfile['paper_size'] === '58mm' ? '58mm' : '80mm') : '210mm' }};min-height:{{ $thermal ? 'auto' : '297mm' }};margin:1rem auto;background:#fff;padding:{{ $thermal ? '4mm' : '14mm' }};box-shadow:0 8px 24px #0002}.center{text-align:center}.muted{color:#64748b;font-size:.78rem}.row{display:flex;justify-content:space-between;gap:1rem;border-bottom:1px dashed #cbd5e1;padding:.38rem 0}.total{font-size:1.12rem;font-weight:900;border-top:2px solid #111827;margin-top:.5rem;padding-top:.55rem}table{width:100%;border-collapse:collapse;margin-top:.7rem;font-size:{{ $thermal ? '.72rem' : '.88rem' }}}th,td{border-bottom:1px solid #e2e8f0;padding:.38rem .2rem;text-align:start;vertical-align:top}.footer{margin-top:1rem;text-align:center;white-space:pre-line}.actions-form{display:inline}@media print{body{background:#fff}.toolbar,.notice{display:none}.sheet{box-shadow:none;margin:0;width:100%;min-height:auto;padding:{{ $thermal ? '2mm' : '8mm' }}}@page{size:{{ $thermal ? ($receiptProfile['paper_size'] ?? '80mm').' auto' : ($receiptProfile['paper_size'] ?? 'A4') }};margin:0}}
    </style>
</head>
<body>
    <nav class="toolbar" aria-label="{{ __('Refund receipt actions') }}">
        <button type="button" class="primary" onclick="window.print()">{{ __('Print') }}</button>
        @if($returnToPos ?? false)<form class="actions-form" method="POST" action="{{ route('pos.orders.store') }}">@csrf<input type="hidden" name="creation_token" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><button type="submit">{{ __('New order') }}</button></form><a href="{{ route('returns.show', $return) }}">{{ __('View current refund') }}</a><a href="{{ route('pos') }}">{{ __('Return to POS') }}</a>@else<a href="{{ route('returns.show', $return) }}">{{ __('View current refund') }}</a>@endif
    </nav>
    @if($receiptProfile['browser_fallback'] ?? true)<p class="notice" role="status">{{ $receiptProfile['fallback_message'] ?? __('Use the secure browser print dialog.') }}</p>@endif
    <main class="sheet">
        @php($template = $receiptProfile['printer']?->printTemplate)
        <header class="center"><h1 style="margin:.2rem 0;font-size:{{ $thermal ? '1rem' : '1.5rem' }}">{{ str_starts_with(app()->getLocale(), 'ar') ? $return->store?->company?->name_ar : $return->store?->company?->name_en }}</h1>@if($template?->header_text)<div class="muted" style="white-space:pre-line">{{ $template->header_text }}</div>@endif<h2 style="margin:.6rem 0 .2rem">{{ __('Refund / return receipt') }}</h2><strong dir="ltr">{{ $return->return_number }}</strong></header>
        <section style="margin-top:.7rem"><div class="row"><span>{{ __('Original invoice') }}</span><strong dir="ltr">{{ $return->sourceSale?->document_number ?: $return->sourceGiftReceipt?->reference }}</strong></div><div class="row"><span>{{ __('Branch / outlet') }}</span><strong>{{ str_starts_with(app()->getLocale(), 'ar') ? $return->branch?->name_ar : $return->branch?->name_en }} · {{ str_starts_with(app()->getLocale(), 'ar') ? $return->store?->name_ar : $return->store?->name_en }}</strong></div><div class="row"><span>{{ __('Customer') }}</span><strong>{{ $return->customer ? (str_starts_with(app()->getLocale(), 'ar') ? $return->customer->name_ar : $return->customer->name_en) : __('Walk-in customer') }}</strong></div><div class="row"><span>{{ __('Completed at') }}</span><strong>{{ $return->completed_at?->format('Y-m-d H:i') }}</strong></div></section>
        <table><thead><tr><th>{{ __('Item') }}</th><th>{{ __('Quantity') }}</th><th>{{ __('Condition') }}</th><th>{{ __('Value') }}</th></tr></thead><tbody>@foreach($return->lines as $line)<tr><td>{{ str_starts_with(app()->getLocale(), 'ar') ? $line->product?->name_ar : $line->product?->name_en }}<div class="muted" dir="ltr">{{ $line->saleLine?->item_code }}</div></td><td><x-product-quantity :value="$line->quantity" /></td><td>{{ match($line->condition) { 'sellable' => __('Sellable'), 'non_sellable' => __('Non-saleable'), 'damaged' => __('Damaged'), default => __('Manager review') } }}<div class="muted">{{ str_starts_with(app()->getLocale(), 'ar') ? $line->returnStore?->name_ar : $line->returnStore?->name_en }}</div></td><td>{{ number_format((float)bcadd((string)$line->eligible_value, (string)$line->tax_value, 2), 2) }}</td></tr>@endforeach</tbody></table>
        <section style="margin-top:.6rem"><div class="row"><span>{{ __('Subtotal') }}</span><strong>{{ number_format((float)$return->subtotal_refund, 2) }}</strong></div><div class="row"><span>{{ __('Discounts') }}</span><strong>− {{ number_format((float)$return->discount_refund, 2) }}</strong></div><div class="row"><span>{{ __('Tax') }}</span><strong>{{ number_format((float)$return->tax_refund, 2) }}</strong></div><div class="row"><span>{{ __('Cash rounding') }}</span><strong>{{ number_format((float)$return->rounding_refund, 2) }}</strong></div><div class="row total"><span>{{ __('Final refund') }}</span><strong>{{ number_format((float)$return->settlement_value, 2) }} {{ $return->currency_code }}</strong></div></section>
        <section style="margin-top:.7rem">@foreach($return->settlements as $settlement)<div class="row"><span>{{ str_starts_with(app()->getLocale(), 'ar') ? $settlement->paymentMethod?->name_ar : $settlement->paymentMethod?->name_en }}{{ $settlement->giftCard ? ' · '.$settlement->giftCard->identifier : '' }}</span><strong>{{ number_format((float)$settlement->amount, 2) }}</strong></div>@endforeach</section>
        <p class="muted">{{ __('Reason') }}: {{ $return->reason }}</p>@if($template?->footer_text)<footer class="footer muted">{{ $template->footer_text }}</footer>@endif
    </main>
</body>
</html>
