@props(['dashboard'])

@php($ar = str_starts_with(app()->getLocale(), 'ar'))

<section class="dashboard-kpi-grid" aria-label="{{ $ar ? 'مؤشرات الأصول والتأجير' : 'Assets and rental indicators' }}">
    <a href="{{ route('party.assets.index', ['mode' => 'catalog']) }}" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $ar ? 'الأصول النشطة' : 'Active assets' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['active_assets']) }}</p><p class="dashboard-kpi__state">{{ $dashboard['available_assets'] }} {{ $ar ? 'متاح للحجز' : 'available to reserve' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.archive-box class="size-5" /></span></a>
    <a href="{{ route('party.assets.index', ['mode' => 'reservations']) }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $ar ? 'الحجوزات القادمة' : 'Upcoming reservations' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['upcoming_reservations']) }}</p><p class="dashboard-kpi__state">{{ $dashboard['upcoming_checkouts'] }} {{ $ar ? 'تسليم خلال 7 أيام' : 'checkouts within 7 days' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.calendar-days class="size-5" /></span></a>
    <a href="{{ route('party.assets.index', ['mode' => 'returns']) }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $ar ? 'أصول خارج العهدة' : 'Assets in custody' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['outstanding_returns']) }}</p><p class="dashboard-kpi__state">{{ $dashboard['overdue_returns'] }} {{ $ar ? 'متأخر عن موعد الإرجاع' : 'overdue for return' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.arrow-uturn-left class="size-5" /></span></a>
    <a href="{{ route('party.assets.index', ['mode' => 'history']) }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $ar ? 'استثناءات الحالة' : 'Condition exceptions' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['unavailable_assets']) }}</p><p class="dashboard-kpi__state">{{ $dashboard['pending_events'] }} {{ $ar ? 'حدث بانتظار الاعتماد' : 'events awaiting approval' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.exclamation-triangle class="size-5" /></span></a>
</section>

<div class="grid gap-4 xl:grid-cols-12">
    <section class="dashboard-panel xl:col-span-7"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'الحجوزات والتسليمات القادمة' : 'Upcoming reservations and checkouts' }}</flux:heading><flux:text size="sm">{{ $ar ? 'أقرب العمليات ضمن نطاق الموقع المصرح به' : 'Nearest operations in the authorized location scope' }}</flux:text></div><a href="{{ route('party.assets.index', ['mode' => 'calendar']) }}" class="text-sm font-semibold text-primary">{{ $ar ? 'فتح التقويم' : 'Open calendar' }}</a></header><div class="dashboard-list">@forelse($dashboard['upcoming_rows'] as $reservation)<a href="{{ route('party.assets.index', ['mode' => 'reservations', 'q' => $reservation->asset?->code]) }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate" dir="ltr">{{ $reservation->asset?->code }}</strong><small class="block truncate text-text-muted">{{ $ar ? $reservation->asset?->name_ar : $reservation->asset?->name_en }} · {{ $reservation->store?->code }}</small></span><span class="text-end"><strong class="block text-sm tabular-nums" dir="ltr">{{ $reservation->starts_at?->format('Y-m-d H:i') }}</strong><small class="text-text-muted">{{ $reservation->source_reference ?: ($ar ? 'دون مرجع' : 'No reference') }}</small></span></a>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش حجوزات قادمة' : ($ar ? 'لا توجد حجوزات قادمة' : 'No upcoming reservations')" icon="calendar-days" />@endforelse</div></section>
    <section class="dashboard-panel xl:col-span-5"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'توزيع الحالة' : 'Lifecycle distribution' }}</flux:heading><flux:text size="sm">{{ $ar ? 'الحالة التشغيلية الحالية لكل أصل' : 'Current operational state of every asset' }}</flux:text></div><flux:badge color="teal">{{ number_format($dashboard['utilization_percent'], 1) }}% {{ $ar ? 'قيد الاستخدام' : 'in use' }}</flux:badge></header><div class="grid grid-cols-2 gap-3">@foreach(['available' => [$ar ? 'متاح' : 'Available', 'emerald'], 'reserved' => [$ar ? 'محجوز' : 'Reserved', 'sky'], 'checked_out' => [$ar ? 'مسلم' : 'Checked out', 'amber'], 'under_inspection' => [$ar ? 'تحت الفحص' : 'Inspection', 'violet'], 'under_maintenance' => [$ar ? 'صيانة' : 'Maintenance', 'orange'], 'lost' => [$ar ? 'مفقود' : 'Lost', 'red']] as $status => [$label, $tone])<a href="{{ route('party.assets.index', ['mode' => 'catalog', 'status' => $status]) }}" class="rounded-xl border border-border bg-surface-muted/30 p-3"><span class="text-sm text-text-muted">{{ $label }}</span><strong class="mt-1 block text-xl tabular-nums">{{ number_format($dashboard['status_counts'][$status] ?? 0) }}</strong></a>@endforeach</div></section>
</div>

<div class="grid gap-4 xl:grid-cols-2">
    <section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'الإرجاعات المتأخرة' : 'Overdue returns' }}</flux:heading><flux:text size="sm">{{ $ar ? 'أصول لم يسجل لها إرجاع بعد انتهاء الحجز' : 'Assets without a return after the reservation ended' }}</flux:text></div><flux:icon.clock class="size-5 text-danger" /></header><div class="dashboard-list">@forelse($dashboard['overdue_rows'] as $checkout)<a href="{{ route('party.assets.index', ['mode' => 'returns', 'q' => $checkout->asset?->code]) }}" class="dashboard-list__row"><span><strong class="block" dir="ltr">{{ $checkout->asset?->code }}</strong><small class="text-text-muted">{{ $checkout->reservation?->source_reference ?: ($ar ? 'دون مرجع' : 'No reference') }}</small></span><span class="text-sm tabular-nums" dir="ltr">{{ $checkout->reservation?->ends_at?->format('Y-m-d H:i') }}</span></a>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش إرجاعات متأخرة' : ($ar ? 'لا توجد إرجاعات متأخرة' : 'No overdue returns')" icon="check-circle" />@endforelse</div></section>
    <section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'آخر نشاط للحالة' : 'Recent condition activity' }}</flux:heading><flux:text size="sm">{{ $ar ? 'فحص وصيانة وضرر واستهلاك تشغيلي' : 'Inspection, maintenance, damage, and operational depreciation' }}</flux:text></div><a href="{{ route('party.assets.index', ['mode' => 'history']) }}" class="text-sm font-semibold text-primary">{{ $ar ? 'السجل الكامل' : 'Full history' }}</a></header><div class="dashboard-list">@forelse($dashboard['recent_events'] as $event)<a href="{{ route('party.assets.index', ['mode' => 'history', 'q' => $event->asset?->code]) }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate"><span dir="ltr">{{ $event->asset?->code }}</span> · {{ $ar ? $event->asset?->name_ar : $event->asset?->name_en }}</strong><small class="block truncate text-text-muted">{{ $event->assessment }}</small></span><x-status.badge :status="$event->status" /></a>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش نشاط حالة بعد' : ($ar ? 'لا يوجد نشاط حالة بعد' : 'No condition activity yet')" icon="wrench-screwdriver" />@endforelse</div></section>
</div>

<section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'حدود النقل والعائد' : 'Transfer and revenue boundary' }}</flux:heading><flux:text size="sm">{{ app()->isLocale('ar-EG') ? 'يعرض النظام بس ما تدعمه سجلات الأصول الحالية' : ($ar ? 'يعرض النظام فقط ما تدعمه سجلات الأصول الحالية' : 'The workspace only presents capabilities backed by current asset records') }}</flux:text></div><flux:icon.information-circle class="size-5 text-info" /></header><p class="text-sm leading-7 text-text-muted">{{ app()->isLocale('ar-EG') ? 'مفيش حالياً سجل مستقل لطلبات نقل الأصول أو دفتر عائد إيجار مباشر. تتغير العهدة والموقع بس عبر عمليات التسليم والإرجاع المعتمدة، وتظل مراجع أصول الحفلات مرتبطة بأوامر التشغيل.' : ($ar ? 'لا يوجد حالياً سجل مستقل لطلبات نقل الأصول أو دفتر عائد إيجار مباشر. تتغير العهدة والموقع فقط عبر عمليات التسليم والإرجاع المعتمدة، وتظل مراجع أصول الحفلات مرتبطة بأوامر التشغيل.' : 'There is currently no standalone asset-transfer request record or direct rental-revenue ledger. Custody and location change only through authorized checkout and return actions, while Party asset references remain linked to operating orders.') }}</p></section>
