@php($ar=str_starts_with(app()->getLocale(), 'ar'))
<x-layouts::app :title="$ar ? 'الحفلات والحجوزات' : 'Parties & bookings'">
    <x-app.page :title="$ar ? 'الحفلات والحجوزات' : 'Parties & bookings'" :description="app()->isLocale('ar-EG') ? 'كمّل الحجوزات والمواعيد والتحصيل والتشغيل ضمن الفروع والمتاجر المصرح بها.' : ($ar ? 'متابعة الحجوزات والمواعيد والتحصيل والتشغيل ضمن الفروع والمتاجر المصرح بها.' : 'Monitor bookings, schedules, collections, and operations within your authorized scope.')" max-width="7xl">
        <x-slot:actions>
            @can('party_bookings_invoices.create')<flux:button href="{{ route('parties.bookings.create') }}" variant="primary" icon="plus">{{ $ar ? 'حجز جديد' : 'New booking' }}</flux:button>@endcan
            @can('rental_assets.view')<flux:button href="{{ route('parties.calendar') }}" variant="subtle" icon="calendar-days">{{ $ar ? 'التقويم' : 'Calendar' }}</flux:button>@endcan
            @can('party_bookings_invoices.view')<flux:button href="{{ route('parties.invoices.index') }}" variant="subtle" icon="document-text">{{ $ar ? 'الفواتير' : 'Invoices' }}</flux:button>@endcan
            @can('customers.view')<flux:button href="{{ route('customers.index') }}" variant="subtle" icon="users">{{ $ar ? 'العملاء' : 'Customers' }}</flux:button>@endcan
        </x-slot:actions>
        @if(session('success'))<flux:callout variant="success" icon="check-circle">{{ session('success') }}</flux:callout>@endif
        @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle">{{ $errors->first() }}</flux:callout>@endif
        <x-party.dashboard :dashboard="$dashboard" />
        <section id="booking-list" class="space-y-4">
            <section class="internal-toolbar" aria-labelledby="booking-filter-heading"><div class="mb-3"><h2 id="booking-filter-heading" class="font-semibold">{{ $ar ? 'قائمة الحجوزات' : 'Booking list' }}</h2><p class="text-sm text-text-muted">{{ app()->isLocale('ar-EG') ? 'دوّر وتصفية الحجوزات دون تغيير نطاق الصلاحيات.' : ($ar ? 'بحث وتصفية الحجوزات دون تغيير نطاق الصلاحيات.' : 'Search and filter bookings without changing authorization scope.') }}</p></div>
                <form method="GET" class="grid w-full gap-3 md:grid-cols-2 xl:grid-cols-6 xl:items-end">
                    <flux:input name="q" :label="app()->isLocale('ar-EG') ? 'دوّر' : ($ar ? 'بحث' : 'Search')" :value="$term" :placeholder="$ar ? 'رقم الحجز أو العميل أو الموقع' : 'Booking, customer, or location'" />
                    <flux:select name="store_id" :label="$ar ? 'موقع الحفل' : 'Party location'"><option value="">{{ $ar ? 'كل المواقع المصرح بها' : 'All authorized locations' }}</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected($storeId===$store->id)>{{ $ar ? $store->name_ar : $store->name_en }}</option>@endforeach</flux:select>
                    <flux:select name="status" :label="$ar ? 'الحالة' : 'Status'"><option value="">{{ $ar ? 'كل الحالات' : 'All statuses' }}</option>@foreach(\App\Modules\Party\Enums\PartyBookingStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ \App\Modules\Platform\Support\UiLabel::status($status->value) }}</option>@endforeach</flux:select>
                    <flux:input name="from" type="date" :label="$ar ? 'من تاريخ' : 'From'" :value="request('from')" />
                    <flux:input name="to" type="date" :label="$ar ? 'إلى تاريخ' : 'To'" :value="request('to')" />
                    <div class="flex gap-2"><flux:button type="submit" variant="primary" icon="magnifying-glass">{{ $ar ? 'تطبيق' : 'Apply' }}</flux:button><flux:button href="{{ route('parties.bookings.index') }}" variant="subtle">{{ $ar ? 'إعادة ضبط' : 'Reset' }}</flux:button></div>
                </form>
            </section>
            <x-tables.data-panel :title="$ar ? 'الحجوزات المجدولة' : 'Scheduled bookings'" :description="$ar ? $bookings->total().' سجلاً ضمن النطاق الحالي' : $bookings->total().' records in current scope'">
                <div class="responsive-resource-table"><table class="data-table data-table--mobile-summary w-full text-sm"><thead><tr><th>{{ $ar ? 'الحجز والعميل' : 'Booking & customer' }}</th><th>{{ $ar ? 'الموعد والمكان' : 'Schedule & venue' }}</th><th>{{ $ar ? 'موقع العمل' : 'Work location' }}</th><th>{{ $ar ? 'الفاتورة' : 'Invoice' }}</th><th>{{ $ar ? 'الحالة' : 'Status' }}</th><th class="text-end">{{ $ar ? 'الإجراء' : 'Action' }}</th></tr></thead><tbody>
                    @forelse($bookings as $booking)<tr><td data-label="{{ $ar ? 'الحجز والعميل' : 'Booking & customer' }}"><div class="font-mono font-semibold" dir="ltr">{{ $booking->booking_number }}</div><div class="font-semibold">{{ $ar ? $booking->customer->name_ar : $booking->customer->name_en }}</div></td><td data-label="{{ $ar ? 'الموعد والمكان' : 'Schedule & venue' }}"><div class="font-semibold">{{ $booking->party_date?->format('Y-m-d') }} · <span dir="ltr">{{ $booking->starts_at?->format('H:i') }}–{{ $booking->ends_at?->format('H:i') }}</span></div><div class="text-xs text-text-muted">{{ $booking->location }}</div></td><td data-label="{{ $ar ? 'موقع العمل' : 'Work location' }}">{{ $ar ? $booking->store->name_ar : $booking->store->name_en }}</td><td data-label="{{ $ar ? 'الفاتورة' : 'Invoice' }}" class="font-mono" dir="ltr">{{ $booking->invoice?->invoice_number ?? '—' }}</td><td data-label="{{ $ar ? 'الحالة' : 'Status' }}"><x-status.badge :status="$booking->status" /></td><td data-label="{{ $ar ? 'الإجراء' : 'Action' }}" class="text-end"><x-actions.button semantic="view" :label="$ar ? 'فتح' : 'Open'" :href="route('parties.bookings.show', $booking->id)">{{ $ar ? 'فتح' : 'Open' }}</x-actions.button></td></tr>
                    @empty<tr><td colspan="6"><x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش حجوزات مطابقة' : ($ar ? 'لا توجد حجوزات مطابقة' : 'No matching bookings')" :description="$ar ? 'غيّر عوامل التصفية أو أنشئ حجزاً جديداً.' : 'Adjust filters or create a new booking.'" /></td></tr>@endforelse
                </tbody></table></div>
                <x-slot:footer><div class="flex flex-wrap items-center justify-between gap-3"><form method="GET" class="flex items-center gap-2">@foreach(request()->except('per_page','page') as $key=>$value)<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endforeach<label for="party-bookings-page-size" class="text-sm text-text-muted">{{ $ar ? 'حجم الصفحة' : 'Page size' }}</label><select id="party-bookings-page-size" name="per_page" class="min-h-11 rounded-lg border border-border bg-surface px-3" onchange="this.form.submit()">@foreach([20,50,100] as $size)<option value="{{ $size }}" @selected($bookings->perPage()===$size)>{{ $size }}</option>@endforeach</select></form>@if($bookings->hasPages()){{ $bookings->links() }}@endif</div></x-slot:footer>
            </x-tables.data-panel>
        </section>
    </x-app.page>
</x-layouts::app>
