@props(['dashboard'])
@php
    $ar = str_starts_with(app()->getLocale(), 'ar');
    $days = collect(range(6, 0))->map(fn ($offset) => now()->subDays($offset));
    $maxTrend = max(1, (int) $days->map(fn ($day) => (int) ($dashboard['trend'][$day->format('Y-m-d')]->booking_count ?? 0))->max());
@endphp

<section class="dashboard-kpi-grid" aria-label="{{ $ar ? 'مؤشرات تشغيل الحفلات' : 'Party operations indicators' }}">
    <a href="#booking-list" class="dashboard-kpi dashboard-kpi--priority"><div><p class="dashboard-kpi__label">{{ $ar ? 'حفلات اليوم' : "Today's parties" }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['today']) }}</p><p class="dashboard-kpi__state">{{ $dashboard['upcoming'] }} {{ $ar ? 'خلال 7 أيام' : 'in the next 7 days' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.calendar-days class="size-5" /></span></a>
    <a href="{{ route('parties.bookings.index', ['status' => 'confirmed']) }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $ar ? 'حجوزات مؤكدة' : 'Confirmed bookings' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['confirmed']) }}</p><p class="dashboard-kpi__state">{{ $ar ? 'جاهزة للتشغيل' : 'Ready for operation' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.check-badge class="size-5" /></span></a>
    <a href="{{ route('parties.bookings.index', ['status' => 'rescheduled']) }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ app()->isLocale('ar-EG') ? 'تحتاج استكمال' : ($ar ? 'تحتاج متابعة' : 'Needs follow-up') }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['follow_up']) }}</p><p class="dashboard-kpi__state">{{ $ar ? 'مسودة أو مبدئية أو مؤجلة للتسوية' : 'Draft, tentative, rescheduled, or unsettled' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.exclamation-triangle class="size-5" /></span></a>
    @can('party_operating_orders_consumables.view')<a href="{{ route('parties.orders.index') }}" class="dashboard-kpi"><div><p class="dashboard-kpi__label">{{ $ar ? 'أوامر تشغيل مفتوحة' : 'Open operating orders' }}</p><p class="dashboard-kpi__value">{{ number_format($dashboard['open_orders']) }}</p><p class="dashboard-kpi__state">{{ $ar ? 'ضمن نطاق العمل المصرح' : 'Within authorized work scope' }}</p></div><span class="dashboard-kpi__icon"><flux:icon.clipboard-document-list class="size-5" /></span></a>@endcan
</section>

<div class="grid gap-4 lg:grid-cols-12">
    <section class="dashboard-panel lg:col-span-7"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'اتجاه الحجوزات خلال 7 أيام' : 'Seven-day booking trend' }}</flux:heading><flux:text size="sm">{{ $dashboard['period_bookings'] }} {{ $ar ? 'حجزاً غير ملغي' : 'non-cancelled bookings' }}</flux:text></div><flux:icon.chart-bar class="size-5 text-primary" /></header><div class="flex h-36 items-end gap-2" aria-label="{{ $ar ? 'عدد الحجوزات لكل يوم' : 'Bookings per day' }}">@foreach($days as $day)@php($count=(int)($dashboard['trend'][$day->format('Y-m-d')]->booking_count ?? 0))<div class="flex min-w-0 flex-1 flex-col items-center gap-2"><span class="text-xs font-semibold tabular-nums">{{ $count }}</span><div class="w-full rounded-t-lg bg-primary/75" style="height: {{ max(6, (int) round(($count / $maxTrend) * 88)) }}px"></div><span class="text-[11px] text-text-muted">{{ $day->format('d/m') }}</span></div>@endforeach</div></section>
    <section class="dashboard-panel lg:col-span-5"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'التحصيل والرصيد' : 'Collections & balance' }}</flux:heading><flux:text size="sm">{{ $ar ? 'قيم فعلية من فواتير ومدفوعات الحفلات' : 'Authoritative Party invoices and payments' }}</flux:text></div><flux:icon.banknotes class="size-5 text-primary" /></header><dl class="grid gap-3 sm:grid-cols-3 lg:grid-cols-1"><div class="rounded-xl bg-primary-soft p-3"><dt class="text-xs text-text-muted">{{ $ar ? 'إجمالي الفترة' : 'Period total' }}</dt><dd class="mt-1 text-xl font-bold tabular-nums" dir="ltr">{{ number_format((float)$dashboard['period_total'], 2) }} EGP</dd></div><div class="rounded-xl bg-surface-muted p-3"><dt class="text-xs text-text-muted">{{ $ar ? 'المحصّل' : 'Collected' }}</dt><dd class="mt-1 text-xl font-bold tabular-nums" dir="ltr">{{ number_format((float)$dashboard['period_paid'], 2) }} EGP</dd></div><div class="rounded-xl bg-surface-muted p-3"><dt class="text-xs text-text-muted">{{ $ar ? 'الرصيد المستحق' : 'Outstanding' }}</dt><dd class="mt-1 text-xl font-bold tabular-nums" dir="ltr">{{ number_format((float)$dashboard['outstanding'], 2) }} EGP</dd></div></dl></section>
</div>

<div class="grid gap-4 xl:grid-cols-2">
    <section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'الحفلات القادمة' : 'Upcoming parties' }}</flux:heading><flux:text size="sm">{{ $ar ? 'أقرب 14 يوماً مرتبة حسب وقت البداية' : 'Next 14 days ordered by start time' }}</flux:text></div>@can('rental_assets.view')<a href="{{ route('parties.calendar') }}" class="text-sm font-semibold text-primary">{{ $ar ? 'فتح الأجندة' : 'Open agenda' }}</a>@endcan</header><div class="dashboard-list">@forelse($dashboard['upcoming_rows'] as $booking)<a href="{{ route('parties.bookings.show', $booking) }}" class="dashboard-list__row"><span class="min-w-0"><strong class="block truncate">{{ $booking->booking_number }} · {{ $ar ? $booking->customer?->name_ar : $booking->customer?->name_en }}</strong><small class="block truncate text-text-muted">{{ $booking->party_date?->format('Y-m-d') }} · {{ $booking->starts_at?->format('H:i') }} · {{ $booking->location }}</small></span><x-status.badge :status="$booking->status" /></a>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش حفلات قادمة' : ($ar ? 'لا توجد حفلات قادمة' : 'No upcoming parties')" icon="calendar-days" />@endforelse</div></section>
    <section class="dashboard-panel"><header class="dashboard-panel__header"><div><flux:heading size="lg">{{ $ar ? 'الخدمات والتحصيل' : 'Services & payment mix' }}</flux:heading><flux:text size="sm">{{ $ar ? 'أكثر خدمات الفواتير استخداماً خلال 7 أيام' : 'Most-used invoice services during 7 days' }}</flux:text></div><flux:icon.sparkles class="size-5 text-primary" /></header><div class="grid gap-4 sm:grid-cols-2"><div class="dashboard-list">@forelse($dashboard['top_services'] as $service)<div class="dashboard-list__row"><span class="truncate">{{ $ar ? $service->description_ar : $service->description_en }}</span><strong class="tabular-nums">{{ number_format((float)$service->service_quantity, 2) }}</strong></div>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش خدمات مسجلة' : ($ar ? 'لا توجد خدمات مسجلة' : 'No service activity')" />@endforelse</div><div class="dashboard-list">@forelse($dashboard['payment_mix'] as $method)<div class="dashboard-list__row"><span>{{ $method->method_type === 'cash' ? ($ar ? 'نقدي' : 'Cash') : ($method->method_type === 'card' ? ($ar ? 'بطاقة' : 'Card') : str($method->method_type)->headline()) }}</span><strong class="tabular-nums" dir="ltr">{{ number_format((float)$method->total_amount, 2) }}</strong></div>@empty<x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش مدفوعات في الفترة' : ($ar ? 'لا توجد مدفوعات في الفترة' : 'No payments in period')" />@endforelse</div></div></section>
</div>
