@php($ar=str_starts_with(app()->getLocale(), 'ar'))
<x-layouts::app :title="$ar ? 'أوامر تشغيل الحفلات' : 'Party operating orders'">
    <x-app.page :title="$ar ? 'أوامر تشغيل الحفلات' : 'Party operating orders'" :description="$ar ? 'تنفيذ الخدمات والأصول والمستهلكات من الحجز المؤكد مع الحفاظ على أثر المصدر.' : 'Execute services, assets, and consumables from confirmed bookings with source traceability.'" max-width="7xl">
        <x-slot:actions><flux:button href="{{ route('parties.bookings.index') }}" variant="subtle" icon="calendar-days">{{ $ar ? 'الحجوزات' : 'Bookings' }}</flux:button></x-slot:actions>
        @if(session('success'))<flux:callout variant="success" icon="check-circle">{{ session('success') }}</flux:callout>@endif
        @if($errors->any())<flux:callout variant="danger" icon="exclamation-triangle">{{ $errors->first() }}</flux:callout>@endif
        <form method="GET" class="internal-toolbar" aria-label="{{ $ar ? 'مرشحات أوامر التشغيل' : 'Operating order filters' }}"><div class="internal-toolbar__grid"><flux:input name="q" :value="$term" :label="app()->isLocale('ar-EG') ? 'دوّر' : ($ar ? 'بحث' : 'Search')" :placeholder="$ar ? 'رقم الأمر أو الحجز أو العميل' : 'Order, booking, or customer'" /><flux:select name="status" :label="$ar ? 'الحالة' : 'Status'"><option value="">{{ $ar ? 'كل الحالات' : 'All statuses' }}</option>@foreach(\App\Modules\Party\Enums\PartyOperatingOrderState::cases() as $state)<option value="{{ $state->value }}" @selected(request('status')===$state->value)>{{ \App\Modules\Platform\Support\UiLabel::status($state->value) }}</option>@endforeach</flux:select><div class="flex items-end gap-2"><flux:button type="submit" variant="primary" icon="magnifying-glass">{{ $ar ? 'تطبيق' : 'Apply' }}</flux:button><flux:button href="{{ route('parties.orders.index') }}" variant="subtle">{{ $ar ? 'إعادة ضبط' : 'Reset' }}</flux:button></div></div></form>
        <x-tables.data-panel :title="$ar ? 'قائمة التشغيل' : 'Operational queue'" :description="$ar ? $orders->total().' أمراً ضمن نطاق مواقع الحفلات المصرح بها' : $orders->total().' orders in authorized Party locations'">
            <div class="responsive-resource-table"><table class="data-table data-table--mobile-summary w-full text-sm"><thead><tr><th>{{ $ar ? 'الأمر والحجز' : 'Order & booking' }}</th><th>{{ $ar ? 'العميل' : 'Customer' }}</th><th>{{ $ar ? 'موقع العمل' : 'Work location' }}</th><th>{{ $ar ? 'الحالة' : 'Status' }}</th><th class="text-end">{{ $ar ? 'الإجراء' : 'Action' }}</th></tr></thead><tbody>@forelse($orders as $order)<tr><td data-label="{{ $ar ? 'الأمر والحجز' : 'Order & booking' }}"><div class="font-mono font-semibold" dir="ltr">{{ $order->order_number }}</div><div class="font-mono text-xs text-text-muted" dir="ltr">{{ $order->booking->booking_number }}</div></td><td data-label="{{ $ar ? 'العميل' : 'Customer' }}">{{ $ar ? $order->booking->customer->name_ar : $order->booking->customer->name_en }}</td><td data-label="{{ $ar ? 'موقع العمل' : 'Work location' }}">{{ $ar ? $order->store->name_ar : $order->store->name_en }}</td><td data-label="{{ $ar ? 'الحالة' : 'Status' }}"><x-status.badge :status="$order->status" /></td><td data-label="{{ $ar ? 'الإجراء' : 'Action' }}" class="text-end"><x-actions.button semantic="view" :label="$ar ? 'فتح' : 'Open'" :href="route('parties.orders.show', $order->id)">{{ $ar ? 'فتح' : 'Open' }}</x-actions.button></td></tr>@empty<tr><td colspan="5"><x-state.empty :title="app()->isLocale('ar-EG') ? 'مفيش أوامر تشغيل مطابقة' : ($ar ? 'لا توجد أوامر تشغيل مطابقة' : 'No matching operating orders')" :description="$ar ? 'يُنشأ أمر التشغيل من حجز مؤكد.' : 'Operating orders are created from confirmed bookings.'" /></td></tr>@endforelse</tbody></table></div><x-slot:footer>@if($orders->hasPages()){{ $orders->links() }}@endif</x-slot:footer>
        </x-tables.data-panel>
    </x-app.page>
</x-layouts::app>
